/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  AttributeMetaInfo,
  AttributeMetaInfoList,
  BatchResponseEntity,
  Consignment,
  ConsignmentList,
  DeleteRowResult,
  Errors,
  Metadata,
} from '../models/index.js';
import {
    AttributeMetaInfoFromJSON,
    AttributeMetaInfoToJSON,
    AttributeMetaInfoListFromJSON,
    AttributeMetaInfoListToJSON,
    BatchResponseEntityFromJSON,
    BatchResponseEntityToJSON,
    ConsignmentFromJSON,
    ConsignmentToJSON,
    ConsignmentListFromJSON,
    ConsignmentListToJSON,
    DeleteRowResultFromJSON,
    DeleteRowResultToJSON,
    ErrorsFromJSON,
    ErrorsToJSON,
    MetadataFromJSON,
    MetadataToJSON,
} from '../models/index.js';

export interface CreateConsignmentRequest {
    consignment: Omit<Consignment, 'id'|'accountId'|'images'|'name'|'updated'>;
    expand?: string;
    accept?: CreateConsignmentAcceptEnum;
    acceptEncoding?: string;
    contentType?: CreateConsignmentContentTypeEnum;
}

export interface CreateConsignmentMetadataAttributeRequest {
    attributeMetaInfo: AttributeMetaInfo;
    accept?: CreateConsignmentMetadataAttributeAcceptEnum;
    acceptEncoding?: string;
    contentType?: CreateConsignmentMetadataAttributeContentTypeEnum;
}

export interface CreateConsignmentsBatchRequest {
    consignment: Array<Consignment>;
    expand?: string;
    accept?: CreateConsignmentsBatchAcceptEnum;
    acceptEncoding?: string;
    contentType?: CreateConsignmentsBatchContentTypeEnum;
}

export interface DeleteConsignmentRequest {
    id: string;
    accept?: DeleteConsignmentAcceptEnum;
    acceptEncoding?: string;
}

export interface DeleteConsignmentMetadataAttributeRequest {
    id: string;
    accept?: DeleteConsignmentMetadataAttributeAcceptEnum;
    acceptEncoding?: string;
}

export interface DeleteConsignmentsBatchRequest {
    consignment: Array<Consignment>;
    accept?: DeleteConsignmentsBatchAcceptEnum;
    acceptEncoding?: string;
    contentType?: DeleteConsignmentsBatchContentTypeEnum;
}

export interface GetConsignmentByIdRequest {
    id: string;
    expand?: string;
    accept?: GetConsignmentByIdAcceptEnum;
    acceptEncoding?: string;
}

export interface GetConsignmentMetadataRequest {
    accept?: GetConsignmentMetadataAcceptEnum;
    acceptEncoding?: string;
}

export interface GetConsignmentMetadataAttributeByIdRequest {
    id: string;
    accept?: GetConsignmentMetadataAttributeByIdAcceptEnum;
    acceptEncoding?: string;
}

export interface GetConsignmentMetadataAttributesRequest {
    accept?: GetConsignmentMetadataAttributesAcceptEnum;
    acceptEncoding?: string;
}

export interface GetConsignmentsRequest {
    limit?: number;
    offset?: number;
    search?: string;
    filter?: string;
    expand?: string;
    order?: string;
    accept?: GetConsignmentsAcceptEnum;
    acceptEncoding?: string;
}

export interface UpdateConsignmentRequest {
    id: string;
    consignment: Omit<Consignment, 'id'|'accountId'|'images'|'name'|'updated'>;
    expand?: string;
    accept?: UpdateConsignmentAcceptEnum;
    acceptEncoding?: string;
    contentType?: UpdateConsignmentContentTypeEnum;
}

export interface UpdateConsignmentMetadataAttributeRequest {
    id: string;
    attributeMetaInfo: AttributeMetaInfo;
    accept?: UpdateConsignmentMetadataAttributeAcceptEnum;
    acceptEncoding?: string;
    contentType?: UpdateConsignmentMetadataAttributeContentTypeEnum;
}

/**
 * 
 */
export class ConsignmentsApi extends runtime.BaseAPI {

    /**
     * Создание новой партии
     * Создать партию
     */
    async createConsignmentRaw(requestParameters: CreateConsignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Consignment>> {
        if (requestParameters['consignment'] == null) {
            throw new runtime.RequiredError(
                'consignment',
                'Required parameter "consignment" was null or undefined when calling createConsignment().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConsignmentToJSON(requestParameters['consignment']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsignmentFromJSON(jsonValue));
    }

    /**
     * Создание новой партии
     * Создать партию
     */
    async createConsignment(requestParameters: CreateConsignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Consignment> {
        const response = await this.createConsignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Создание нового доп. поля для партий
     * Создать доп. поле партии
     */
    async createConsignmentMetadataAttributeRaw(requestParameters: CreateConsignmentMetadataAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AttributeMetaInfo>> {
        if (requestParameters['attributeMetaInfo'] == null) {
            throw new runtime.RequiredError(
                'attributeMetaInfo',
                'Required parameter "attributeMetaInfo" was null or undefined when calling createConsignmentMetadataAttribute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment/metadata/attributes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AttributeMetaInfoToJSON(requestParameters['attributeMetaInfo']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttributeMetaInfoFromJSON(jsonValue));
    }

    /**
     * Создание нового доп. поля для партий
     * Создать доп. поле партии
     */
    async createConsignmentMetadataAttribute(requestParameters: CreateConsignmentMetadataAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AttributeMetaInfo> {
        const response = await this.createConsignmentMetadataAttributeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Создание или изменение нескольких партий.
     * Создать или изменить партии
     */
    async createConsignmentsBatchRaw(requestParameters: CreateConsignmentsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BatchResponseEntity>>> {
        if (requestParameters['consignment'] == null) {
            throw new runtime.RequiredError(
                'consignment',
                'Required parameter "consignment" was null or undefined when calling createConsignmentsBatch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment/batch`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['consignment']!.map(ConsignmentToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BatchResponseEntityFromJSON));
    }

    /**
     * Создание или изменение нескольких партий.
     * Создать или изменить партии
     */
    async createConsignmentsBatch(requestParameters: CreateConsignmentsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BatchResponseEntity>> {
        const response = await this.createConsignmentsBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Удаление Партии с указанным id
     * Удалить партию
     */
    async deleteConsignmentRaw(requestParameters: DeleteConsignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteConsignment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Удаление Партии с указанным id
     * Удалить партию
     */
    async deleteConsignment(requestParameters: DeleteConsignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConsignmentRaw(requestParameters, initOverrides);
    }

    /**
     * Удаление доп. поля
     * Удалить доп. поле партии
     */
    async deleteConsignmentMetadataAttributeRaw(requestParameters: DeleteConsignmentMetadataAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteConsignmentMetadataAttribute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment/metadata/attributes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Удаление доп. поля
     * Удалить доп. поле партии
     */
    async deleteConsignmentMetadataAttribute(requestParameters: DeleteConsignmentMetadataAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConsignmentMetadataAttributeRaw(requestParameters, initOverrides);
    }

    /**
     * Массовое удаление партий по их мета-объектам.
     * Удалить партии
     */
    async deleteConsignmentsBatchRaw(requestParameters: DeleteConsignmentsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DeleteRowResult>>> {
        if (requestParameters['consignment'] == null) {
            throw new runtime.RequiredError(
                'consignment',
                'Required parameter "consignment" was null or undefined when calling deleteConsignmentsBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment/delete`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['consignment']!.map(ConsignmentToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DeleteRowResultFromJSON));
    }

    /**
     * Массовое удаление партий по их мета-объектам.
     * Удалить партии
     */
    async deleteConsignmentsBatch(requestParameters: DeleteConsignmentsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DeleteRowResult>> {
        const response = await this.deleteConsignmentsBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Запрос на получение Партии с указанным id
     * Получить партию по ID
     */
    async getConsignmentByIdRaw(requestParameters: GetConsignmentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Consignment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getConsignmentById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsignmentFromJSON(jsonValue));
    }

    /**
     * Запрос на получение Партии с указанным id
     * Получить партию по ID
     */
    async getConsignmentById(requestParameters: GetConsignmentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Consignment> {
        const response = await this.getConsignmentByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Запрос на получение метаданных партий
     * Получить метаданные партий
     */
    async getConsignmentMetadataRaw(requestParameters: GetConsignmentMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Metadata>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment/metadata`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataFromJSON(jsonValue));
    }

    /**
     * Запрос на получение метаданных партий
     * Получить метаданные партий
     */
    async getConsignmentMetadata(requestParameters: GetConsignmentMetadataRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Metadata> {
        const response = await this.getConsignmentMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Запрос на получение отдельного доп. поля
     * Получить доп. поле партии по ID
     */
    async getConsignmentMetadataAttributeByIdRaw(requestParameters: GetConsignmentMetadataAttributeByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AttributeMetaInfo>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getConsignmentMetadataAttributeById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment/metadata/attributes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttributeMetaInfoFromJSON(jsonValue));
    }

    /**
     * Запрос на получение отдельного доп. поля
     * Получить доп. поле партии по ID
     */
    async getConsignmentMetadataAttributeById(requestParameters: GetConsignmentMetadataAttributeByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AttributeMetaInfo> {
        const response = await this.getConsignmentMetadataAttributeByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Запрос на получение всех доп. полей для партий
     * Получить доп. поля партий
     */
    async getConsignmentMetadataAttributesRaw(requestParameters: GetConsignmentMetadataAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AttributeMetaInfoList>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment/metadata/attributes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttributeMetaInfoListFromJSON(jsonValue));
    }

    /**
     * Запрос на получение всех доп. полей для партий
     * Получить доп. поля партий
     */
    async getConsignmentMetadataAttributes(requestParameters: GetConsignmentMetadataAttributesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AttributeMetaInfoList> {
        const response = await this.getConsignmentMetadataAttributesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Запрос всех партий на данной учетной записи
     * Получить список партий
     */
    async getConsignmentsRaw(requestParameters: GetConsignmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConsignmentList>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsignmentListFromJSON(jsonValue));
    }

    /**
     * Запрос всех партий на данной учетной записи
     * Получить список партий
     */
    async getConsignments(requestParameters: GetConsignmentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConsignmentList> {
        const response = await this.getConsignmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Обновление Партии с указанным id
     * Обновить партию
     */
    async updateConsignmentRaw(requestParameters: UpdateConsignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Consignment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateConsignment().'
            );
        }

        if (requestParameters['consignment'] == null) {
            throw new runtime.RequiredError(
                'consignment',
                'Required parameter "consignment" was null or undefined when calling updateConsignment().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ConsignmentToJSON(requestParameters['consignment']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsignmentFromJSON(jsonValue));
    }

    /**
     * Обновление Партии с указанным id
     * Обновить партию
     */
    async updateConsignment(requestParameters: UpdateConsignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Consignment> {
        const response = await this.updateConsignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Обновление доп. поля для партий
     * Обновить доп. поле партии
     */
    async updateConsignmentMetadataAttributeRaw(requestParameters: UpdateConsignmentMetadataAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AttributeMetaInfo>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateConsignmentMetadataAttribute().'
            );
        }

        if (requestParameters['attributeMetaInfo'] == null) {
            throw new runtime.RequiredError(
                'attributeMetaInfo',
                'Required parameter "attributeMetaInfo" was null or undefined when calling updateConsignmentMetadataAttribute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/consignment/metadata/attributes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AttributeMetaInfoToJSON(requestParameters['attributeMetaInfo']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttributeMetaInfoFromJSON(jsonValue));
    }

    /**
     * Обновление доп. поля для партий
     * Обновить доп. поле партии
     */
    async updateConsignmentMetadataAttribute(requestParameters: UpdateConsignmentMetadataAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AttributeMetaInfo> {
        const response = await this.updateConsignmentMetadataAttributeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateConsignmentAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type CreateConsignmentAcceptEnum = typeof CreateConsignmentAcceptEnum[keyof typeof CreateConsignmentAcceptEnum];
/**
 * @export
 */
export const CreateConsignmentContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type CreateConsignmentContentTypeEnum = typeof CreateConsignmentContentTypeEnum[keyof typeof CreateConsignmentContentTypeEnum];
/**
 * @export
 */
export const CreateConsignmentMetadataAttributeAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type CreateConsignmentMetadataAttributeAcceptEnum = typeof CreateConsignmentMetadataAttributeAcceptEnum[keyof typeof CreateConsignmentMetadataAttributeAcceptEnum];
/**
 * @export
 */
export const CreateConsignmentMetadataAttributeContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type CreateConsignmentMetadataAttributeContentTypeEnum = typeof CreateConsignmentMetadataAttributeContentTypeEnum[keyof typeof CreateConsignmentMetadataAttributeContentTypeEnum];
/**
 * @export
 */
export const CreateConsignmentsBatchAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type CreateConsignmentsBatchAcceptEnum = typeof CreateConsignmentsBatchAcceptEnum[keyof typeof CreateConsignmentsBatchAcceptEnum];
/**
 * @export
 */
export const CreateConsignmentsBatchContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type CreateConsignmentsBatchContentTypeEnum = typeof CreateConsignmentsBatchContentTypeEnum[keyof typeof CreateConsignmentsBatchContentTypeEnum];
/**
 * @export
 */
export const DeleteConsignmentAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type DeleteConsignmentAcceptEnum = typeof DeleteConsignmentAcceptEnum[keyof typeof DeleteConsignmentAcceptEnum];
/**
 * @export
 */
export const DeleteConsignmentMetadataAttributeAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type DeleteConsignmentMetadataAttributeAcceptEnum = typeof DeleteConsignmentMetadataAttributeAcceptEnum[keyof typeof DeleteConsignmentMetadataAttributeAcceptEnum];
/**
 * @export
 */
export const DeleteConsignmentsBatchAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type DeleteConsignmentsBatchAcceptEnum = typeof DeleteConsignmentsBatchAcceptEnum[keyof typeof DeleteConsignmentsBatchAcceptEnum];
/**
 * @export
 */
export const DeleteConsignmentsBatchContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type DeleteConsignmentsBatchContentTypeEnum = typeof DeleteConsignmentsBatchContentTypeEnum[keyof typeof DeleteConsignmentsBatchContentTypeEnum];
/**
 * @export
 */
export const GetConsignmentByIdAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type GetConsignmentByIdAcceptEnum = typeof GetConsignmentByIdAcceptEnum[keyof typeof GetConsignmentByIdAcceptEnum];
/**
 * @export
 */
export const GetConsignmentMetadataAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type GetConsignmentMetadataAcceptEnum = typeof GetConsignmentMetadataAcceptEnum[keyof typeof GetConsignmentMetadataAcceptEnum];
/**
 * @export
 */
export const GetConsignmentMetadataAttributeByIdAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type GetConsignmentMetadataAttributeByIdAcceptEnum = typeof GetConsignmentMetadataAttributeByIdAcceptEnum[keyof typeof GetConsignmentMetadataAttributeByIdAcceptEnum];
/**
 * @export
 */
export const GetConsignmentMetadataAttributesAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type GetConsignmentMetadataAttributesAcceptEnum = typeof GetConsignmentMetadataAttributesAcceptEnum[keyof typeof GetConsignmentMetadataAttributesAcceptEnum];
/**
 * @export
 */
export const GetConsignmentsAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type GetConsignmentsAcceptEnum = typeof GetConsignmentsAcceptEnum[keyof typeof GetConsignmentsAcceptEnum];
/**
 * @export
 */
export const UpdateConsignmentAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type UpdateConsignmentAcceptEnum = typeof UpdateConsignmentAcceptEnum[keyof typeof UpdateConsignmentAcceptEnum];
/**
 * @export
 */
export const UpdateConsignmentContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type UpdateConsignmentContentTypeEnum = typeof UpdateConsignmentContentTypeEnum[keyof typeof UpdateConsignmentContentTypeEnum];
/**
 * @export
 */
export const UpdateConsignmentMetadataAttributeAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type UpdateConsignmentMetadataAttributeAcceptEnum = typeof UpdateConsignmentMetadataAttributeAcceptEnum[keyof typeof UpdateConsignmentMetadataAttributeAcceptEnum];
/**
 * @export
 */
export const UpdateConsignmentMetadataAttributeContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type UpdateConsignmentMetadataAttributeContentTypeEnum = typeof UpdateConsignmentMetadataAttributeContentTypeEnum[keyof typeof UpdateConsignmentMetadataAttributeContentTypeEnum];
