/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  BatchResponseEntity,
  DocumentMetadata,
  EmissionOrder,
  EmissionOrderList,
  EmissionOrderPosition,
  EmissionOrderPositionList,
  Errors,
  State,
  StateRowResult,
} from '../models/index.js';
import {
    BatchResponseEntityFromJSON,
    BatchResponseEntityToJSON,
    DocumentMetadataFromJSON,
    DocumentMetadataToJSON,
    EmissionOrderFromJSON,
    EmissionOrderToJSON,
    EmissionOrderListFromJSON,
    EmissionOrderListToJSON,
    EmissionOrderPositionFromJSON,
    EmissionOrderPositionToJSON,
    EmissionOrderPositionListFromJSON,
    EmissionOrderPositionListToJSON,
    ErrorsFromJSON,
    ErrorsToJSON,
    StateFromJSON,
    StateToJSON,
    StateRowResultFromJSON,
    StateRowResultToJSON,
} from '../models/index.js';

export interface CreateEmissionOrderRequest {
    emissionOrder: Omit<EmissionOrder, 'id'|'accountId'|'created'|'documentState'|'printed'|'published'|'updated'>;
    expand?: string;
    accept?: CreateEmissionOrderAcceptEnum;
    acceptEncoding?: string;
    contentType?: CreateEmissionOrderContentTypeEnum;
}

export interface CreateEmissionOrderBatchRequest {
    emissionOrder: Array<EmissionOrder>;
    expand?: string;
    accept?: CreateEmissionOrderBatchAcceptEnum;
    acceptEncoding?: string;
    contentType?: CreateEmissionOrderBatchContentTypeEnum;
}

export interface CreateEmissionOrderMetadataStateRequest {
    state: Omit<State, 'id'|'accountId'|'entityType'>;
    accept?: CreateEmissionOrderMetadataStateAcceptEnum;
    acceptEncoding?: string;
    contentType?: CreateEmissionOrderMetadataStateContentTypeEnum;
}

export interface CreateEmissionOrderMetadataStatesBatchRequest {
    state: Array<State>;
    accept?: CreateEmissionOrderMetadataStatesBatchAcceptEnum;
    acceptEncoding?: string;
    contentType?: CreateEmissionOrderMetadataStatesBatchContentTypeEnum;
}

export interface CreateEmissionOrderPositionRequest {
    id: string;
    emissionOrderPosition: Omit<EmissionOrderPosition, 'id'|'accountId'|'status'>;
    expand?: string;
    accept?: CreateEmissionOrderPositionAcceptEnum;
    acceptEncoding?: string;
    contentType?: CreateEmissionOrderPositionContentTypeEnum;
}

export interface CreateEmissionOrderPositionsRequest {
    id: string;
    emissionOrderPosition: Array<EmissionOrderPosition>;
    expand?: string;
    accept?: CreateEmissionOrderPositionsAcceptEnum;
    acceptEncoding?: string;
    contentType?: CreateEmissionOrderPositionsContentTypeEnum;
}

export interface DeleteEmissionOrderMetadataStateByIdRequest {
    id: string;
    accept?: DeleteEmissionOrderMetadataStateByIdAcceptEnum;
    acceptEncoding?: string;
    contentType?: DeleteEmissionOrderMetadataStateByIdContentTypeEnum;
}

export interface GetEmissionOrderByIdRequest {
    id: string;
    expand?: string;
    fields?: GetEmissionOrderByIdFieldsEnum;
    accept?: GetEmissionOrderByIdAcceptEnum;
    acceptEncoding?: string;
}

export interface GetEmissionOrderListRequest {
    limit?: number;
    offset?: number;
    expand?: string;
    fields?: GetEmissionOrderListFieldsEnum;
    accept?: GetEmissionOrderListAcceptEnum;
    acceptEncoding?: string;
}

export interface GetEmissionOrderMetadataRequest {
    accept?: GetEmissionOrderMetadataAcceptEnum;
    acceptEncoding?: string;
    contentType?: GetEmissionOrderMetadataContentTypeEnum;
}

export interface GetEmissionOrderMetadataStateByIdRequest {
    id: string;
    accept?: GetEmissionOrderMetadataStateByIdAcceptEnum;
    acceptEncoding?: string;
    contentType?: GetEmissionOrderMetadataStateByIdContentTypeEnum;
}

export interface GetEmissionOrderPositionByIdRequest {
    id: string;
    positionId: string;
    expand?: string;
    fields?: GetEmissionOrderPositionByIdFieldsEnum;
    accept?: GetEmissionOrderPositionByIdAcceptEnum;
    acceptEncoding?: string;
}

export interface GetEmissionOrderPositionsRequest {
    id: string;
    limit?: number;
    offset?: number;
    expand?: string;
    fields?: GetEmissionOrderPositionsFieldsEnum;
    accept?: GetEmissionOrderPositionsAcceptEnum;
    acceptEncoding?: string;
}

export interface MoveEmissionOrderToTrashRequest {
    id: string;
    accept?: MoveEmissionOrderToTrashAcceptEnum;
    acceptEncoding?: string;
}

export interface UpdateEmissionOrderRequest {
    id: string;
    emissionOrder: Omit<EmissionOrder, 'id'|'accountId'|'created'|'documentState'|'printed'|'published'|'updated'>;
    expand?: string;
    fields?: UpdateEmissionOrderFieldsEnum;
    accept?: UpdateEmissionOrderAcceptEnum;
    acceptEncoding?: string;
    contentType?: UpdateEmissionOrderContentTypeEnum;
}

export interface UpdateEmissionOrderMetadataStateByIdRequest {
    id: string;
    state: Omit<State, 'id'|'accountId'|'entityType'>;
    accept?: UpdateEmissionOrderMetadataStateByIdAcceptEnum;
    acceptEncoding?: string;
    contentType?: UpdateEmissionOrderMetadataStateByIdContentTypeEnum;
}

export interface UpdateEmissionOrderPositionRequest {
    id: string;
    positionId: string;
    emissionOrderPosition: Omit<EmissionOrderPosition, 'id'|'accountId'|'status'>;
    expand?: string;
    fields?: UpdateEmissionOrderPositionFieldsEnum;
    accept?: UpdateEmissionOrderPositionAcceptEnum;
    acceptEncoding?: string;
    contentType?: UpdateEmissionOrderPositionContentTypeEnum;
}

/**
 * 
 */
export class EmissionOrdersApi extends runtime.BaseAPI {

    /**
     * Создать Заказ кодов маркировки
     */
    async createEmissionOrderRaw(requestParameters: CreateEmissionOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmissionOrder>> {
        if (requestParameters['emissionOrder'] == null) {
            throw new runtime.RequiredError(
                'emissionOrder',
                'Required parameter "emissionOrder" was null or undefined when calling createEmissionOrder().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmissionOrderToJSON(requestParameters['emissionOrder']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmissionOrderFromJSON(jsonValue));
    }

    /**
     * Создать Заказ кодов маркировки
     */
    async createEmissionOrder(requestParameters: CreateEmissionOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmissionOrder> {
        const response = await this.createEmissionOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Массовое создание и обновление Заказов кодов маркировки
     */
    async createEmissionOrderBatchRaw(requestParameters: CreateEmissionOrderBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BatchResponseEntity>>> {
        if (requestParameters['emissionOrder'] == null) {
            throw new runtime.RequiredError(
                'emissionOrder',
                'Required parameter "emissionOrder" was null or undefined when calling createEmissionOrderBatch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/batch`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['emissionOrder']!.map(EmissionOrderToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BatchResponseEntityFromJSON));
    }

    /**
     * Массовое создание и обновление Заказов кодов маркировки
     */
    async createEmissionOrderBatch(requestParameters: CreateEmissionOrderBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BatchResponseEntity>> {
        const response = await this.createEmissionOrderBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Создать статус Заказа кодов маркировки
     */
    async createEmissionOrderMetadataStateRaw(requestParameters: CreateEmissionOrderMetadataStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<State>> {
        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling createEmissionOrderMetadataState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/metadata/states`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StateToJSON(requestParameters['state']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StateFromJSON(jsonValue));
    }

    /**
     * Создать статус Заказа кодов маркировки
     */
    async createEmissionOrderMetadataState(requestParameters: CreateEmissionOrderMetadataStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<State> {
        const response = await this.createEmissionOrderMetadataStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Массовое создание и обновление статусов Заказа кодов маркировки
     */
    async createEmissionOrderMetadataStatesBatchRaw(requestParameters: CreateEmissionOrderMetadataStatesBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StateRowResult>>> {
        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling createEmissionOrderMetadataStatesBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/metadata/states/batch`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['state']!.map(StateToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StateRowResultFromJSON));
    }

    /**
     * Массовое создание и обновление статусов Заказа кодов маркировки
     */
    async createEmissionOrderMetadataStatesBatch(requestParameters: CreateEmissionOrderMetadataStatesBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StateRowResult>> {
        const response = await this.createEmissionOrderMetadataStatesBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Создать и обновить позицию Заказа кодов маркировки
     */
    async createEmissionOrderPositionRaw(requestParameters: CreateEmissionOrderPositionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EmissionOrderPosition>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createEmissionOrderPosition().'
            );
        }

        if (requestParameters['emissionOrderPosition'] == null) {
            throw new runtime.RequiredError(
                'emissionOrderPosition',
                'Required parameter "emissionOrderPosition" was null or undefined when calling createEmissionOrderPosition().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/{id}/positions`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmissionOrderPositionToJSON(requestParameters['emissionOrderPosition']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EmissionOrderPositionFromJSON));
    }

    /**
     * Создать и обновить позицию Заказа кодов маркировки
     */
    async createEmissionOrderPosition(requestParameters: CreateEmissionOrderPositionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EmissionOrderPosition>> {
        const response = await this.createEmissionOrderPositionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Массовое создание и обновление позиций Заказа кодов маркировки
     */
    async createEmissionOrderPositionsRaw(requestParameters: CreateEmissionOrderPositionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BatchResponseEntity>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createEmissionOrderPositions().'
            );
        }

        if (requestParameters['emissionOrderPosition'] == null) {
            throw new runtime.RequiredError(
                'emissionOrderPosition',
                'Required parameter "emissionOrderPosition" was null or undefined when calling createEmissionOrderPositions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/{id}/positions/batch`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['emissionOrderPosition']!.map(EmissionOrderPositionToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BatchResponseEntityFromJSON));
    }

    /**
     * Массовое создание и обновление позиций Заказа кодов маркировки
     */
    async createEmissionOrderPositions(requestParameters: CreateEmissionOrderPositionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BatchResponseEntity>> {
        const response = await this.createEmissionOrderPositionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Удалить отдельный статус Заказа кодов маркировки
     */
    async deleteEmissionOrderMetadataStateByIdRaw(requestParameters: DeleteEmissionOrderMetadataStateByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteEmissionOrderMetadataStateById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/metadata/states/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Удалить отдельный статус Заказа кодов маркировки
     */
    async deleteEmissionOrderMetadataStateById(requestParameters: DeleteEmissionOrderMetadataStateByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEmissionOrderMetadataStateByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Получить Заказ кодов маркировки
     */
    async getEmissionOrderByIdRaw(requestParameters: GetEmissionOrderByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmissionOrder>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEmissionOrderById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmissionOrderFromJSON(jsonValue));
    }

    /**
     * Получить Заказ кодов маркировки
     */
    async getEmissionOrderById(requestParameters: GetEmissionOrderByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmissionOrder> {
        const response = await this.getEmissionOrderByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Получить список Заказов кодов маркировки
     */
    async getEmissionOrderListRaw(requestParameters: GetEmissionOrderListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmissionOrderList>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmissionOrderListFromJSON(jsonValue));
    }

    /**
     * Получить список Заказов кодов маркировки
     */
    async getEmissionOrderList(requestParameters: GetEmissionOrderListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmissionOrderList> {
        const response = await this.getEmissionOrderListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Метаданные Заказов кодов маркировки
     */
    async getEmissionOrderMetadataRaw(requestParameters: GetEmissionOrderMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentMetadata>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/metadata`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentMetadataFromJSON(jsonValue));
    }

    /**
     * Метаданные Заказов кодов маркировки
     */
    async getEmissionOrderMetadata(requestParameters: GetEmissionOrderMetadataRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentMetadata> {
        const response = await this.getEmissionOrderMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Отдельный статус Заказа кодов маркировки
     */
    async getEmissionOrderMetadataStateByIdRaw(requestParameters: GetEmissionOrderMetadataStateByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<State>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEmissionOrderMetadataStateById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/metadata/states/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StateFromJSON(jsonValue));
    }

    /**
     * Отдельный статус Заказа кодов маркировки
     */
    async getEmissionOrderMetadataStateById(requestParameters: GetEmissionOrderMetadataStateByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<State> {
        const response = await this.getEmissionOrderMetadataStateByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Получить позицию Заказа кодов маркировки
     */
    async getEmissionOrderPositionByIdRaw(requestParameters: GetEmissionOrderPositionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmissionOrderPosition>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEmissionOrderPositionById().'
            );
        }

        if (requestParameters['positionId'] == null) {
            throw new runtime.RequiredError(
                'positionId',
                'Required parameter "positionId" was null or undefined when calling getEmissionOrderPositionById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/{id}/positions/{positionId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"positionId"}}`, encodeURIComponent(String(requestParameters['positionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmissionOrderPositionFromJSON(jsonValue));
    }

    /**
     * Получить позицию Заказа кодов маркировки
     */
    async getEmissionOrderPositionById(requestParameters: GetEmissionOrderPositionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmissionOrderPosition> {
        const response = await this.getEmissionOrderPositionByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Получить позиции Заказа кодов маркировки
     */
    async getEmissionOrderPositionsRaw(requestParameters: GetEmissionOrderPositionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmissionOrderPositionList>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEmissionOrderPositions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/{id}/positions`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmissionOrderPositionListFromJSON(jsonValue));
    }

    /**
     * Получить позиции Заказа кодов маркировки
     */
    async getEmissionOrderPositions(requestParameters: GetEmissionOrderPositionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmissionOrderPositionList> {
        const response = await this.getEmissionOrderPositionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Удалить Заказ кодов маркировки в корзину
     */
    async moveEmissionOrderToTrashRaw(requestParameters: MoveEmissionOrderToTrashRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling moveEmissionOrderToTrash().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/{id}/trash`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Удалить Заказ кодов маркировки в корзину
     */
    async moveEmissionOrderToTrash(requestParameters: MoveEmissionOrderToTrashRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.moveEmissionOrderToTrashRaw(requestParameters, initOverrides);
    }

    /**
     * Изменить Заказ кодов маркировки
     */
    async updateEmissionOrderRaw(requestParameters: UpdateEmissionOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmissionOrder>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateEmissionOrder().'
            );
        }

        if (requestParameters['emissionOrder'] == null) {
            throw new runtime.RequiredError(
                'emissionOrder',
                'Required parameter "emissionOrder" was null or undefined when calling updateEmissionOrder().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EmissionOrderToJSON(requestParameters['emissionOrder']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmissionOrderFromJSON(jsonValue));
    }

    /**
     * Изменить Заказ кодов маркировки
     */
    async updateEmissionOrder(requestParameters: UpdateEmissionOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmissionOrder> {
        const response = await this.updateEmissionOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Обновить отдельный статус Заказа кодов маркировки
     */
    async updateEmissionOrderMetadataStateByIdRaw(requestParameters: UpdateEmissionOrderMetadataStateByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<State>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateEmissionOrderMetadataStateById().'
            );
        }

        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling updateEmissionOrderMetadataStateById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/metadata/states/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StateToJSON(requestParameters['state']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StateFromJSON(jsonValue));
    }

    /**
     * Обновить отдельный статус Заказа кодов маркировки
     */
    async updateEmissionOrderMetadataStateById(requestParameters: UpdateEmissionOrderMetadataStateByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<State> {
        const response = await this.updateEmissionOrderMetadataStateByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Изменить позицию Заказа кодов маркировки
     */
    async updateEmissionOrderPositionRaw(requestParameters: UpdateEmissionOrderPositionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmissionOrderPosition>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateEmissionOrderPosition().'
            );
        }

        if (requestParameters['positionId'] == null) {
            throw new runtime.RequiredError(
                'positionId',
                'Required parameter "positionId" was null or undefined when calling updateEmissionOrderPosition().'
            );
        }

        if (requestParameters['emissionOrderPosition'] == null) {
            throw new runtime.RequiredError(
                'emissionOrderPosition',
                'Required parameter "emissionOrderPosition" was null or undefined when calling updateEmissionOrderPosition().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/emissionorder/{id}/positions/{positionId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"positionId"}}`, encodeURIComponent(String(requestParameters['positionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EmissionOrderPositionToJSON(requestParameters['emissionOrderPosition']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmissionOrderPositionFromJSON(jsonValue));
    }

    /**
     * Изменить позицию Заказа кодов маркировки
     */
    async updateEmissionOrderPosition(requestParameters: UpdateEmissionOrderPositionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmissionOrderPosition> {
        const response = await this.updateEmissionOrderPositionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateEmissionOrderAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type CreateEmissionOrderAcceptEnum = typeof CreateEmissionOrderAcceptEnum[keyof typeof CreateEmissionOrderAcceptEnum];
/**
 * @export
 */
export const CreateEmissionOrderContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type CreateEmissionOrderContentTypeEnum = typeof CreateEmissionOrderContentTypeEnum[keyof typeof CreateEmissionOrderContentTypeEnum];
/**
 * @export
 */
export const CreateEmissionOrderBatchAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type CreateEmissionOrderBatchAcceptEnum = typeof CreateEmissionOrderBatchAcceptEnum[keyof typeof CreateEmissionOrderBatchAcceptEnum];
/**
 * @export
 */
export const CreateEmissionOrderBatchContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type CreateEmissionOrderBatchContentTypeEnum = typeof CreateEmissionOrderBatchContentTypeEnum[keyof typeof CreateEmissionOrderBatchContentTypeEnum];
/**
 * @export
 */
export const CreateEmissionOrderMetadataStateAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type CreateEmissionOrderMetadataStateAcceptEnum = typeof CreateEmissionOrderMetadataStateAcceptEnum[keyof typeof CreateEmissionOrderMetadataStateAcceptEnum];
/**
 * @export
 */
export const CreateEmissionOrderMetadataStateContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type CreateEmissionOrderMetadataStateContentTypeEnum = typeof CreateEmissionOrderMetadataStateContentTypeEnum[keyof typeof CreateEmissionOrderMetadataStateContentTypeEnum];
/**
 * @export
 */
export const CreateEmissionOrderMetadataStatesBatchAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type CreateEmissionOrderMetadataStatesBatchAcceptEnum = typeof CreateEmissionOrderMetadataStatesBatchAcceptEnum[keyof typeof CreateEmissionOrderMetadataStatesBatchAcceptEnum];
/**
 * @export
 */
export const CreateEmissionOrderMetadataStatesBatchContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type CreateEmissionOrderMetadataStatesBatchContentTypeEnum = typeof CreateEmissionOrderMetadataStatesBatchContentTypeEnum[keyof typeof CreateEmissionOrderMetadataStatesBatchContentTypeEnum];
/**
 * @export
 */
export const CreateEmissionOrderPositionAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type CreateEmissionOrderPositionAcceptEnum = typeof CreateEmissionOrderPositionAcceptEnum[keyof typeof CreateEmissionOrderPositionAcceptEnum];
/**
 * @export
 */
export const CreateEmissionOrderPositionContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type CreateEmissionOrderPositionContentTypeEnum = typeof CreateEmissionOrderPositionContentTypeEnum[keyof typeof CreateEmissionOrderPositionContentTypeEnum];
/**
 * @export
 */
export const CreateEmissionOrderPositionsAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type CreateEmissionOrderPositionsAcceptEnum = typeof CreateEmissionOrderPositionsAcceptEnum[keyof typeof CreateEmissionOrderPositionsAcceptEnum];
/**
 * @export
 */
export const CreateEmissionOrderPositionsContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type CreateEmissionOrderPositionsContentTypeEnum = typeof CreateEmissionOrderPositionsContentTypeEnum[keyof typeof CreateEmissionOrderPositionsContentTypeEnum];
/**
 * @export
 */
export const DeleteEmissionOrderMetadataStateByIdAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type DeleteEmissionOrderMetadataStateByIdAcceptEnum = typeof DeleteEmissionOrderMetadataStateByIdAcceptEnum[keyof typeof DeleteEmissionOrderMetadataStateByIdAcceptEnum];
/**
 * @export
 */
export const DeleteEmissionOrderMetadataStateByIdContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type DeleteEmissionOrderMetadataStateByIdContentTypeEnum = typeof DeleteEmissionOrderMetadataStateByIdContentTypeEnum[keyof typeof DeleteEmissionOrderMetadataStateByIdContentTypeEnum];
/**
 * @export
 */
export const GetEmissionOrderByIdFieldsEnum = {
    MinimumStock: 'minimumStock',
    DownloadPermanentHref: 'downloadPermanentHref',
    Stock: 'stock',
    Declaration: 'declaration'
} as const;
export type GetEmissionOrderByIdFieldsEnum = typeof GetEmissionOrderByIdFieldsEnum[keyof typeof GetEmissionOrderByIdFieldsEnum];
/**
 * @export
 */
export const GetEmissionOrderByIdAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type GetEmissionOrderByIdAcceptEnum = typeof GetEmissionOrderByIdAcceptEnum[keyof typeof GetEmissionOrderByIdAcceptEnum];
/**
 * @export
 */
export const GetEmissionOrderListFieldsEnum = {
    MinimumStock: 'minimumStock',
    DownloadPermanentHref: 'downloadPermanentHref',
    Stock: 'stock',
    Declaration: 'declaration'
} as const;
export type GetEmissionOrderListFieldsEnum = typeof GetEmissionOrderListFieldsEnum[keyof typeof GetEmissionOrderListFieldsEnum];
/**
 * @export
 */
export const GetEmissionOrderListAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type GetEmissionOrderListAcceptEnum = typeof GetEmissionOrderListAcceptEnum[keyof typeof GetEmissionOrderListAcceptEnum];
/**
 * @export
 */
export const GetEmissionOrderMetadataAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type GetEmissionOrderMetadataAcceptEnum = typeof GetEmissionOrderMetadataAcceptEnum[keyof typeof GetEmissionOrderMetadataAcceptEnum];
/**
 * @export
 */
export const GetEmissionOrderMetadataContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type GetEmissionOrderMetadataContentTypeEnum = typeof GetEmissionOrderMetadataContentTypeEnum[keyof typeof GetEmissionOrderMetadataContentTypeEnum];
/**
 * @export
 */
export const GetEmissionOrderMetadataStateByIdAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type GetEmissionOrderMetadataStateByIdAcceptEnum = typeof GetEmissionOrderMetadataStateByIdAcceptEnum[keyof typeof GetEmissionOrderMetadataStateByIdAcceptEnum];
/**
 * @export
 */
export const GetEmissionOrderMetadataStateByIdContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type GetEmissionOrderMetadataStateByIdContentTypeEnum = typeof GetEmissionOrderMetadataStateByIdContentTypeEnum[keyof typeof GetEmissionOrderMetadataStateByIdContentTypeEnum];
/**
 * @export
 */
export const GetEmissionOrderPositionByIdFieldsEnum = {
    MinimumStock: 'minimumStock',
    DownloadPermanentHref: 'downloadPermanentHref',
    Stock: 'stock',
    Declaration: 'declaration'
} as const;
export type GetEmissionOrderPositionByIdFieldsEnum = typeof GetEmissionOrderPositionByIdFieldsEnum[keyof typeof GetEmissionOrderPositionByIdFieldsEnum];
/**
 * @export
 */
export const GetEmissionOrderPositionByIdAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type GetEmissionOrderPositionByIdAcceptEnum = typeof GetEmissionOrderPositionByIdAcceptEnum[keyof typeof GetEmissionOrderPositionByIdAcceptEnum];
/**
 * @export
 */
export const GetEmissionOrderPositionsFieldsEnum = {
    MinimumStock: 'minimumStock',
    DownloadPermanentHref: 'downloadPermanentHref',
    Stock: 'stock',
    Declaration: 'declaration'
} as const;
export type GetEmissionOrderPositionsFieldsEnum = typeof GetEmissionOrderPositionsFieldsEnum[keyof typeof GetEmissionOrderPositionsFieldsEnum];
/**
 * @export
 */
export const GetEmissionOrderPositionsAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type GetEmissionOrderPositionsAcceptEnum = typeof GetEmissionOrderPositionsAcceptEnum[keyof typeof GetEmissionOrderPositionsAcceptEnum];
/**
 * @export
 */
export const MoveEmissionOrderToTrashAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type MoveEmissionOrderToTrashAcceptEnum = typeof MoveEmissionOrderToTrashAcceptEnum[keyof typeof MoveEmissionOrderToTrashAcceptEnum];
/**
 * @export
 */
export const UpdateEmissionOrderFieldsEnum = {
    MinimumStock: 'minimumStock',
    DownloadPermanentHref: 'downloadPermanentHref',
    Stock: 'stock',
    Declaration: 'declaration'
} as const;
export type UpdateEmissionOrderFieldsEnum = typeof UpdateEmissionOrderFieldsEnum[keyof typeof UpdateEmissionOrderFieldsEnum];
/**
 * @export
 */
export const UpdateEmissionOrderAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type UpdateEmissionOrderAcceptEnum = typeof UpdateEmissionOrderAcceptEnum[keyof typeof UpdateEmissionOrderAcceptEnum];
/**
 * @export
 */
export const UpdateEmissionOrderContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type UpdateEmissionOrderContentTypeEnum = typeof UpdateEmissionOrderContentTypeEnum[keyof typeof UpdateEmissionOrderContentTypeEnum];
/**
 * @export
 */
export const UpdateEmissionOrderMetadataStateByIdAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type UpdateEmissionOrderMetadataStateByIdAcceptEnum = typeof UpdateEmissionOrderMetadataStateByIdAcceptEnum[keyof typeof UpdateEmissionOrderMetadataStateByIdAcceptEnum];
/**
 * @export
 */
export const UpdateEmissionOrderMetadataStateByIdContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type UpdateEmissionOrderMetadataStateByIdContentTypeEnum = typeof UpdateEmissionOrderMetadataStateByIdContentTypeEnum[keyof typeof UpdateEmissionOrderMetadataStateByIdContentTypeEnum];
/**
 * @export
 */
export const UpdateEmissionOrderPositionFieldsEnum = {
    MinimumStock: 'minimumStock',
    DownloadPermanentHref: 'downloadPermanentHref',
    Stock: 'stock',
    Declaration: 'declaration'
} as const;
export type UpdateEmissionOrderPositionFieldsEnum = typeof UpdateEmissionOrderPositionFieldsEnum[keyof typeof UpdateEmissionOrderPositionFieldsEnum];
/**
 * @export
 */
export const UpdateEmissionOrderPositionAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type UpdateEmissionOrderPositionAcceptEnum = typeof UpdateEmissionOrderPositionAcceptEnum[keyof typeof UpdateEmissionOrderPositionAcceptEnum];
/**
 * @export
 */
export const UpdateEmissionOrderPositionContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type UpdateEmissionOrderPositionContentTypeEnum = typeof UpdateEmissionOrderPositionContentTypeEnum[keyof typeof UpdateEmissionOrderPositionContentTypeEnum];
