/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  AttributeMetaInfo,
  Errors,
} from '../models/index.js';
import {
    AttributeMetaInfoFromJSON,
    AttributeMetaInfoToJSON,
    ErrorsFromJSON,
    ErrorsToJSON,
} from '../models/index.js';

export interface CreatePrepaymentMetadataAttributeRequest {
    attributeMetaInfo: AttributeMetaInfo;
    accept?: CreatePrepaymentMetadataAttributeAcceptEnum;
    acceptEncoding?: string;
    contentType?: CreatePrepaymentMetadataAttributeContentTypeEnum;
}

/**
 * 
 */
export class PrepaymentsApi extends runtime.BaseAPI {

    /**
     * Создать доп. поле Предоплаты
     */
    async createPrepaymentMetadataAttributeRaw(requestParameters: CreatePrepaymentMetadataAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AttributeMetaInfo>> {
        if (requestParameters['attributeMetaInfo'] == null) {
            throw new runtime.RequiredError(
                'attributeMetaInfo',
                'Required parameter "attributeMetaInfo" was null or undefined when calling createPrepaymentMetadataAttribute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/prepayment/metadata/attributes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AttributeMetaInfoToJSON(requestParameters['attributeMetaInfo']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttributeMetaInfoFromJSON(jsonValue));
    }

    /**
     * Создать доп. поле Предоплаты
     */
    async createPrepaymentMetadataAttribute(requestParameters: CreatePrepaymentMetadataAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AttributeMetaInfo> {
        const response = await this.createPrepaymentMetadataAttributeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreatePrepaymentMetadataAttributeAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type CreatePrepaymentMetadataAttributeAcceptEnum = typeof CreatePrepaymentMetadataAttributeAcceptEnum[keyof typeof CreatePrepaymentMetadataAttributeAcceptEnum];
/**
 * @export
 */
export const CreatePrepaymentMetadataAttributeContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type CreatePrepaymentMetadataAttributeContentTypeEnum = typeof CreatePrepaymentMetadataAttributeContentTypeEnum[keyof typeof CreatePrepaymentMetadataAttributeContentTypeEnum];
