/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  AttributeMetaInfo,
  AttributeMetaInfoList,
  Errors,
} from '../models/index.js';
import {
    AttributeMetaInfoFromJSON,
    AttributeMetaInfoToJSON,
    AttributeMetaInfoListFromJSON,
    AttributeMetaInfoListToJSON,
    ErrorsFromJSON,
    ErrorsToJSON,
} from '../models/index.js';

export interface CreateProductionTaskMetadataAttributeRequest {
    attributeMetaInfo: AttributeMetaInfo;
    accept?: CreateProductionTaskMetadataAttributeAcceptEnum;
    acceptEncoding?: string;
    contentType?: CreateProductionTaskMetadataAttributeContentTypeEnum;
}

export interface GetProductionTaskMetadataAttributeRequest {
    offset?: number;
    limit?: number;
    accept?: GetProductionTaskMetadataAttributeAcceptEnum;
    acceptEncoding?: string;
}

/**
 * 
 */
export class ProductionTasksApi extends runtime.BaseAPI {

    /**
     * Создать Доп. поле Производственных задач
     */
    async createProductionTaskMetadataAttributeRaw(requestParameters: CreateProductionTaskMetadataAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AttributeMetaInfo>> {
        if (requestParameters['attributeMetaInfo'] == null) {
            throw new runtime.RequiredError(
                'attributeMetaInfo',
                'Required parameter "attributeMetaInfo" was null or undefined when calling createProductionTaskMetadataAttribute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/productiontask/metadata/attributes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AttributeMetaInfoToJSON(requestParameters['attributeMetaInfo']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttributeMetaInfoFromJSON(jsonValue));
    }

    /**
     * Создать Доп. поле Производственных задач
     */
    async createProductionTaskMetadataAttribute(requestParameters: CreateProductionTaskMetadataAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AttributeMetaInfo> {
        const response = await this.createProductionTaskMetadataAttributeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Доп. поля ProductionTask
     */
    async getProductionTaskMetadataAttributeRaw(requestParameters: GetProductionTaskMetadataAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AttributeMetaInfoList>> {
        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['accept'] != null) {
            headerParameters['accept'] = String(requestParameters['accept']);
        }

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entity/productiontask/metadata/attributes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttributeMetaInfoListFromJSON(jsonValue));
    }

    /**
     * Доп. поля ProductionTask
     */
    async getProductionTaskMetadataAttribute(requestParameters: GetProductionTaskMetadataAttributeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AttributeMetaInfoList> {
        const response = await this.getProductionTaskMetadataAttributeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateProductionTaskMetadataAttributeAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type CreateProductionTaskMetadataAttributeAcceptEnum = typeof CreateProductionTaskMetadataAttributeAcceptEnum[keyof typeof CreateProductionTaskMetadataAttributeAcceptEnum];
/**
 * @export
 */
export const CreateProductionTaskMetadataAttributeContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type CreateProductionTaskMetadataAttributeContentTypeEnum = typeof CreateProductionTaskMetadataAttributeContentTypeEnum[keyof typeof CreateProductionTaskMetadataAttributeContentTypeEnum];
/**
 * @export
 */
export const GetProductionTaskMetadataAttributeAcceptEnum = {
    ApplicationJson: 'application/json',
    ApplicationJsoncharsetutf8: 'application/json;charset=utf-8'
} as const;
export type GetProductionTaskMetadataAttributeAcceptEnum = typeof GetProductionTaskMetadataAttributeAcceptEnum[keyof typeof GetProductionTaskMetadataAttributeAcceptEnum];
