/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';

/**
 * Решение
 * @export
 * @interface Application
 */
export interface Application {
    /**
     * 
     * @type {Meta}
     * @memberof Application
     */
    meta?: Meta;
    /**
     * ID решения
     * @type {string}
     * @memberof Application
     */
    readonly id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof Application
     */
    readonly accountId?: string;
    /**
     * Наименование решения
     * @type {string}
     * @memberof Application
     */
    readonly name?: string;
    /**
     * Логин решения
     * @type {string}
     * @memberof Application
     */
    readonly appUid?: string;
}


/**
 * Check if a given object implements the Application interface.
 */
export function instanceOfApplication(value: object): value is Application {
    return true;
}

export function ApplicationFromJSON(json: any): Application {
    return ApplicationFromJSONTyped(json, false);
}

export function ApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Application {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'appUid': json['appUid'] == null ? undefined : json['appUid'],
    };
}

export function ApplicationToJSON(json: any): Application {
    return ApplicationToJSONTyped(json, false);
}

export function ApplicationToJSONTyped(value?: Omit<Application, 'id'|'account_id'|'name'|'appUid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaToJSON(value['meta']),
    };
}

