/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { AssortmentSettingsUniqueCodeRules } from './AssortmentSettingsUniqueCodeRules.js';
import {
    AssortmentSettingsUniqueCodeRulesFromJSON,
    AssortmentSettingsUniqueCodeRulesFromJSONTyped,
    AssortmentSettingsUniqueCodeRulesToJSON,
    AssortmentSettingsUniqueCodeRulesToJSONTyped,
} from './AssortmentSettingsUniqueCodeRules.js';
import type { AssortmentSettingsBarcodeRules } from './AssortmentSettingsBarcodeRules.js';
import {
    AssortmentSettingsBarcodeRulesFromJSON,
    AssortmentSettingsBarcodeRulesFromJSONTyped,
    AssortmentSettingsBarcodeRulesToJSON,
    AssortmentSettingsBarcodeRulesToJSONTyped,
} from './AssortmentSettingsBarcodeRules.js';

/**
 * Настройки ассортимента
 * @export
 * @interface AssortmentSettings
 */
export interface AssortmentSettings {
    /**
     * 
     * @type {Meta}
     * @memberof AssortmentSettings
     */
    meta?: Meta;
    /**
     * 
     * @type {AssortmentSettingsBarcodeRules}
     * @memberof AssortmentSettings
     */
    barcodeRules?: AssortmentSettingsBarcodeRules;
    /**
     * 
     * @type {AssortmentSettingsUniqueCodeRules}
     * @memberof AssortmentSettings
     */
    uniqueCodeRules?: AssortmentSettingsUniqueCodeRules;
    /**
     * Создавать новые элементы с меткой "Общий"
     * @type {boolean}
     * @memberof AssortmentSettings
     */
    createdShared?: boolean;
}


/**
 * Check if a given object implements the AssortmentSettings interface.
 */
export function instanceOfAssortmentSettings(value: object): value is AssortmentSettings {
    return true;
}

export function AssortmentSettingsFromJSON(json: any): AssortmentSettings {
    return AssortmentSettingsFromJSONTyped(json, false);
}

export function AssortmentSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssortmentSettings {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'barcodeRules': json['barcodeRules'] == null ? undefined : AssortmentSettingsBarcodeRulesFromJSON(json['barcodeRules']),
        'uniqueCodeRules': json['uniqueCodeRules'] == null ? undefined : AssortmentSettingsUniqueCodeRulesFromJSON(json['uniqueCodeRules']),
        'createdShared': json['createdShared'] == null ? undefined : json['createdShared'],
    };
}

export function AssortmentSettingsToJSON(json: any): AssortmentSettings {
    return AssortmentSettingsToJSONTyped(json, false);
}

export function AssortmentSettingsToJSONTyped(value?: AssortmentSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaToJSON(value['meta']),
        'barcodeRules': AssortmentSettingsBarcodeRulesToJSON(value['barcodeRules']),
        'uniqueCodeRules': AssortmentSettingsUniqueCodeRulesToJSON(value['uniqueCodeRules']),
        'createdShared': value['createdShared'],
    };
}

