/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { AttributeAbstract } from './AttributeAbstract.js';
import {
    AttributeAbstractFromJSON,
    AttributeAbstractFromJSONTyped,
    AttributeAbstractToJSON,
    AttributeAbstractToJSONTyped,
} from './AttributeAbstract.js';

/**
 * 
 * @export
 * @interface AttributeFile
 */
export interface AttributeFile extends AttributeAbstract {
    /**
     * 
     * @type {string}
     * @memberof AttributeFile
     */
    type: AttributeFileTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AttributeFile
     */
    value?: string;
    /**
     * 
     * @type {object}
     * @memberof AttributeFile
     */
    download?: object;
}


/**
 * @export
 */
export const AttributeFileTypeEnum = {
    File: 'file'
} as const;
export type AttributeFileTypeEnum = typeof AttributeFileTypeEnum[keyof typeof AttributeFileTypeEnum];


/**
 * Check if a given object implements the AttributeFile interface.
 */
export function instanceOfAttributeFile(value: object): value is AttributeFile {
    return true;
}

export function AttributeFileFromJSON(json: any): AttributeFile {
    return AttributeFileFromJSONTyped(json, false);
}

export function AttributeFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeFile {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
    }
    return {
        ...AttributeAbstractFromJSONTyped(json, true),
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
        'download': json['download'] == null ? undefined : json['download'],
    };
}

export function AttributeFileToJSON(json: any): AttributeFile {
    return AttributeFileToJSONTyped(json, false);
}

export function AttributeFileToJSONTyped(value?: AttributeFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (!ignoreDiscriminator) {
        switch (value['type']) {
            default:
                return value;
        }
    }
    return {
        ...AttributeAbstractToJSONTyped(value, true),
        'type': value['type'],
        'value': value['value'],
        'download': value['download'],
    };
}

