/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';

import { type AttributeBool, AttributeBoolFromJSONTyped, AttributeBoolToJSON, AttributeBoolToJSONTyped } from './AttributeBool.js';
import { type AttributeContractEntity, AttributeContractEntityFromJSONTyped, AttributeContractEntityToJSON, AttributeContractEntityToJSONTyped } from './AttributeContractEntity.js';
import { type AttributeCounterpartyEntity, AttributeCounterpartyEntityFromJSONTyped, AttributeCounterpartyEntityToJSON, AttributeCounterpartyEntityToJSONTyped } from './AttributeCounterpartyEntity.js';
import { type AttributeCustomEntity, AttributeCustomEntityFromJSONTyped, AttributeCustomEntityToJSON, AttributeCustomEntityToJSONTyped } from './AttributeCustomEntity.js';
import { type AttributeDouble, AttributeDoubleFromJSONTyped, AttributeDoubleToJSON, AttributeDoubleToJSONTyped } from './AttributeDouble.js';
import { type AttributeEmployeeEntity, AttributeEmployeeEntityFromJSONTyped, AttributeEmployeeEntityToJSON, AttributeEmployeeEntityToJSONTyped } from './AttributeEmployeeEntity.js';
import { type AttributeFile, AttributeFileFromJSONTyped, AttributeFileToJSON, AttributeFileToJSONTyped } from './AttributeFile.js';
import { type AttributeLink, AttributeLinkFromJSONTyped, AttributeLinkToJSON, AttributeLinkToJSONTyped } from './AttributeLink.js';
import { type AttributeLong, AttributeLongFromJSONTyped, AttributeLongToJSON, AttributeLongToJSONTyped } from './AttributeLong.js';
import { type AttributeProductEntity, AttributeProductEntityFromJSONTyped, AttributeProductEntityToJSON, AttributeProductEntityToJSONTyped } from './AttributeProductEntity.js';
import { type AttributeProjectEntity, AttributeProjectEntityFromJSONTyped, AttributeProjectEntityToJSON, AttributeProjectEntityToJSONTyped } from './AttributeProjectEntity.js';
import { type AttributeStoreEntity, AttributeStoreEntityFromJSONTyped, AttributeStoreEntityToJSON, AttributeStoreEntityToJSONTyped } from './AttributeStoreEntity.js';
import { type AttributeString, AttributeStringFromJSONTyped, AttributeStringToJSON, AttributeStringToJSONTyped } from './AttributeString.js';
import { type AttributeText, AttributeTextFromJSONTyped, AttributeTextToJSON, AttributeTextToJSONTyped } from './AttributeText.js';
import { type AttributeDateTime, AttributeDateTimeFromJSONTyped, AttributeDateTimeToJSON, AttributeDateTimeToJSONTyped } from './AttributeDateTime.js';
/**
 * 
 * @export
 * @interface AttributeAbstract
 */
export interface AttributeAbstract {
    /**
     * ID дополнительного поля
     * @type {string}
     * @memberof AttributeAbstract
     */
    id?: string;
    /**
     * Наименование дополнительного поля
     * @type {string}
     * @memberof AttributeAbstract
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AttributeAbstract
     */
    type: string;
    /**
     * 
     * @type {Meta}
     * @memberof AttributeAbstract
     */
    meta?: Meta;
}


/**
 * Check if a given object implements the AttributeAbstract interface.
 */
export function instanceOfAttributeAbstract(value: object): value is AttributeAbstract {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AttributeAbstractFromJSON(json: any): AttributeAbstract {
    return AttributeAbstractFromJSONTyped(json, false);
}

export function AttributeAbstractFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeAbstract {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['type'] === 'boolean') {
            return AttributeBoolFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'contract') {
            return AttributeContractEntityFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'counterparty') {
            return AttributeCounterpartyEntityFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'customentity') {
            return AttributeCustomEntityFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'double') {
            return AttributeDoubleFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'employee') {
            return AttributeEmployeeEntityFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'file') {
            return AttributeFileFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'link') {
            return AttributeLinkFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'long') {
            return AttributeLongFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'product') {
            return AttributeProductEntityFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'project') {
            return AttributeProjectEntityFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'store') {
            return AttributeStoreEntityFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'string') {
            return AttributeStringFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'text') {
            return AttributeTextFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'time') {
            return AttributeDateTimeFromJSONTyped(json, ignoreDiscriminator);
        }
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'],
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
    };
}

export function AttributeAbstractToJSON(json: any): AttributeAbstract {
    return AttributeAbstractToJSONTyped(json, false);
}

export function AttributeAbstractToJSONTyped(value?: AttributeAbstract | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (!ignoreDiscriminator) {
        switch (value['type']) {
            case 'boolean':
                return AttributeBoolToJSONTyped(value as AttributeBool, ignoreDiscriminator);
            case 'contract':
                return AttributeContractEntityToJSONTyped(value as AttributeContractEntity, ignoreDiscriminator);
            case 'counterparty':
                return AttributeCounterpartyEntityToJSONTyped(value as AttributeCounterpartyEntity, ignoreDiscriminator);
            case 'customentity':
                return AttributeCustomEntityToJSONTyped(value as AttributeCustomEntity, ignoreDiscriminator);
            case 'double':
                return AttributeDoubleToJSONTyped(value as AttributeDouble, ignoreDiscriminator);
            case 'employee':
                return AttributeEmployeeEntityToJSONTyped(value as AttributeEmployeeEntity, ignoreDiscriminator);
            case 'file':
                return AttributeFileToJSONTyped(value as AttributeFile, ignoreDiscriminator);
            case 'link':
                return AttributeLinkToJSONTyped(value as AttributeLink, ignoreDiscriminator);
            case 'long':
                return AttributeLongToJSONTyped(value as AttributeLong, ignoreDiscriminator);
            case 'product':
                return AttributeProductEntityToJSONTyped(value as AttributeProductEntity, ignoreDiscriminator);
            case 'project':
                return AttributeProjectEntityToJSONTyped(value as AttributeProjectEntity, ignoreDiscriminator);
            case 'store':
                return AttributeStoreEntityToJSONTyped(value as AttributeStoreEntity, ignoreDiscriminator);
            case 'string':
                return AttributeStringToJSONTyped(value as AttributeString, ignoreDiscriminator);
            case 'text':
                return AttributeTextToJSONTyped(value as AttributeText, ignoreDiscriminator);
            case 'time':
                return AttributeDateTimeToJSONTyped(value as AttributeDateTime, ignoreDiscriminator);
            default:
                return value;
        }
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'meta': MetaToJSON(value['meta']),
    };
}

