/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Известные значения источника изменения в аудите
 * @export
 */
export const AuditSourceType = {
    Registration: 'registration',
    Clearrecyclebin: 'clearrecyclebin',
    Combine: 'combine',
    Bulkcreate: 'bulkcreate',
    Connectors: 'connectors',
    Copy: 'copy',
    Emailsend: 'emailsend',
    Evotor: 'evotor',
    Export: 'export',
    Exportediclient1c: 'exportediclient1c',
    Import: 'import',
    Import1c: 'import1c',
    ImportAlfabank: 'importAlfabank',
    ImportModulebank: 'importModulebank',
    ImportTinkoffbank: 'importTinkoffbank',
    ImportTochkabank: 'importTochkabank',
    Importediclient1c: 'importediclient1c',
    Loginlogout: 'loginlogout',
    Phone10: 'phone-1.0',
    Posapi: 'posapi',
    Remap10: 'remap-1.0',
    Remap11: 'remap-1.1',
    Remap12: 'remap-1.2',
    Remap13: 'remap-1.3',
    Restapi: 'restapi',
    Retail: 'retail',
    App: 'app',
    ImportSberbank: 'importSberbank',
    Jsonapi: 'jsonapi',
    Manufacture10: 'manufacture-1.0',
    Scriptor: 'scriptor',
    Exportyml: 'exportyml',
    Edoimportsupply: 'edoimportsupply',
    Taxcomimportsupply: 'taxcomimportsupply',
    Yandexkassawebhook: 'yandexkassawebhook',
    Fillreserves: 'fillreserves',
    Recyclebincleaner: 'recyclebincleaner',
    Dropgoodfolder: 'dropgoodfolder',
    Print: 'print'
} as const;
export type AuditSourceType = typeof AuditSourceType[keyof typeof AuditSourceType];


export function instanceOfAuditSourceType(value: any): boolean {
    for (const key in AuditSourceType) {
        if (Object.prototype.hasOwnProperty.call(AuditSourceType, key)) {
            if (AuditSourceType[key as keyof typeof AuditSourceType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AuditSourceTypeFromJSON(json: any): AuditSourceType {
    return AuditSourceTypeFromJSONTyped(json, false);
}

export function AuditSourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditSourceType {
    return json as AuditSourceType;
}

export function AuditSourceTypeToJSON(value?: AuditSourceType | null): any {
    return value as any;
}

export function AuditSourceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AuditSourceType {
    return value as AuditSourceType;
}

