/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Currency } from './Currency.js';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency.js';

/**
 * Дополнительные расходы
 * @export
 * @interface BundleOverhead
 */
export interface BundleOverhead {
    /**
     * Значение цены
     * @type {number}
     * @memberof BundleOverhead
     */
    value?: number;
    /**
     * 
     * @type {Currency}
     * @memberof BundleOverhead
     */
    currency?: Currency;
}


/**
 * Check if a given object implements the BundleOverhead interface.
 */
export function instanceOfBundleOverhead(value: object): value is BundleOverhead {
    return true;
}

export function BundleOverheadFromJSON(json: any): BundleOverhead {
    return BundleOverheadFromJSONTyped(json, false);
}

export function BundleOverheadFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleOverhead {
    if (json == null) {
        return json;
    }
    return {
        'value': json['value'] == null ? undefined : json['value'],
        'currency': json['currency'] == null ? undefined : CurrencyFromJSON(json['currency']),
    };
}

export function BundleOverheadToJSON(json: any): BundleOverhead {
    return BundleOverheadToJSONTyped(json, false);
}

export function BundleOverheadToJSONTyped(value?: BundleOverhead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'value': value['value'],
        'currency': CurrencyToJSON(value['currency']),
    };
}

