/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';

/**
 * Метаданные документа
 * @export
 * @interface ByOperationsStockOperation
 */
export interface ByOperationsStockOperation {
    /**
     * 
     * @type {Meta}
     * @memberof ByOperationsStockOperation
     */
    meta?: Meta;
}


/**
 * Check if a given object implements the ByOperationsStockOperation interface.
 */
export function instanceOfByOperationsStockOperation(value: object): value is ByOperationsStockOperation {
    return true;
}

export function ByOperationsStockOperationFromJSON(json: any): ByOperationsStockOperation {
    return ByOperationsStockOperationFromJSONTyped(json, false);
}

export function ByOperationsStockOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ByOperationsStockOperation {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
    };
}

export function ByOperationsStockOperationToJSON(json: any): ByOperationsStockOperation {
    return ByOperationsStockOperationToJSONTyped(json, false);
}

export function ByOperationsStockOperationToJSONTyped(value?: ByOperationsStockOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaToJSON(value['meta']),
    };
}

