/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';

/**
 * Метаданные склада документа
 * @export
 * @interface ByOperationsStockStore
 */
export interface ByOperationsStockStore {
    /**
     * 
     * @type {Meta}
     * @memberof ByOperationsStockStore
     */
    meta?: Meta;
}


/**
 * Check if a given object implements the ByOperationsStockStore interface.
 */
export function instanceOfByOperationsStockStore(value: object): value is ByOperationsStockStore {
    return true;
}

export function ByOperationsStockStoreFromJSON(json: any): ByOperationsStockStore {
    return ByOperationsStockStoreFromJSONTyped(json, false);
}

export function ByOperationsStockStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): ByOperationsStockStore {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
    };
}

export function ByOperationsStockStoreToJSON(json: any): ByOperationsStockStore {
    return ByOperationsStockStoreToJSONTyped(json, false);
}

export function ByOperationsStockStoreToJSONTyped(value?: ByOperationsStockStore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaToJSON(value['meta']),
    };
}

