/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Pack } from './Pack.js';
import {
    PackFromJSON,
    PackFromJSONTyped,
    PackToJSON,
    PackToJSONTyped,
} from './Pack.js';
import type { ProductMarker } from './ProductMarker.js';
import {
    ProductMarkerFromJSON,
    ProductMarkerFromJSONTyped,
    ProductMarkerToJSON,
    ProductMarkerToJSONTyped,
} from './ProductMarker.js';

import * as CommissionReportInPositionPolymorphicParent from './EntityWithMeta.js';
/**
 * Позиция реализовано комиссионером Полученного отчета комиссионера
 * @export
 * @interface CommissionReportInPosition
 */
export interface CommissionReportInPositionOwn {
    /**
     * 
     * @type {Meta}
     * @memberof CommissionReportInPosition
     */
    meta?: Meta;
    /**
     * ID позиции
     * @type {string}
     * @memberof CommissionReportInPosition
     */
    readonly id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof CommissionReportInPosition
     */
    readonly accountId?: string;
    /**
     * Количество товаров/услуг в позиции
     * @type {number}
     * @memberof CommissionReportInPosition
     */
    quantity?: number;
    /**
     * Цена товара в копейках
     * @type {number}
     * @memberof CommissionReportInPosition
     */
    price?: number;
    /**
     * Вознаграждение
     * @type {number}
     * @memberof CommissionReportInPosition
     */
    reward?: number;
    /**
     * НДС для позиции
     * @type {number}
     * @memberof CommissionReportInPosition
     */
    vat?: number;
    /**
     * Включен ли НДС для позиции
     * @type {boolean}
     * @memberof CommissionReportInPosition
     */
    vatEnabled?: boolean;
    /**
     * Метаданные товара/партии/модификации/комплекта, которую представляет позиция
     * @type {ProductMarker}
     * @memberof CommissionReportInPosition
     */
    assortment?: ProductMarker;
    /**
     * Упаковка Товара
     * @type {Pack}
     * @memberof CommissionReportInPosition
     */
    pack?: Pack | null;
}
export type CommissionReportInPosition = CommissionReportInPositionOwn & CommissionReportInPositionPolymorphicParent.EntityWithMeta;


/**
 * Check if a given object implements the CommissionReportInPosition interface.
 */
export function instanceOfCommissionReportInPosition(value: object): value is CommissionReportInPosition {
    return true;
}

export function CommissionReportInPositionFromJSON(json: any): CommissionReportInPosition {
    return CommissionReportInPositionFromJSONTyped(json, false);
}

export function CommissionReportInPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommissionReportInPosition {
    if (json == null) {
        return json;
    }
    return {
        ...CommissionReportInPositionPolymorphicParent.EntityWithMetaFromJSONTyped(json, true),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'price': json['price'] == null ? undefined : json['price'],
        'reward': json['reward'] == null ? undefined : json['reward'],
        'vat': json['vat'] == null ? undefined : json['vat'],
        'vatEnabled': json['vatEnabled'] == null ? undefined : json['vatEnabled'],
        'assortment': json['assortment'] == null ? undefined : ProductMarkerFromJSON(json['assortment']),
        'pack': json['pack'] == null ? undefined : PackFromJSON(json['pack']),
    };
}

export function CommissionReportInPositionToJSON(json: any): CommissionReportInPosition {
    return CommissionReportInPositionToJSONTyped(json, false);
}

export function CommissionReportInPositionToJSONTyped(value?: Omit<CommissionReportInPosition, 'id'|'accountId'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...CommissionReportInPositionPolymorphicParent.EntityWithMetaToJSONTyped(value as any, true),
        'meta': MetaToJSON(value['meta']),
        'quantity': value['quantity'],
        'price': value['price'],
        'reward': value['reward'],
        'vat': value['vat'],
        'vatEnabled': value['vatEnabled'],
        'assortment': ProductMarkerToJSON(value['assortment']),
        'pack': PackToJSON(value['pack']),
    };
}

