/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Прочие расходы
 * @export
 * @interface CommissionReportInCommissionOverhead
 */
export interface CommissionReportInCommissionOverhead {
    /**
     * Сумма НДС
     * @type {number}
     * @memberof CommissionReportInCommissionOverhead
     */
    sum?: number;
}


/**
 * Check if a given object implements the CommissionReportInCommissionOverhead interface.
 */
export function instanceOfCommissionReportInCommissionOverhead(value: object): value is CommissionReportInCommissionOverhead {
    return true;
}

export function CommissionReportInCommissionOverheadFromJSON(json: any): CommissionReportInCommissionOverhead {
    return CommissionReportInCommissionOverheadFromJSONTyped(json, false);
}

export function CommissionReportInCommissionOverheadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommissionReportInCommissionOverhead {
    if (json == null) {
        return json;
    }
    return {
        'sum': json['sum'] == null ? undefined : json['sum'],
    };
}

export function CommissionReportInCommissionOverheadToJSON(json: any): CommissionReportInCommissionOverhead {
    return CommissionReportInCommissionOverheadToJSONTyped(json, false);
}

export function CommissionReportInCommissionOverheadToJSONTyped(value?: CommissionReportInCommissionOverhead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'sum': value['sum'],
    };
}

