/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Известные значения типа контрагента
 * @export
 */
export const CompanyType = {
    Legal: 'legal',
    Entrepreneur: 'entrepreneur',
    Individual: 'individual'
} as const;
export type CompanyType = typeof CompanyType[keyof typeof CompanyType];


export function instanceOfCompanyType(value: any): boolean {
    for (const key in CompanyType) {
        if (Object.prototype.hasOwnProperty.call(CompanyType, key)) {
            if (CompanyType[key as keyof typeof CompanyType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CompanyTypeFromJSON(json: any): CompanyType {
    return CompanyTypeFromJSONTyped(json, false);
}

export function CompanyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyType {
    return json as CompanyType;
}

export function CompanyTypeToJSON(value?: CompanyType | null): any {
    return value as any;
}

export function CompanyTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CompanyType {
    return value as CompanyType;
}

