/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Известные значения типа договора
 * @export
 */
export const ContractType = {
    Commission: 'Commission',
    Sales: 'Sales'
} as const;
export type ContractType = typeof ContractType[keyof typeof ContractType];


export function instanceOfContractType(value: any): boolean {
    for (const key in ContractType) {
        if (Object.prototype.hasOwnProperty.call(ContractType, key)) {
            if (ContractType[key as keyof typeof ContractType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ContractTypeFromJSON(json: any): ContractType {
    return ContractTypeFromJSONTyped(json, false);
}

export function ContractTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractType {
    return json as ContractType;
}

export function ContractTypeToJSON(value?: ContractType | null): any {
    return value as any;
}

export function ContractTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ContractType {
    return value as ContractType;
}

