/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CounterpartyNotes } from './CounterpartyNotes.js';
import {
    CounterpartyNotesFromJSON,
    CounterpartyNotesFromJSONTyped,
    CounterpartyNotesToJSON,
    CounterpartyNotesToJSONTyped,
} from './CounterpartyNotes.js';
import type { Group } from './Group.js';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Address } from './Address.js';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address.js';
import type { FileList } from './FileList.js';
import {
    FileListFromJSON,
    FileListFromJSONTyped,
    FileListToJSON,
    FileListToJSONTyped,
} from './FileList.js';
import type { AttributeAbstract } from './AttributeAbstract.js';
import {
    AttributeAbstractFromJSON,
    AttributeAbstractFromJSONTyped,
    AttributeAbstractToJSON,
    AttributeAbstractToJSONTyped,
} from './AttributeAbstract.js';
import type { AgentDiscount } from './AgentDiscount.js';
import {
    AgentDiscountFromJSON,
    AgentDiscountFromJSONTyped,
    AgentDiscountToJSON,
    AgentDiscountToJSONTyped,
} from './AgentDiscount.js';
import type { Employee } from './Employee.js';
import {
    EmployeeFromJSON,
    EmployeeFromJSONTyped,
    EmployeeToJSON,
    EmployeeToJSONTyped,
} from './Employee.js';
import type { CounterpartyAccounts } from './CounterpartyAccounts.js';
import {
    CounterpartyAccountsFromJSON,
    CounterpartyAccountsFromJSONTyped,
    CounterpartyAccountsToJSON,
    CounterpartyAccountsToJSONTyped,
} from './CounterpartyAccounts.js';
import type { State } from './State.js';
import {
    StateFromJSON,
    StateFromJSONTyped,
    StateToJSON,
    StateToJSONTyped,
} from './State.js';
import type { CounterpartyContactpersons } from './CounterpartyContactpersons.js';
import {
    CounterpartyContactpersonsFromJSON,
    CounterpartyContactpersonsFromJSONTyped,
    CounterpartyContactpersonsToJSON,
    CounterpartyContactpersonsToJSONTyped,
} from './CounterpartyContactpersons.js';
import type { PriceType } from './PriceType.js';
import {
    PriceTypeFromJSON,
    PriceTypeFromJSONTyped,
    PriceTypeToJSON,
    PriceTypeToJSONTyped,
} from './PriceType.js';
import type { BonusProgram } from './BonusProgram.js';
import {
    BonusProgramFromJSON,
    BonusProgramFromJSONTyped,
    BonusProgramToJSON,
    BonusProgramToJSONTyped,
} from './BonusProgram.js';

import * as CounterpartyPolymorphicParent from './Agent.js';
/**
 * Контрагент
 * @export
 * @interface Counterparty
 */
export interface CounterpartyOwn {
    /**
     * 
     * @type {Meta}
     * @memberof Counterparty
     */
    meta?: Meta;
    /**
     * ID контрагента
     * @type {string}
     * @memberof Counterparty
     */
    id?: string;
    /**
     * ID синхронизации
     * @type {string}
     * @memberof Counterparty
     */
    syncId?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof Counterparty
     */
    readonly accountId?: string;
    /**
     * Наименование контрагента
     * @type {string}
     * @memberof Counterparty
     */
    name?: string;
    /**
     * Код контрагента
     * @type {string}
     * @memberof Counterparty
     */
    code?: string;
    /**
     * Внешний код контрагента
     * @type {string}
     * @memberof Counterparty
     */
    externalCode?: string;
    /**
     * Добавлен ли контрагент в архив
     * @type {boolean}
     * @memberof Counterparty
     */
    archived?: boolean;
    /**
     * Момент создания
     * @type {string}
     * @memberof Counterparty
     */
    readonly created?: string;
    /**
     * Момент последнего обновления
     * @type {string}
     * @memberof Counterparty
     */
    readonly updated?: string;
    /**
     * Комментарий к контрагенту
     * @type {string}
     * @memberof Counterparty
     */
    description?: string;
    /**
     * Тип контрагента. Известные значения описаны в CompanyType
     * @type {string}
     * @memberof Counterparty
     */
    companyType?: string;
    /**
     * Адрес электронной почты
     * @type {string}
     * @memberof Counterparty
     */
    email?: string;
    /**
     * Номер телефона
     * @type {string}
     * @memberof Counterparty
     */
    phone?: string;
    /**
     * Номер факса
     * @type {string}
     * @memberof Counterparty
     */
    fax?: string;
    /**
     * Фактический адрес контрагента
     * @type {string}
     * @memberof Counterparty
     */
    actualAddress?: string;
    /**
     * Полный адрес
     * @type {Address}
     * @memberof Counterparty
     */
    actualAddressFull?: Address | null;
    /**
     * Юридический адрес контрагента
     * @type {string}
     * @memberof Counterparty
     */
    legalAddress?: string;
    /**
     * Полный юридический адрес контрагента
     * @type {Address}
     * @memberof Counterparty
     */
    legalAddressFull?: Address | null;
    /**
     * ИНН
     * @type {string}
     * @memberof Counterparty
     */
    inn?: string;
    /**
     * КПП
     * @type {string}
     * @memberof Counterparty
     */
    kpp?: string;
    /**
     * ОГРН
     * @type {string}
     * @memberof Counterparty
     */
    ogrn?: string;
    /**
     * ОГРНИП
     * @type {string}
     * @memberof Counterparty
     */
    ogrnip?: string;
    /**
     * ОКПО
     * @type {string}
     * @memberof Counterparty
     */
    okpo?: string;
    /**
     * Номер свидетельства
     * @type {string}
     * @memberof Counterparty
     */
    certificateNumber?: string;
    /**
     * Дата свидетельства
     * @type {string}
     * @memberof Counterparty
     */
    certificateDate?: string;
    /**
     * Полное наименование
     * @type {string}
     * @memberof Counterparty
     */
    legalTitle?: string;
    /**
     * Имя для ИП и физлица
     * @type {string}
     * @memberof Counterparty
     */
    legalFirstName?: string;
    /**
     * Фамилия для ИП и физлица
     * @type {string}
     * @memberof Counterparty
     */
    legalLastName?: string;
    /**
     * Отчество для ИП и физлица
     * @type {string}
     * @memberof Counterparty
     */
    legalMiddleName?: string;
    /**
     * Дата рождения для физлица
     * @type {string}
     * @memberof Counterparty
     */
    birthDate?: string;
    /**
     * Пол контрагента. Известные значения описаны в Sex
     * @type {string}
     * @memberof Counterparty
     */
    sex?: string;
    /**
     * Номер дисконтной карты контрагента
     * @type {string}
     * @memberof Counterparty
     */
    discountCardNumber?: string;
    /**
     * Массив скидок контрагента
     * @type {Array<AgentDiscount>}
     * @memberof Counterparty
     */
    discounts?: Array<AgentDiscount> | null;
    /**
     * Общий доступ
     * @type {boolean}
     * @memberof Counterparty
     */
    shared?: boolean;
    /**
     * 
     * @type {Group}
     * @memberof Counterparty
     */
    group?: Group;
    /**
     * Метаданные владельца (Сотрудника)
     * @type {Employee}
     * @memberof Counterparty
     */
    owner?: Employee | null;
    /**
     * Сумма продаж
     * @type {number}
     * @memberof Counterparty
     */
    readonly salesAmount?: number;
    /**
     * Бонусные баллы по активной бонусной программе
     * @type {number}
     * @memberof Counterparty
     */
    readonly bonusPoints?: number;
    /**
     * 
     * @type {BonusProgram}
     * @memberof Counterparty
     */
    bonusProgram?: BonusProgram | null;
    /**
     * 
     * @type {PriceType}
     * @memberof Counterparty
     */
    priceType?: PriceType | null;
    /**
     * 
     * @type {State}
     * @memberof Counterparty
     */
    state?: State;
    /**
     * 
     * @type {CounterpartyAccounts}
     * @memberof Counterparty
     */
    accounts?: CounterpartyAccounts;
    /**
     * 
     * @type {CounterpartyContactpersons}
     * @memberof Counterparty
     */
    contactpersons?: CounterpartyContactpersons;
    /**
     * 
     * @type {CounterpartyNotes}
     * @memberof Counterparty
     */
    notes?: CounterpartyNotes;
    /**
     * 
     * @type {FileList}
     * @memberof Counterparty
     */
    files?: FileList;
    /**
     * Группы контрагента
     * @type {Array<string>}
     * @memberof Counterparty
     */
    tags?: Array<string> | null;
    /**
     * Дополнительные поля
     * @type {Array<AttributeAbstract>}
     * @memberof Counterparty
     */
    attributes?: Array<AttributeAbstract> | null;
}
export type Counterparty = CounterpartyOwn & CounterpartyPolymorphicParent.Agent;


/**
 * Check if a given object implements the Counterparty interface.
 */
export function instanceOfCounterparty(value: object): value is Counterparty {
    return true;
}

export function CounterpartyFromJSON(json: any): Counterparty {
    return CounterpartyFromJSONTyped(json, false);
}

export function CounterpartyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Counterparty {
    if (json == null) {
        return json;
    }
    return {
        ...CounterpartyPolymorphicParent.AgentFromJSONTyped(json, true),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'syncId': json['syncId'] == null ? undefined : json['syncId'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'externalCode': json['externalCode'] == null ? undefined : json['externalCode'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        'created': json['created'] == null ? undefined : json['created'],
        'updated': json['updated'] == null ? undefined : json['updated'],
        'description': json['description'] == null ? undefined : json['description'],
        'companyType': json['companyType'] == null ? undefined : json['companyType'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'fax': json['fax'] == null ? undefined : json['fax'],
        'actualAddress': json['actualAddress'] == null ? undefined : json['actualAddress'],
        'actualAddressFull': json['actualAddressFull'] == null ? undefined : AddressFromJSON(json['actualAddressFull']),
        'legalAddress': json['legalAddress'] == null ? undefined : json['legalAddress'],
        'legalAddressFull': json['legalAddressFull'] == null ? undefined : AddressFromJSON(json['legalAddressFull']),
        'inn': json['inn'] == null ? undefined : json['inn'],
        'kpp': json['kpp'] == null ? undefined : json['kpp'],
        'ogrn': json['ogrn'] == null ? undefined : json['ogrn'],
        'ogrnip': json['ogrnip'] == null ? undefined : json['ogrnip'],
        'okpo': json['okpo'] == null ? undefined : json['okpo'],
        'certificateNumber': json['certificateNumber'] == null ? undefined : json['certificateNumber'],
        'certificateDate': json['certificateDate'] == null ? undefined : json['certificateDate'],
        'legalTitle': json['legalTitle'] == null ? undefined : json['legalTitle'],
        'legalFirstName': json['legalFirstName'] == null ? undefined : json['legalFirstName'],
        'legalLastName': json['legalLastName'] == null ? undefined : json['legalLastName'],
        'legalMiddleName': json['legalMiddleName'] == null ? undefined : json['legalMiddleName'],
        'birthDate': json['birthDate'] == null ? undefined : json['birthDate'],
        'sex': json['sex'] == null ? undefined : json['sex'],
        'discountCardNumber': json['discountCardNumber'] == null ? undefined : json['discountCardNumber'],
        'discounts': json['discounts'] == null ? undefined : ((json['discounts'] as Array<any>).map(AgentDiscountFromJSON)),
        'shared': json['shared'] == null ? undefined : json['shared'],
        'group': json['group'] == null ? undefined : GroupFromJSON(json['group']),
        'owner': json['owner'] == null ? undefined : EmployeeFromJSON(json['owner']),
        'salesAmount': json['salesAmount'] == null ? undefined : json['salesAmount'],
        'bonusPoints': json['bonusPoints'] == null ? undefined : json['bonusPoints'],
        'bonusProgram': json['bonusProgram'] == null ? undefined : BonusProgramFromJSON(json['bonusProgram']),
        'priceType': json['priceType'] == null ? undefined : PriceTypeFromJSON(json['priceType']),
        'state': json['state'] == null ? undefined : StateFromJSON(json['state']),
        'accounts': json['accounts'] == null ? undefined : CounterpartyAccountsFromJSON(json['accounts']),
        'contactpersons': json['contactpersons'] == null ? undefined : CounterpartyContactpersonsFromJSON(json['contactpersons']),
        'notes': json['notes'] == null ? undefined : CounterpartyNotesFromJSON(json['notes']),
        'files': json['files'] == null ? undefined : FileListFromJSON(json['files']),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(AttributeAbstractFromJSON)),
    };
}

export function CounterpartyToJSON(json: any): Counterparty {
    return CounterpartyToJSONTyped(json, false);
}

export function CounterpartyToJSONTyped(value?: Omit<Counterparty, 'accountId'|'created'|'updated'|'salesAmount'|'bonusPoints'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...CounterpartyPolymorphicParent.AgentToJSONTyped(value as any, true),
        'meta': MetaToJSON(value['meta']),
        'id': value['id'],
        'syncId': value['syncId'],
        'name': value['name'],
        'code': value['code'],
        'externalCode': value['externalCode'],
        'archived': value['archived'],
        'description': value['description'],
        'companyType': value['companyType'],
        'email': value['email'],
        'phone': value['phone'],
        'fax': value['fax'],
        'actualAddress': value['actualAddress'],
        'actualAddressFull': AddressToJSON(value['actualAddressFull']),
        'legalAddress': value['legalAddress'],
        'legalAddressFull': AddressToJSON(value['legalAddressFull']),
        'inn': value['inn'],
        'kpp': value['kpp'],
        'ogrn': value['ogrn'],
        'ogrnip': value['ogrnip'],
        'okpo': value['okpo'],
        'certificateNumber': value['certificateNumber'],
        'certificateDate': value['certificateDate'],
        'legalTitle': value['legalTitle'],
        'legalFirstName': value['legalFirstName'],
        'legalLastName': value['legalLastName'],
        'legalMiddleName': value['legalMiddleName'],
        'birthDate': value['birthDate'],
        'sex': value['sex'],
        'discountCardNumber': value['discountCardNumber'],
        'discounts': value['discounts'] == null ? undefined : ((value['discounts'] as Array<any>).map(AgentDiscountToJSON)),
        'shared': value['shared'],
        'group': GroupToJSON(value['group']),
        'owner': EmployeeToJSON(value['owner']),
        'bonusProgram': BonusProgramToJSON(value['bonusProgram']),
        'priceType': PriceTypeToJSON(value['priceType']),
        'state': StateToJSON(value['state']),
        'accounts': CounterpartyAccountsToJSON(value['accounts']),
        'contactpersons': CounterpartyContactpersonsToJSON(value['contactpersons']),
        'notes': CounterpartyNotesToJSON(value['notes']),
        'files': FileListToJSON(value['files']),
        'tags': value['tags'],
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(AttributeAbstractToJSON)),
    };
}

