/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ModelError } from './ModelError.js';
import {
    instanceOfModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError.js';
import type { RetailShift } from './RetailShift.js';
import {
    instanceOfRetailShift,
    RetailShiftFromJSON,
    RetailShiftFromJSONTyped,
    RetailShiftToJSON,
} from './RetailShift.js';

/**
 * @type CreateRetailShiftBatch200ResponseInner
 * 
 * @export
 */
export type CreateRetailShiftBatch200ResponseInner = ModelError | RetailShift;

export function CreateRetailShiftBatch200ResponseInnerFromJSON(json: any): CreateRetailShiftBatch200ResponseInner {
    return CreateRetailShiftBatch200ResponseInnerFromJSONTyped(json, false);
}

export function CreateRetailShiftBatch200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRetailShiftBatch200ResponseInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfModelError(json)) {
        return ModelErrorFromJSONTyped(json, true);
    }
    if (instanceOfRetailShift(json)) {
        return RetailShiftFromJSONTyped(json, true);
    }

    return {} as any;
}

export function CreateRetailShiftBatch200ResponseInnerToJSON(json: any): any {
    return CreateRetailShiftBatch200ResponseInnerToJSONTyped(json, false);
}

export function CreateRetailShiftBatch200ResponseInnerToJSONTyped(value?: CreateRetailShiftBatch200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfModelError(value)) {
        return ModelErrorToJSON(value as ModelError);
    }
    if (instanceOfRetailShift(value)) {
        return RetailShiftToJSON(value as RetailShift);
    }

    return {};
}

