/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StoreZone } from './StoreZone.js';
import {
    instanceOfStoreZone,
    StoreZoneFromJSON,
    StoreZoneFromJSONTyped,
    StoreZoneToJSON,
} from './StoreZone.js';

/**
 * @type CreateStoreZonesRequest
 * 
 * @export
 */
export type CreateStoreZonesRequest = Array<StoreZone> | StoreZone;

export function CreateStoreZonesRequestFromJSON(json: any): CreateStoreZonesRequest {
    return CreateStoreZonesRequestFromJSONTyped(json, false);
}

export function CreateStoreZonesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStoreZonesRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfStoreZone(json)) {
        return StoreZoneFromJSONTyped(json, true);
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'object')) {
            if (json.every(item => instanceOfStoreZone(item))) {
                return json.map(value => StoreZoneFromJSONTyped(value, true));
            }
        }
        return json;
    }

    return {} as any;
}

export function CreateStoreZonesRequestToJSON(json: any): any {
    return CreateStoreZonesRequestToJSONTyped(json, false);
}

export function CreateStoreZonesRequestToJSONTyped(value?: CreateStoreZonesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfStoreZone(value)) {
        return StoreZoneToJSON(value as StoreZone);
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'object')) {
            if (value.every(item => instanceOfStoreZone(item))) {
                return value.map(value => StoreZoneToJSON(value as StoreZone));
            }
        }
        return value;
    }

    return {};
}

