/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ModelError } from './ModelError.js';
import {
    instanceOfModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError.js';
import type { RetailSalesReturnPosition } from './RetailSalesReturnPosition.js';
import {
    instanceOfRetailSalesReturnPosition,
    RetailSalesReturnPositionFromJSON,
    RetailSalesReturnPositionFromJSONTyped,
    RetailSalesReturnPositionToJSON,
} from './RetailSalesReturnPosition.js';

/**
 * @type CreateRetailSalesReturnPositions200ResponseInner
 * 
 * @export
 */
export type CreateRetailSalesReturnPositions200ResponseInner = ModelError | RetailSalesReturnPosition;

export function CreateRetailSalesReturnPositions200ResponseInnerFromJSON(json: any): CreateRetailSalesReturnPositions200ResponseInner {
    return CreateRetailSalesReturnPositions200ResponseInnerFromJSONTyped(json, false);
}

export function CreateRetailSalesReturnPositions200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRetailSalesReturnPositions200ResponseInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfModelError(json)) {
        return ModelErrorFromJSONTyped(json, true);
    }
    if (instanceOfRetailSalesReturnPosition(json)) {
        return RetailSalesReturnPositionFromJSONTyped(json, true);
    }

    return {} as any;
}

export function CreateRetailSalesReturnPositions200ResponseInnerToJSON(json: any): any {
    return CreateRetailSalesReturnPositions200ResponseInnerToJSONTyped(json, false);
}

export function CreateRetailSalesReturnPositions200ResponseInnerToJSONTyped(value?: CreateRetailSalesReturnPositions200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfModelError(value)) {
        return ModelErrorToJSON(value as ModelError);
    }
    if (instanceOfRetailSalesReturnPosition(value)) {
        return RetailSalesReturnPositionToJSON(value as RetailSalesReturnPosition);
    }

    return {};
}

