/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { State } from './State.js';
import {
    instanceOfState,
    StateFromJSON,
    StateFromJSONTyped,
    StateToJSON,
} from './State.js';

/**
 * @type CreateRetailDemandMetadataStateRequest
 * 
 * @export
 */
export type CreateRetailDemandMetadataStateRequest = Array<State> | State;

export function CreateRetailDemandMetadataStateRequestFromJSON(json: any): CreateRetailDemandMetadataStateRequest {
    return CreateRetailDemandMetadataStateRequestFromJSONTyped(json, false);
}

export function CreateRetailDemandMetadataStateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRetailDemandMetadataStateRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfState(json)) {
        return StateFromJSONTyped(json, true);
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'object')) {
            if (json.every(item => instanceOfState(item))) {
                return json.map(value => StateFromJSONTyped(value, true));
            }
        }
        return json;
    }

    return {} as any;
}

export function CreateRetailDemandMetadataStateRequestToJSON(json: any): any {
    return CreateRetailDemandMetadataStateRequestToJSONTyped(json, false);
}

export function CreateRetailDemandMetadataStateRequestToJSONTyped(value?: CreateRetailDemandMetadataStateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfState(value)) {
        return StateToJSON(value as State);
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'object')) {
            if (value.every(item => instanceOfState(item))) {
                return value.map(value => StateToJSON(value as State));
            }
        }
        return value;
    }

    return {};
}

