/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ModelError } from './ModelError.js';
import {
    instanceOfModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError.js';
import type { RetailSalesReturn } from './RetailSalesReturn.js';
import {
    instanceOfRetailSalesReturn,
    RetailSalesReturnFromJSON,
    RetailSalesReturnFromJSONTyped,
    RetailSalesReturnToJSON,
} from './RetailSalesReturn.js';

/**
 * @type CreateRetailSalesReturnsBatch200ResponseInner
 * 
 * @export
 */
export type CreateRetailSalesReturnsBatch200ResponseInner = ModelError | RetailSalesReturn;

export function CreateRetailSalesReturnsBatch200ResponseInnerFromJSON(json: any): CreateRetailSalesReturnsBatch200ResponseInner {
    return CreateRetailSalesReturnsBatch200ResponseInnerFromJSONTyped(json, false);
}

export function CreateRetailSalesReturnsBatch200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRetailSalesReturnsBatch200ResponseInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfModelError(json)) {
        return ModelErrorFromJSONTyped(json, true);
    }
    if (instanceOfRetailSalesReturn(json)) {
        return RetailSalesReturnFromJSONTyped(json, true);
    }

    return {} as any;
}

export function CreateRetailSalesReturnsBatch200ResponseInnerToJSON(json: any): any {
    return CreateRetailSalesReturnsBatch200ResponseInnerToJSONTyped(json, false);
}

export function CreateRetailSalesReturnsBatch200ResponseInnerToJSONTyped(value?: CreateRetailSalesReturnsBatch200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfModelError(value)) {
        return ModelErrorToJSON(value as ModelError);
    }
    if (instanceOfRetailSalesReturn(value)) {
        return RetailSalesReturnToJSON(value as RetailSalesReturn);
    }

    return {};
}

