/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Context } from './Context.js';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context.js';
import type { Currency } from './Currency.js';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency.js';
import type { MetaList } from './MetaList.js';
import {
    MetaListFromJSON,
    MetaListFromJSONTyped,
    MetaListToJSON,
    MetaListToJSONTyped,
} from './MetaList.js';

/**
 * Список валют
 * @export
 * @interface CurrencyList
 */
export interface CurrencyList {
    /**
     * 
     * @type {Context}
     * @memberof CurrencyList
     */
    context?: Context;
    /**
     * 
     * @type {MetaList}
     * @memberof CurrencyList
     */
    meta?: MetaList;
    /**
     * Массив валют
     * @type {Array<Currency>}
     * @memberof CurrencyList
     */
    rows?: Array<Currency>;
}


/**
 * Check if a given object implements the CurrencyList interface.
 */
export function instanceOfCurrencyList(value: object): value is CurrencyList {
    return true;
}

export function CurrencyListFromJSON(json: any): CurrencyList {
    return CurrencyListFromJSONTyped(json, false);
}

export function CurrencyListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyList {
    if (json == null) {
        return json;
    }
    return {
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
        'meta': json['meta'] == null ? undefined : MetaListFromJSON(json['meta']),
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(CurrencyFromJSON)),
    };
}

export function CurrencyListToJSON(json: any): CurrencyList {
    return CurrencyListToJSONTyped(json, false);
}

export function CurrencyListToJSONTyped(value?: CurrencyList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'context': ContextToJSON(value['context']),
        'meta': MetaListToJSON(value['meta']),
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(CurrencyToJSON)),
    };
}

