/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Context } from './Context.js';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context.js';
import type { CustomerOrder } from './CustomerOrder.js';
import {
    CustomerOrderFromJSON,
    CustomerOrderFromJSONTyped,
    CustomerOrderToJSON,
    CustomerOrderToJSONTyped,
} from './CustomerOrder.js';
import type { MetaList } from './MetaList.js';
import {
    MetaListFromJSON,
    MetaListFromJSONTyped,
    MetaListToJSON,
    MetaListToJSONTyped,
} from './MetaList.js';

/**
 * Список Заказов покупателей
 * @export
 * @interface CustomerOrderList
 */
export interface CustomerOrderList {
    /**
     * 
     * @type {Context}
     * @memberof CustomerOrderList
     */
    context?: Context;
    /**
     * 
     * @type {MetaList}
     * @memberof CustomerOrderList
     */
    meta?: MetaList;
    /**
     * Массив Заказов покупателей
     * @type {Array<CustomerOrder>}
     * @memberof CustomerOrderList
     */
    rows?: Array<CustomerOrder>;
}


/**
 * Check if a given object implements the CustomerOrderList interface.
 */
export function instanceOfCustomerOrderList(value: object): value is CustomerOrderList {
    return true;
}

export function CustomerOrderListFromJSON(json: any): CustomerOrderList {
    return CustomerOrderListFromJSONTyped(json, false);
}

export function CustomerOrderListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerOrderList {
    if (json == null) {
        return json;
    }
    return {
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
        'meta': json['meta'] == null ? undefined : MetaListFromJSON(json['meta']),
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(CustomerOrderFromJSON)),
    };
}

export function CustomerOrderListToJSON(json: any): CustomerOrderList {
    return CustomerOrderListToJSONTyped(json, false);
}

export function CustomerOrderListToJSONTyped(value?: CustomerOrderList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'context': ContextToJSON(value['context']),
        'meta': MetaListToJSON(value['meta']),
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(CustomerOrderToJSON)),
    };
}

