/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Country } from './Country.js';
import {
    CountryFromJSON,
    CountryFromJSONTyped,
    CountryToJSON,
    CountryToJSONTyped,
} from './Country.js';

/**
 * Запись о прослеживаемости импортных товаров
 * @export
 * @interface DeclarationInner
 */
export interface DeclarationInner {
    /**
     * Грузовая таможенная декларация
     * @type {string}
     * @memberof DeclarationInner
     */
    readonly gtd?: string;
    /**
     * Регистрационный номер партии товара (прослеживаемый товар)
     * @type {string}
     * @memberof DeclarationInner
     */
    readonly rnpt?: string;
    /**
     * Страна происхождения товара
     * @type {Country}
     * @memberof DeclarationInner
     */
    readonly country?: Country;
    /**
     * Количество товара с указанными ГТД или РНПТ в позиции документа
     * @type {number}
     * @memberof DeclarationInner
     */
    readonly quantity?: number;
}


/**
 * Check if a given object implements the DeclarationInner interface.
 */
export function instanceOfDeclarationInner(value: object): value is DeclarationInner {
    return true;
}

export function DeclarationInnerFromJSON(json: any): DeclarationInner {
    return DeclarationInnerFromJSONTyped(json, false);
}

export function DeclarationInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeclarationInner {
    if (json == null) {
        return json;
    }
    return {
        'gtd': json['gtd'] == null ? undefined : json['gtd'],
        'rnpt': json['rnpt'] == null ? undefined : json['rnpt'],
        'country': json['country'] == null ? undefined : CountryFromJSON(json['country']),
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function DeclarationInnerToJSON(json: any): DeclarationInner {
    return DeclarationInnerToJSONTyped(json, false);
}

export function DeclarationInnerToJSONTyped(value?: Omit<DeclarationInner, 'gtd'|'rnpt'|'country'|'quantity'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
    };
}

