/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Результат удаления сущности
 * @export
 * @interface DeleteInfo
 */
export interface DeleteInfo {
    /**
     * Информационное сообщение об удалении сущности
     * @type {string}
     * @memberof DeleteInfo
     */
    info?: string;
}


/**
 * Check if a given object implements the DeleteInfo interface.
 */
export function instanceOfDeleteInfo(value: object): value is DeleteInfo {
    return true;
}

export function DeleteInfoFromJSON(json: any): DeleteInfo {
    return DeleteInfoFromJSONTyped(json, false);
}

export function DeleteInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteInfo {
    if (json == null) {
        return json;
    }
    return {
        'info': json['info'] == null ? undefined : json['info'],
    };
}

export function DeleteInfoToJSON(json: any): DeleteInfo {
    return DeleteInfoToJSONTyped(json, false);
}

export function DeleteInfoToJSONTyped(value?: DeleteInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'info': value['info'],
    };
}

