/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Известные значения стратегии совместного применения скидок
 * @export
 */
export const DiscountStrategy = {
    BySum: 'bySum',
    ByPriority: 'byPriority'
} as const;
export type DiscountStrategy = typeof DiscountStrategy[keyof typeof DiscountStrategy];


export function instanceOfDiscountStrategy(value: any): boolean {
    for (const key in DiscountStrategy) {
        if (Object.prototype.hasOwnProperty.call(DiscountStrategy, key)) {
            if (DiscountStrategy[key as keyof typeof DiscountStrategy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DiscountStrategyFromJSON(json: any): DiscountStrategy {
    return DiscountStrategyFromJSONTyped(json, false);
}

export function DiscountStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscountStrategy {
    return json as DiscountStrategy;
}

export function DiscountStrategyToJSON(value?: DiscountStrategy | null): any {
    return value as any;
}

export function DiscountStrategyToJSONTyped(value: any, ignoreDiscriminator: boolean): DiscountStrategy {
    return value as DiscountStrategy;
}

