/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { StoreSlot } from './StoreSlot.js';
import {
    StoreSlotFromJSON,
    StoreSlotFromJSONTyped,
    StoreSlotToJSON,
    StoreSlotToJSONTyped,
} from './StoreSlot.js';
import type { Gtd } from './Gtd.js';
import {
    GtdFromJSON,
    GtdFromJSONTyped,
    GtdToJSON,
    GtdToJSONTyped,
} from './Gtd.js';
import type { Country } from './Country.js';
import {
    CountryFromJSON,
    CountryFromJSONTyped,
    CountryToJSON,
    CountryToJSONTyped,
} from './Country.js';
import type { Pack } from './Pack.js';
import {
    PackFromJSON,
    PackFromJSONTyped,
    PackToJSON,
    PackToJSONTyped,
} from './Pack.js';
import type { ProductMarker } from './ProductMarker.js';
import {
    ProductMarkerFromJSON,
    ProductMarkerFromJSONTyped,
    ProductMarkerToJSON,
    ProductMarkerToJSONTyped,
} from './ProductMarker.js';

import * as EnterPositionPolymorphicParent from './EntityWithMeta.js';
/**
 * Позиция Оприходования
 * @export
 * @interface EnterPosition
 */
export interface EnterPositionOwn {
    /**
     * 
     * @type {Meta}
     * @memberof EnterPosition
     */
    meta?: Meta;
    /**
     * ID позиции
     * @type {string}
     * @memberof EnterPosition
     */
    id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof EnterPosition
     */
    readonly accountId?: string;
    /**
     * Метаданные товара/услуги/партии/модификации, которую представляет собой позиция
     * @type {ProductMarker}
     * @memberof EnterPosition
     */
    assortment?: ProductMarker;
    /**
     * Метаданные страны
     * @type {Country}
     * @memberof EnterPosition
     */
    country?: Country | null;
    /**
     * 
     * @type {Gtd}
     * @memberof EnterPosition
     */
    gtd?: Gtd | null;
    /**
     * Накладные расходы
     * @type {number}
     * @memberof EnterPosition
     */
    readonly overhead?: number;
    /**
     * Упаковка Товара
     * @type {Pack}
     * @memberof EnterPosition
     */
    pack?: Pack | null;
    /**
     * Цена товара/услуги в копейках
     * @type {number}
     * @memberof EnterPosition
     */
    price?: number;
    /**
     * Количество товаров данного вида в позиции
     * @type {number}
     * @memberof EnterPosition
     */
    quantity?: number;
    /**
     * Причина оприходования данной позиции
     * @type {string}
     * @memberof EnterPosition
     */
    reason?: string | null;
    /**
     * Ячейка на складе
     * @type {StoreSlot}
     * @memberof EnterPosition
     */
    slot?: StoreSlot | null;
    /**
     * Серийные номера. Игнорируется, если товар позиции не на серийном учёте;
     * иначе количество единиц в позиции совпадает с числом переданных серийных номеров.
     * 
     * @type {Array<string>}
     * @memberof EnterPosition
     */
    things?: Array<string>;
}
export type EnterPosition = EnterPositionOwn & EnterPositionPolymorphicParent.EntityWithMeta;


/**
 * Check if a given object implements the EnterPosition interface.
 */
export function instanceOfEnterPosition(value: object): value is EnterPosition {
    return true;
}

export function EnterPositionFromJSON(json: any): EnterPosition {
    return EnterPositionFromJSONTyped(json, false);
}

export function EnterPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnterPosition {
    if (json == null) {
        return json;
    }
    return {
        ...EnterPositionPolymorphicParent.EntityWithMetaFromJSONTyped(json, true),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'assortment': json['assortment'] == null ? undefined : ProductMarkerFromJSON(json['assortment']),
        'country': json['country'] == null ? undefined : CountryFromJSON(json['country']),
        'gtd': json['gtd'] == null ? undefined : GtdFromJSON(json['gtd']),
        'overhead': json['overhead'] == null ? undefined : json['overhead'],
        'pack': json['pack'] == null ? undefined : PackFromJSON(json['pack']),
        'price': json['price'] == null ? undefined : json['price'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'slot': json['slot'] == null ? undefined : StoreSlotFromJSON(json['slot']),
        'things': json['things'] == null ? undefined : json['things'],
    };
}

export function EnterPositionToJSON(json: any): EnterPosition {
    return EnterPositionToJSONTyped(json, false);
}

export function EnterPositionToJSONTyped(value?: Omit<EnterPosition, 'accountId'|'overhead'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...EnterPositionPolymorphicParent.EntityWithMetaToJSONTyped(value as any, true),
        'meta': MetaToJSON(value['meta']),
        'id': value['id'],
        'assortment': ProductMarkerToJSON(value['assortment']),
        'country': CountryToJSON(value['country']),
        'gtd': GtdToJSON(value['gtd']),
        'pack': PackToJSON(value['pack']),
        'price': value['price'],
        'quantity': value['quantity'],
        'reason': value['reason'],
        'slot': StoreSlotToJSON(value['slot']),
        'things': value['things'],
    };
}

