/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import * as FinanceInOperationAbstractPolymorphicFinanceInOperationCustomerOrder from './FinanceInOperationCustomerOrder.js';
import * as FinanceInOperationAbstractPolymorphicFinanceInOperationPurchaseReturn from './FinanceInOperationPurchaseReturn.js';
import * as FinanceInOperationAbstractPolymorphicFinanceInOperationDemand from './FinanceInOperationDemand.js';
import * as FinanceInOperationAbstractPolymorphicFinanceInOperationInvoiceOut from './FinanceInOperationInvoiceOut.js';
import * as FinanceInOperationAbstractPolymorphicFinanceInOperationCommissionReportIn from './FinanceInOperationCommissionReportIn.js';
import * as FinanceInOperationAbstractPolymorphicFinanceInOperationRetailShift from './FinanceInOperationRetailShift.js';
/**
 * Элемент массива `operations` приходного ордера / входящего платежа.
 * 
 * Допустимые `meta.type`: customerorder, purchasereturn, demand, invoiceout,
 * commissionreportin, retailshift.
 * 
 * @export
 * @interface FinanceInOperationAbstract
 */
export interface FinanceInOperationAbstract {
    /**
     * Сумма, оплаченная по данному документу
     * @type {number}
     * @memberof FinanceInOperationAbstract
     */
    linkedSum: number;
}


function readFinanceInOperationAbstractPolymorphicDiscriminator(value: any): unknown {
    const path = 'meta.type'.replace(/^\//, '').replace(/\//g, '.');
    return path.split('.').filter(Boolean).reduce(
        (current: any, segment: string) => current == null ? undefined : current[segment],
        value,
    );
}

function isFinanceInOperationAbstractPolymorphicBatchError(value: any): boolean {
    return Array.isArray(value?.errors)
        && value.errors.length > 0
        && typeof value.errors[0]?.error === 'string';
}

/**
 * Check if a given object implements the FinanceInOperationAbstract interface.
 */
export function instanceOfFinanceInOperationAbstract(value: object): value is FinanceInOperationAbstract {
    if (!('linkedSum' in value) || value['linkedSum'] === undefined) return false;
    return true;
}

export function FinanceInOperationAbstractFromJSON(json: any): FinanceInOperationAbstract {
    return FinanceInOperationAbstractFromJSONTyped(json, false);
}

export function FinanceInOperationAbstractFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinanceInOperationAbstract {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        const discriminator = readFinanceInOperationAbstractPolymorphicDiscriminator(json);
        const converters: Record<string, (value: any) => any> = {
            'customerorder': FinanceInOperationAbstractPolymorphicFinanceInOperationCustomerOrder.FinanceInOperationCustomerOrderFromJSON,
            'purchasereturn': FinanceInOperationAbstractPolymorphicFinanceInOperationPurchaseReturn.FinanceInOperationPurchaseReturnFromJSON,
            'demand': FinanceInOperationAbstractPolymorphicFinanceInOperationDemand.FinanceInOperationDemandFromJSON,
            'invoiceout': FinanceInOperationAbstractPolymorphicFinanceInOperationInvoiceOut.FinanceInOperationInvoiceOutFromJSON,
            'commissionreportin': FinanceInOperationAbstractPolymorphicFinanceInOperationCommissionReportIn.FinanceInOperationCommissionReportInFromJSON,
            'retailshift': FinanceInOperationAbstractPolymorphicFinanceInOperationRetailShift.FinanceInOperationRetailShiftFromJSON,
        };
        const converter = typeof discriminator === 'string'
            ? converters[discriminator] ?? converters['undefined']
            : undefined;
        if (converter !== undefined) {
            return converter(json);
        }
    }
    return {
        'linkedSum': json['linkedSum'],
    };
}

export function FinanceInOperationAbstractToJSON(json: any): FinanceInOperationAbstract {
    return FinanceInOperationAbstractToJSONTyped(json, false);
}

export function FinanceInOperationAbstractToJSONTyped(value?: FinanceInOperationAbstract | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (!ignoreDiscriminator) {
        const discriminator = readFinanceInOperationAbstractPolymorphicDiscriminator(value);
        const converters: Record<string, (item: any) => any> = {
            'customerorder': FinanceInOperationAbstractPolymorphicFinanceInOperationCustomerOrder.FinanceInOperationCustomerOrderToJSON,
            'purchasereturn': FinanceInOperationAbstractPolymorphicFinanceInOperationPurchaseReturn.FinanceInOperationPurchaseReturnToJSON,
            'demand': FinanceInOperationAbstractPolymorphicFinanceInOperationDemand.FinanceInOperationDemandToJSON,
            'invoiceout': FinanceInOperationAbstractPolymorphicFinanceInOperationInvoiceOut.FinanceInOperationInvoiceOutToJSON,
            'commissionreportin': FinanceInOperationAbstractPolymorphicFinanceInOperationCommissionReportIn.FinanceInOperationCommissionReportInToJSON,
            'retailshift': FinanceInOperationAbstractPolymorphicFinanceInOperationRetailShift.FinanceInOperationRetailShiftToJSON,
        };
        const converter = typeof discriminator === 'string'
            ? converters[discriminator] ?? converters['undefined']
            : undefined;
        if (converter !== undefined) {
            return converter(value);
        }
    }
    return {
        'linkedSum': value['linkedSum'],
    };
}

