/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Demand } from './Demand.js';
import {
    DemandFromJSON,
    DemandFromJSONTyped,
    DemandToJSON,
    DemandToJSONTyped,
} from './Demand.js';
import type { Account } from './Account.js';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account.js';
import type { Agent } from './Agent.js';
import {
    AgentFromJSON,
    AgentFromJSONTyped,
    AgentToJSON,
    AgentToJSONTyped,
} from './Agent.js';
import type { Group } from './Group.js';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Organization } from './Organization.js';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
    OrganizationToJSONTyped,
} from './Organization.js';
import type { CurrencyRate } from './CurrencyRate.js';
import {
    CurrencyRateFromJSON,
    CurrencyRateFromJSONTyped,
    CurrencyRateToJSON,
    CurrencyRateToJSONTyped,
} from './CurrencyRate.js';
import type { FileList } from './FileList.js';
import {
    FileListFromJSON,
    FileListFromJSONTyped,
    FileListToJSON,
    FileListToJSONTyped,
} from './FileList.js';
import type { AttributeAbstract } from './AttributeAbstract.js';
import {
    AttributeAbstractFromJSON,
    AttributeAbstractFromJSONTyped,
    AttributeAbstractToJSON,
    AttributeAbstractToJSONTyped,
} from './AttributeAbstract.js';
import type { Loss } from './Loss.js';
import {
    LossFromJSON,
    LossFromJSONTyped,
    LossToJSON,
    LossToJSONTyped,
} from './Loss.js';
import type { SalesReturnPositionList } from './SalesReturnPositionList.js';
import {
    SalesReturnPositionListFromJSON,
    SalesReturnPositionListFromJSONTyped,
    SalesReturnPositionListToJSON,
    SalesReturnPositionListToJSONTyped,
} from './SalesReturnPositionList.js';
import type { Store } from './Store.js';
import {
    StoreFromJSON,
    StoreFromJSONTyped,
    StoreToJSON,
    StoreToJSONTyped,
} from './Store.js';
import type { SalesChannel } from './SalesChannel.js';
import {
    SalesChannelFromJSON,
    SalesChannelFromJSONTyped,
    SalesChannelToJSON,
    SalesChannelToJSONTyped,
} from './SalesChannel.js';
import type { Project } from './Project.js';
import {
    ProjectFromJSON,
    ProjectFromJSONTyped,
    ProjectToJSON,
    ProjectToJSONTyped,
} from './Project.js';
import type { Employee } from './Employee.js';
import {
    EmployeeFromJSON,
    EmployeeFromJSONTyped,
    EmployeeToJSON,
    EmployeeToJSONTyped,
} from './Employee.js';
import type { FactureOut } from './FactureOut.js';
import {
    FactureOutFromJSON,
    FactureOutFromJSONTyped,
    FactureOutToJSON,
    FactureOutToJSONTyped,
} from './FactureOut.js';
import type { State } from './State.js';
import {
    StateFromJSON,
    StateFromJSONTyped,
    StateToJSON,
    StateToJSONTyped,
} from './State.js';
import type { Contract } from './Contract.js';
import {
    ContractFromJSON,
    ContractFromJSONTyped,
    ContractToJSON,
    ContractToJSONTyped,
} from './Contract.js';
import type { SalesReturnPaymentsInner } from './SalesReturnPaymentsInner.js';
import {
    SalesReturnPaymentsInnerFromJSON,
    SalesReturnPaymentsInnerFromJSONTyped,
    SalesReturnPaymentsInnerToJSON,
    SalesReturnPaymentsInnerToJSONTyped,
} from './SalesReturnPaymentsInner.js';

import * as FinanceOutOperationSalesReturnPolymorphicParent from './FinanceOutOperationAbstract.js';
/**
 * Возврат покупателя + linkedSum
 * @export
 * @interface FinanceOutOperationSalesReturn
 */
export interface FinanceOutOperationSalesReturnOwn {
    /**
     * 
     * @type {Meta}
     * @memberof FinanceOutOperationSalesReturn
     */
    meta?: Meta;
    /**
     * ID Возврата покупателя
     * @type {string}
     * @memberof FinanceOutOperationSalesReturn
     */
    readonly id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof FinanceOutOperationSalesReturn
     */
    readonly accountId?: string;
    /**
     * Наименование Возврата покупателя
     * @type {string}
     * @memberof FinanceOutOperationSalesReturn
     */
    name?: string;
    /**
     * Код Возврата покупателя
     * @type {string}
     * @memberof FinanceOutOperationSalesReturn
     */
    code?: string;
    /**
     * Внешний код Возврата покупателя
     * @type {string}
     * @memberof FinanceOutOperationSalesReturn
     */
    externalCode?: string;
    /**
     * ID синхронизации
     * @type {string}
     * @memberof FinanceOutOperationSalesReturn
     */
    syncId?: string;
    /**
     * Комментарий Возврата покупателя
     * @type {string}
     * @memberof FinanceOutOperationSalesReturn
     */
    description?: string | null;
    /**
     * Дата создания
     * @type {string}
     * @memberof FinanceOutOperationSalesReturn
     */
    readonly created?: string;
    /**
     * Момент последнего удаления Возврата покупателя
     * @type {string}
     * @memberof FinanceOutOperationSalesReturn
     */
    readonly deleted?: string;
    /**
     * Момент последнего обновления Возврата покупателя
     * @type {string}
     * @memberof FinanceOutOperationSalesReturn
     */
    readonly updated?: string;
    /**
     * Дата документа
     * @type {string}
     * @memberof FinanceOutOperationSalesReturn
     */
    moment?: string;
    /**
     * Отметка о проведении
     * @type {boolean}
     * @memberof FinanceOutOperationSalesReturn
     */
    applicable?: boolean;
    /**
     * Напечатан ли документ
     * @type {boolean}
     * @memberof FinanceOutOperationSalesReturn
     */
    readonly printed?: boolean;
    /**
     * Опубликован ли документ
     * @type {boolean}
     * @memberof FinanceOutOperationSalesReturn
     */
    readonly published?: boolean;
    /**
     * Общий доступ
     * @type {boolean}
     * @memberof FinanceOutOperationSalesReturn
     */
    shared?: boolean;
    /**
     * Учитывается ли НДС
     * @type {boolean}
     * @memberof FinanceOutOperationSalesReturn
     */
    vatEnabled?: boolean;
    /**
     * Включен ли НДС в цену
     * @type {boolean}
     * @memberof FinanceOutOperationSalesReturn
     */
    vatIncluded?: boolean;
    /**
     * Сумма НДС
     * @type {number}
     * @memberof FinanceOutOperationSalesReturn
     */
    vatSum?: number;
    /**
     * Сумма Возврата покупателя в копейках
     * @type {number}
     * @memberof FinanceOutOperationSalesReturn
     */
    readonly sum?: number;
    /**
     * Сумма исходящих платежей по Возврату покупателя
     * @type {number}
     * @memberof FinanceOutOperationSalesReturn
     */
    payedSum?: number;
    /**
     * 
     * @type {Organization}
     * @memberof FinanceOutOperationSalesReturn
     */
    organization?: Organization;
    /**
     * Метаданные счета юрлица
     * @type {Account}
     * @memberof FinanceOutOperationSalesReturn
     */
    organizationAccount?: Account | null;
    /**
     * Метаданные Контрагента или юрлица
     * @type {Agent}
     * @memberof FinanceOutOperationSalesReturn
     */
    agent?: Agent;
    /**
     * Метаданные счета контрагента
     * @type {Account}
     * @memberof FinanceOutOperationSalesReturn
     */
    agentAccount?: Account | null;
    /**
     * Метаданные склада
     * @type {Store}
     * @memberof FinanceOutOperationSalesReturn
     */
    store?: Store | null;
    /**
     * Метаданные статуса Возврата покупателя
     * @type {State}
     * @memberof FinanceOutOperationSalesReturn
     */
    state?: State | null;
    /**
     * Метаданные договора
     * @type {Contract}
     * @memberof FinanceOutOperationSalesReturn
     */
    contract?: Contract | null;
    /**
     * Метаданные проекта
     * @type {Project}
     * @memberof FinanceOutOperationSalesReturn
     */
    project?: Project | null;
    /**
     * Владелец (Сотрудник)
     * @type {Employee}
     * @memberof FinanceOutOperationSalesReturn
     */
    owner?: Employee | null;
    /**
     * 
     * @type {Group}
     * @memberof FinanceOutOperationSalesReturn
     */
    group?: Group;
    /**
     * Коллекция метаданных доп. полей
     * @type {Array<AttributeAbstract>}
     * @memberof FinanceOutOperationSalesReturn
     */
    attributes?: Array<AttributeAbstract> | null;
    /**
     * Метаданные массива Файлов
     * @type {FileList}
     * @memberof FinanceOutOperationSalesReturn
     */
    files?: FileList | null;
    /**
     * 
     * @type {CurrencyRate}
     * @memberof FinanceOutOperationSalesReturn
     */
    rate?: CurrencyRate;
    /**
     * 
     * @type {SalesReturnPositionList}
     * @memberof FinanceOutOperationSalesReturn
     */
    positions?: SalesReturnPositionList;
    /**
     * Метаданные канала продаж
     * @type {SalesChannel}
     * @memberof FinanceOutOperationSalesReturn
     */
    salesChannel?: SalesChannel | null;
    /**
     * Отгрузка, по которой произошел возврат
     * @type {Demand}
     * @memberof FinanceOutOperationSalesReturn
     */
    demand?: Demand | null;
    /**
     * Массив ссылок на связанные списания
     * @type {Array<Loss>}
     * @memberof FinanceOutOperationSalesReturn
     */
    losses?: Array<Loss> | null;
    /**
     * Массив ссылок на связанные платежи
     * @type {Array<SalesReturnPaymentsInner>}
     * @memberof FinanceOutOperationSalesReturn
     */
    payments?: Array<SalesReturnPaymentsInner> | null;
    /**
     * Счет-фактура выданный, с которым связан этот возврат
     * @type {FactureOut}
     * @memberof FinanceOutOperationSalesReturn
     */
    factureOut?: FactureOut | null;
}
export type FinanceOutOperationSalesReturn = FinanceOutOperationSalesReturnOwn & FinanceOutOperationSalesReturnPolymorphicParent.FinanceOutOperationAbstract;


/**
 * Check if a given object implements the FinanceOutOperationSalesReturn interface.
 */
export function instanceOfFinanceOutOperationSalesReturn(value: object): value is FinanceOutOperationSalesReturn {
    return true;
}

export function FinanceOutOperationSalesReturnFromJSON(json: any): FinanceOutOperationSalesReturn {
    return FinanceOutOperationSalesReturnFromJSONTyped(json, false);
}

export function FinanceOutOperationSalesReturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinanceOutOperationSalesReturn {
    if (json == null) {
        return json;
    }
    return {
        ...FinanceOutOperationSalesReturnPolymorphicParent.FinanceOutOperationAbstractFromJSONTyped(json, true),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'externalCode': json['externalCode'] == null ? undefined : json['externalCode'],
        'syncId': json['syncId'] == null ? undefined : json['syncId'],
        'description': json['description'] == null ? undefined : json['description'],
        'created': json['created'] == null ? undefined : json['created'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'updated': json['updated'] == null ? undefined : json['updated'],
        'moment': json['moment'] == null ? undefined : json['moment'],
        'applicable': json['applicable'] == null ? undefined : json['applicable'],
        'printed': json['printed'] == null ? undefined : json['printed'],
        'published': json['published'] == null ? undefined : json['published'],
        'shared': json['shared'] == null ? undefined : json['shared'],
        'vatEnabled': json['vatEnabled'] == null ? undefined : json['vatEnabled'],
        'vatIncluded': json['vatIncluded'] == null ? undefined : json['vatIncluded'],
        'vatSum': json['vatSum'] == null ? undefined : json['vatSum'],
        'sum': json['sum'] == null ? undefined : json['sum'],
        'payedSum': json['payedSum'] == null ? undefined : json['payedSum'],
        'organization': json['organization'] == null ? undefined : OrganizationFromJSON(json['organization']),
        'organizationAccount': json['organizationAccount'] == null ? undefined : AccountFromJSON(json['organizationAccount']),
        'agent': json['agent'] == null ? undefined : AgentFromJSON(json['agent']),
        'agentAccount': json['agentAccount'] == null ? undefined : AccountFromJSON(json['agentAccount']),
        'store': json['store'] == null ? undefined : StoreFromJSON(json['store']),
        'state': json['state'] == null ? undefined : StateFromJSON(json['state']),
        'contract': json['contract'] == null ? undefined : ContractFromJSON(json['contract']),
        'project': json['project'] == null ? undefined : ProjectFromJSON(json['project']),
        'owner': json['owner'] == null ? undefined : EmployeeFromJSON(json['owner']),
        'group': json['group'] == null ? undefined : GroupFromJSON(json['group']),
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(AttributeAbstractFromJSON)),
        'files': json['files'] == null ? undefined : FileListFromJSON(json['files']),
        'rate': json['rate'] == null ? undefined : json['rate'],
        'positions': json['positions'] == null ? undefined : SalesReturnPositionListFromJSON(json['positions']),
        'salesChannel': json['salesChannel'] == null ? undefined : SalesChannelFromJSON(json['salesChannel']),
        'demand': json['demand'] == null ? undefined : DemandFromJSON(json['demand']),
        'losses': json['losses'] == null ? undefined : ((json['losses'] as Array<any>).map(LossFromJSON)),
        'payments': json['payments'] == null ? undefined : ((json['payments'] as Array<any>).map(SalesReturnPaymentsInnerFromJSON)),
        'factureOut': json['factureOut'] == null ? undefined : FactureOutFromJSON(json['factureOut']),
    };
}

export function FinanceOutOperationSalesReturnToJSON(json: any): FinanceOutOperationSalesReturn {
    return FinanceOutOperationSalesReturnToJSONTyped(json, false);
}

export function FinanceOutOperationSalesReturnToJSONTyped(value?: Omit<FinanceOutOperationSalesReturn, 'id'|'accountId'|'created'|'deleted'|'updated'|'printed'|'published'|'sum'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...FinanceOutOperationSalesReturnPolymorphicParent.FinanceOutOperationAbstractToJSONTyped(value as any, true),
        'meta': MetaToJSON(value['meta']),
        'name': value['name'],
        'code': value['code'],
        'externalCode': value['externalCode'],
        'syncId': value['syncId'],
        'description': value['description'],
        'moment': value['moment'],
        'applicable': value['applicable'],
        'shared': value['shared'],
        'vatEnabled': value['vatEnabled'],
        'vatIncluded': value['vatIncluded'],
        'vatSum': value['vatSum'],
        'payedSum': value['payedSum'],
        'organization': OrganizationToJSON(value['organization']),
        'organizationAccount': AccountToJSON(value['organizationAccount']),
        'agent': AgentToJSON(value['agent']),
        'agentAccount': AccountToJSON(value['agentAccount']),
        'store': StoreToJSON(value['store']),
        'state': StateToJSON(value['state']),
        'contract': ContractToJSON(value['contract']),
        'project': ProjectToJSON(value['project']),
        'owner': EmployeeToJSON(value['owner']),
        'group': GroupToJSON(value['group']),
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(AttributeAbstractToJSON)),
        'files': FileListToJSON(value['files']),
        'rate': value['rate'],
        'positions': SalesReturnPositionListToJSON(value['positions']),
        'salesChannel': SalesChannelToJSON(value['salesChannel']),
        'demand': DemandToJSON(value['demand']),
        'losses': value['losses'] == null ? undefined : ((value['losses'] as Array<any>).map(LossToJSON)),
        'payments': value['payments'] == null ? undefined : ((value['payments'] as Array<any>).map(SalesReturnPaymentsInnerToJSON)),
        'factureOut': FactureOutToJSON(value['factureOut']),
    };
}

