/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Account } from './Account.js';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account.js';
import type { MetaList } from './MetaList.js';
import {
    MetaListFromJSON,
    MetaListFromJSONTyped,
    MetaListToJSON,
    MetaListToJSONTyped,
} from './MetaList.js';

/**
 * 
 * @export
 * @interface GetCounterpartyAccounts200Response
 */
export interface GetCounterpartyAccounts200Response {
    /**
     * 
     * @type {MetaList}
     * @memberof GetCounterpartyAccounts200Response
     */
    meta?: MetaList;
    /**
     * 
     * @type {Array<Account>}
     * @memberof GetCounterpartyAccounts200Response
     */
    rows?: Array<Account>;
}


/**
 * Check if a given object implements the GetCounterpartyAccounts200Response interface.
 */
export function instanceOfGetCounterpartyAccounts200Response(value: object): value is GetCounterpartyAccounts200Response {
    return true;
}

export function GetCounterpartyAccounts200ResponseFromJSON(json: any): GetCounterpartyAccounts200Response {
    return GetCounterpartyAccounts200ResponseFromJSONTyped(json, false);
}

export function GetCounterpartyAccounts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCounterpartyAccounts200Response {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaListFromJSON(json['meta']),
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(AccountFromJSON)),
    };
}

export function GetCounterpartyAccounts200ResponseToJSON(json: any): GetCounterpartyAccounts200Response {
    return GetCounterpartyAccounts200ResponseToJSONTyped(json, false);
}

export function GetCounterpartyAccounts200ResponseToJSONTyped(value?: GetCounterpartyAccounts200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaListToJSON(value['meta']),
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(AccountToJSON)),
    };
}

