/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Image } from './Image.js';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
    ImageToJSONTyped,
} from './Image.js';
import type { MetaList } from './MetaList.js';
import {
    MetaListFromJSON,
    MetaListFromJSONTyped,
    MetaListToJSON,
    MetaListToJSONTyped,
} from './MetaList.js';

/**
 * Изображения
 * @export
 * @interface ImageList
 */
export interface ImageList {
    /**
     * 
     * @type {MetaList}
     * @memberof ImageList
     */
    meta?: MetaList;
    /**
     * 
     * @type {Array<Image>}
     * @memberof ImageList
     */
    rows?: Array<Image> | null;
}


/**
 * Check if a given object implements the ImageList interface.
 */
export function instanceOfImageList(value: object): value is ImageList {
    return true;
}

export function ImageListFromJSON(json: any): ImageList {
    return ImageListFromJSONTyped(json, false);
}

export function ImageListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageList {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaListFromJSON(json['meta']),
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(ImageFromJSON)),
    };
}

export function ImageListToJSON(json: any): ImageList {
    return ImageListToJSONTyped(json, false);
}

export function ImageListToJSONTyped(value?: ImageList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaListToJSON(value['meta']),
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(ImageToJSON)),
    };
}

