/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Group } from './Group.js';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Organization } from './Organization.js';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
    OrganizationToJSONTyped,
} from './Organization.js';
import type { CurrencyRate } from './CurrencyRate.js';
import {
    CurrencyRateFromJSON,
    CurrencyRateFromJSONTyped,
    CurrencyRateToJSON,
    CurrencyRateToJSONTyped,
} from './CurrencyRate.js';
import type { FileList } from './FileList.js';
import {
    FileListFromJSON,
    FileListFromJSONTyped,
    FileListToJSON,
    FileListToJSONTyped,
} from './FileList.js';
import type { AttributeAbstract } from './AttributeAbstract.js';
import {
    AttributeAbstractFromJSON,
    AttributeAbstractFromJSONTyped,
    AttributeAbstractToJSON,
    AttributeAbstractToJSONTyped,
} from './AttributeAbstract.js';
import type { Store } from './Store.js';
import {
    StoreFromJSON,
    StoreFromJSONTyped,
    StoreToJSON,
    StoreToJSONTyped,
} from './Store.js';
import type { Project } from './Project.js';
import {
    ProjectFromJSON,
    ProjectFromJSONTyped,
    ProjectToJSON,
    ProjectToJSONTyped,
} from './Project.js';
import type { Employee } from './Employee.js';
import {
    EmployeeFromJSON,
    EmployeeFromJSONTyped,
    EmployeeToJSON,
    EmployeeToJSONTyped,
} from './Employee.js';
import type { ProcessingOrder } from './ProcessingOrder.js';
import {
    ProcessingOrderFromJSON,
    ProcessingOrderFromJSONTyped,
    ProcessingOrderToJSON,
    ProcessingOrderToJSONTyped,
} from './ProcessingOrder.js';
import type { InternalOrderPositionList } from './InternalOrderPositionList.js';
import {
    InternalOrderPositionListFromJSON,
    InternalOrderPositionListFromJSONTyped,
    InternalOrderPositionListToJSON,
    InternalOrderPositionListToJSONTyped,
} from './InternalOrderPositionList.js';
import type { Move } from './Move.js';
import {
    MoveFromJSON,
    MoveFromJSONTyped,
    MoveToJSON,
    MoveToJSONTyped,
} from './Move.js';
import type { State } from './State.js';
import {
    StateFromJSON,
    StateFromJSONTyped,
    StateToJSON,
    StateToJSONTyped,
} from './State.js';
import type { PurchaseOrder } from './PurchaseOrder.js';
import {
    PurchaseOrderFromJSON,
    PurchaseOrderFromJSONTyped,
    PurchaseOrderToJSON,
    PurchaseOrderToJSONTyped,
} from './PurchaseOrder.js';
import type { ProductionTask } from './ProductionTask.js';
import {
    ProductionTaskFromJSON,
    ProductionTaskFromJSONTyped,
    ProductionTaskToJSON,
    ProductionTaskToJSONTyped,
} from './ProductionTask.js';

import * as InternalOrderPolymorphicParent from './EntityWithMeta.js';
/**
 * Внутренний заказ
 * @export
 * @interface InternalOrder
 */
export interface InternalOrderOwn {
    /**
     * 
     * @type {Meta}
     * @memberof InternalOrder
     */
    meta?: Meta;
    /**
     * ID Внутреннего заказа
     * @type {string}
     * @memberof InternalOrder
     */
    readonly id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof InternalOrder
     */
    readonly accountId?: string;
    /**
     * Наименование Внутреннего заказа
     * @type {string}
     * @memberof InternalOrder
     */
    name?: string;
    /**
     * Код Внутреннего заказа
     * @type {string}
     * @memberof InternalOrder
     */
    code?: string;
    /**
     * Внешний код Внутреннего заказа
     * @type {string}
     * @memberof InternalOrder
     */
    externalCode?: string;
    /**
     * ID синхронизации
     * @type {string}
     * @memberof InternalOrder
     */
    syncId?: string;
    /**
     * Комментарий Внутреннего заказа
     * @type {string}
     * @memberof InternalOrder
     */
    description?: string | null;
    /**
     * Дата создания
     * @type {string}
     * @memberof InternalOrder
     */
    readonly created?: string;
    /**
     * Момент последнего удаления Внутреннего заказа
     * @type {string}
     * @memberof InternalOrder
     */
    readonly deleted?: string;
    /**
     * Момент последнего обновления Внутреннего заказа
     * @type {string}
     * @memberof InternalOrder
     */
    readonly updated?: string;
    /**
     * Дата документа
     * @type {string}
     * @memberof InternalOrder
     */
    moment?: string;
    /**
     * Планируемая дата приемки
     * @type {string}
     * @memberof InternalOrder
     */
    deliveryPlannedMoment?: string;
    /**
     * Отметка о проведении
     * @type {boolean}
     * @memberof InternalOrder
     */
    applicable?: boolean;
    /**
     * Напечатан ли документ
     * @type {boolean}
     * @memberof InternalOrder
     */
    readonly printed?: boolean;
    /**
     * Опубликован ли документ
     * @type {boolean}
     * @memberof InternalOrder
     */
    readonly published?: boolean;
    /**
     * Общий доступ
     * @type {boolean}
     * @memberof InternalOrder
     */
    readonly shared?: boolean;
    /**
     * Учитывается ли НДС
     * @type {boolean}
     * @memberof InternalOrder
     */
    vatEnabled?: boolean;
    /**
     * Включен ли НДС в цену
     * @type {boolean}
     * @memberof InternalOrder
     */
    vatIncluded?: boolean;
    /**
     * Сумма НДС
     * @type {number}
     * @memberof InternalOrder
     */
    readonly vatSum?: number;
    /**
     * Сумма Внутреннего заказа в копейках
     * @type {number}
     * @memberof InternalOrder
     */
    readonly sum?: number;
    /**
     * 
     * @type {Organization}
     * @memberof InternalOrder
     */
    organization?: Organization;
    /**
     * Метаданные склада
     * @type {Store}
     * @memberof InternalOrder
     */
    store?: Store | null;
    /**
     * Метаданные статуса Внутреннего заказа
     * @type {State}
     * @memberof InternalOrder
     */
    state?: State | null;
    /**
     * Метаданные проекта
     * @type {Project}
     * @memberof InternalOrder
     */
    project?: Project | null;
    /**
     * Владелец (Сотрудник)
     * @type {Employee}
     * @memberof InternalOrder
     */
    owner?: Employee | null;
    /**
     * 
     * @type {Group}
     * @memberof InternalOrder
     */
    group?: Group;
    /**
     * Коллекция метаданных доп. полей
     * @type {Array<AttributeAbstract>}
     * @memberof InternalOrder
     */
    attributes?: Array<AttributeAbstract> | null;
    /**
     * Метаданные массива Файлов
     * @type {FileList}
     * @memberof InternalOrder
     */
    files?: FileList | null;
    /**
     * 
     * @type {CurrencyRate}
     * @memberof InternalOrder
     */
    rate?: CurrencyRate;
    /**
     * 
     * @type {InternalOrderPositionList}
     * @memberof InternalOrder
     */
    positions?: InternalOrderPositionList;
    /**
     * Коллекция метаданных на связанные заказы поставщику
     * @type {Array<PurchaseOrder>}
     * @memberof InternalOrder
     */
    purchaseOrders?: Array<PurchaseOrder> | null;
    /**
     * Массив ссылок на связанные производственные задания
     * @type {Array<ProductionTask>}
     * @memberof InternalOrder
     */
    productionTasks?: Array<ProductionTask> | null;
    /**
     * Коллекция метаданных на связанные заказы перемещения
     * @type {Array<Move>}
     * @memberof InternalOrder
     */
    moves?: Array<Move> | null;
    /**
     * Метаданные Заказа на производство
     * @type {ProcessingOrder}
     * @memberof InternalOrder
     */
    processingOrder?: ProcessingOrder | null;
}
export type InternalOrder = InternalOrderOwn & InternalOrderPolymorphicParent.EntityWithMeta;


/**
 * Check if a given object implements the InternalOrder interface.
 */
export function instanceOfInternalOrder(value: object): value is InternalOrder {
    return true;
}

export function InternalOrderFromJSON(json: any): InternalOrder {
    return InternalOrderFromJSONTyped(json, false);
}

export function InternalOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalOrder {
    if (json == null) {
        return json;
    }
    return {
        ...InternalOrderPolymorphicParent.EntityWithMetaFromJSONTyped(json, true),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'externalCode': json['externalCode'] == null ? undefined : json['externalCode'],
        'syncId': json['syncId'] == null ? undefined : json['syncId'],
        'description': json['description'] == null ? undefined : json['description'],
        'created': json['created'] == null ? undefined : json['created'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'updated': json['updated'] == null ? undefined : json['updated'],
        'moment': json['moment'] == null ? undefined : json['moment'],
        'deliveryPlannedMoment': json['deliveryPlannedMoment'] == null ? undefined : json['deliveryPlannedMoment'],
        'applicable': json['applicable'] == null ? undefined : json['applicable'],
        'printed': json['printed'] == null ? undefined : json['printed'],
        'published': json['published'] == null ? undefined : json['published'],
        'shared': json['shared'] == null ? undefined : json['shared'],
        'vatEnabled': json['vatEnabled'] == null ? undefined : json['vatEnabled'],
        'vatIncluded': json['vatIncluded'] == null ? undefined : json['vatIncluded'],
        'vatSum': json['vatSum'] == null ? undefined : json['vatSum'],
        'sum': json['sum'] == null ? undefined : json['sum'],
        'organization': json['organization'] == null ? undefined : OrganizationFromJSON(json['organization']),
        'store': json['store'] == null ? undefined : StoreFromJSON(json['store']),
        'state': json['state'] == null ? undefined : StateFromJSON(json['state']),
        'project': json['project'] == null ? undefined : ProjectFromJSON(json['project']),
        'owner': json['owner'] == null ? undefined : EmployeeFromJSON(json['owner']),
        'group': json['group'] == null ? undefined : GroupFromJSON(json['group']),
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(AttributeAbstractFromJSON)),
        'files': json['files'] == null ? undefined : FileListFromJSON(json['files']),
        'rate': json['rate'] == null ? undefined : CurrencyRateFromJSON(json['rate']),
        'positions': json['positions'] == null ? undefined : InternalOrderPositionListFromJSON(json['positions']),
        'purchaseOrders': json['purchaseOrders'] == null ? undefined : ((json['purchaseOrders'] as Array<any>).map(PurchaseOrderFromJSON)),
        'productionTasks': json['productionTasks'] == null ? undefined : ((json['productionTasks'] as Array<any>).map(ProductionTaskFromJSON)),
        'moves': json['moves'] == null ? undefined : ((json['moves'] as Array<any>).map(MoveFromJSON)),
        'processingOrder': json['processingOrder'] == null ? undefined : ProcessingOrderFromJSON(json['processingOrder']),
    };
}

export function InternalOrderToJSON(json: any): InternalOrder {
    return InternalOrderToJSONTyped(json, false);
}

export function InternalOrderToJSONTyped(value?: Omit<InternalOrder, 'id'|'accountId'|'created'|'deleted'|'updated'|'printed'|'published'|'shared'|'vatSum'|'sum'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...InternalOrderPolymorphicParent.EntityWithMetaToJSONTyped(value as any, true),
        'meta': MetaToJSON(value['meta']),
        'name': value['name'],
        'code': value['code'],
        'externalCode': value['externalCode'],
        'syncId': value['syncId'],
        'description': value['description'],
        'moment': value['moment'],
        'deliveryPlannedMoment': value['deliveryPlannedMoment'],
        'applicable': value['applicable'],
        'vatEnabled': value['vatEnabled'],
        'vatIncluded': value['vatIncluded'],
        'organization': OrganizationToJSON(value['organization']),
        'store': StoreToJSON(value['store']),
        'state': StateToJSON(value['state']),
        'project': ProjectToJSON(value['project']),
        'owner': EmployeeToJSON(value['owner']),
        'group': GroupToJSON(value['group']),
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(AttributeAbstractToJSON)),
        'files': FileListToJSON(value['files']),
        'rate': CurrencyRateToJSON(value['rate']),
        'positions': InternalOrderPositionListToJSON(value['positions']),
        'purchaseOrders': value['purchaseOrders'] == null ? undefined : ((value['purchaseOrders'] as Array<any>).map(PurchaseOrderToJSON)),
        'productionTasks': value['productionTasks'] == null ? undefined : ((value['productionTasks'] as Array<any>).map(ProductionTaskToJSON)),
        'moves': value['moves'] == null ? undefined : ((value['moves'] as Array<any>).map(MoveToJSON)),
        'processingOrder': ProcessingOrderToJSON(value['processingOrder']),
    };
}

