/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Pack } from './Pack.js';
import {
    PackFromJSON,
    PackFromJSONTyped,
    PackToJSON,
    PackToJSONTyped,
} from './Pack.js';
import type { ProductMarker } from './ProductMarker.js';
import {
    ProductMarkerFromJSON,
    ProductMarkerFromJSONTyped,
    ProductMarkerToJSON,
    ProductMarkerToJSONTyped,
} from './ProductMarker.js';

import * as InvoiceOutPositionPolymorphicParent from './EntityWithMeta.js';
/**
 * Позиция Счета покупателю
 * @export
 * @interface InvoiceOutPosition
 */
export interface InvoiceOutPositionOwn {
    /**
     * 
     * @type {Meta}
     * @memberof InvoiceOutPosition
     */
    meta?: Meta;
    /**
     * ID позиции
     * @type {string}
     * @memberof InvoiceOutPosition
     */
    id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof InvoiceOutPosition
     */
    readonly accountId?: string;
    /**
     * Количество товаров/услуг данного вида в позиции
     * @type {number}
     * @memberof InvoiceOutPosition
     */
    quantity?: number;
    /**
     * Цена товара/услуги в копейках
     * @type {number}
     * @memberof InvoiceOutPosition
     */
    price?: number;
    /**
     * Процент скидки или наценки
     * @type {number}
     * @memberof InvoiceOutPosition
     */
    discount?: number;
    /**
     * НДС, которым облагается текущая позиция
     * @type {number}
     * @memberof InvoiceOutPosition
     */
    vat?: number;
    /**
     * Включен ли НДС для позиции
     * @type {boolean}
     * @memberof InvoiceOutPosition
     */
    vatEnabled?: boolean;
    /**
     * Метаданные товара/услуги/партии/модификации/комплекта, которую представляет собой позиция
     * @type {ProductMarker}
     * @memberof InvoiceOutPosition
     */
    assortment?: ProductMarker;
    /**
     * Упаковка Товара
     * @type {Pack}
     * @memberof InvoiceOutPosition
     */
    pack?: Pack | null;
}
export type InvoiceOutPosition = InvoiceOutPositionOwn & InvoiceOutPositionPolymorphicParent.EntityWithMeta;


/**
 * Check if a given object implements the InvoiceOutPosition interface.
 */
export function instanceOfInvoiceOutPosition(value: object): value is InvoiceOutPosition {
    return true;
}

export function InvoiceOutPositionFromJSON(json: any): InvoiceOutPosition {
    return InvoiceOutPositionFromJSONTyped(json, false);
}

export function InvoiceOutPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceOutPosition {
    if (json == null) {
        return json;
    }
    return {
        ...InvoiceOutPositionPolymorphicParent.EntityWithMetaFromJSONTyped(json, true),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'price': json['price'] == null ? undefined : json['price'],
        'discount': json['discount'] == null ? undefined : json['discount'],
        'vat': json['vat'] == null ? undefined : json['vat'],
        'vatEnabled': json['vatEnabled'] == null ? undefined : json['vatEnabled'],
        'assortment': json['assortment'] == null ? undefined : ProductMarkerFromJSON(json['assortment']),
        'pack': json['pack'] == null ? undefined : PackFromJSON(json['pack']),
    };
}

export function InvoiceOutPositionToJSON(json: any): InvoiceOutPosition {
    return InvoiceOutPositionToJSONTyped(json, false);
}

export function InvoiceOutPositionToJSONTyped(value?: Omit<InvoiceOutPosition, 'accountId'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...InvoiceOutPositionPolymorphicParent.EntityWithMetaToJSONTyped(value as any, true),
        'meta': MetaToJSON(value['meta']),
        'id': value['id'],
        'quantity': value['quantity'],
        'price': value['price'],
        'discount': value['discount'],
        'vat': value['vat'],
        'vatEnabled': value['vatEnabled'],
        'assortment': ProductMarkerToJSON(value['assortment']),
        'pack': PackToJSON(value['pack']),
    };
}

