/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Context } from './Context.js';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context.js';
import type { InvoiceOut } from './InvoiceOut.js';
import {
    InvoiceOutFromJSON,
    InvoiceOutFromJSONTyped,
    InvoiceOutToJSON,
    InvoiceOutToJSONTyped,
} from './InvoiceOut.js';
import type { MetaList } from './MetaList.js';
import {
    MetaListFromJSON,
    MetaListFromJSONTyped,
    MetaListToJSON,
    MetaListToJSONTyped,
} from './MetaList.js';

/**
 * Список Счетов покупателям
 * @export
 * @interface InvoiceOutList
 */
export interface InvoiceOutList {
    /**
     * 
     * @type {Context}
     * @memberof InvoiceOutList
     */
    context?: Context;
    /**
     * 
     * @type {MetaList}
     * @memberof InvoiceOutList
     */
    meta?: MetaList;
    /**
     * Массив Счетов покупателям
     * @type {Array<InvoiceOut>}
     * @memberof InvoiceOutList
     */
    rows?: Array<InvoiceOut> | null;
}


/**
 * Check if a given object implements the InvoiceOutList interface.
 */
export function instanceOfInvoiceOutList(value: object): value is InvoiceOutList {
    return true;
}

export function InvoiceOutListFromJSON(json: any): InvoiceOutList {
    return InvoiceOutListFromJSONTyped(json, false);
}

export function InvoiceOutListFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceOutList {
    if (json == null) {
        return json;
    }
    return {
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
        'meta': json['meta'] == null ? undefined : MetaListFromJSON(json['meta']),
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(InvoiceOutFromJSON)),
    };
}

export function InvoiceOutListToJSON(json: any): InvoiceOutList {
    return InvoiceOutListToJSONTyped(json, false);
}

export function InvoiceOutListToJSONTyped(value?: InvoiceOutList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'context': ContextToJSON(value['context']),
        'meta': MetaListToJSON(value['meta']),
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(InvoiceOutToJSON)),
    };
}

