/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Известные значения ограничения связи касс-слуг с кассами-мастерами
 * @export
 */
export const MinionToMasterType = {
    Any: 'ANY',
    SameGroup: 'SAME_GROUP',
    Chosen: 'CHOSEN'
} as const;
export type MinionToMasterType = typeof MinionToMasterType[keyof typeof MinionToMasterType];


export function instanceOfMinionToMasterType(value: any): boolean {
    for (const key in MinionToMasterType) {
        if (Object.prototype.hasOwnProperty.call(MinionToMasterType, key)) {
            if (MinionToMasterType[key as keyof typeof MinionToMasterType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MinionToMasterTypeFromJSON(json: any): MinionToMasterType {
    return MinionToMasterTypeFromJSONTyped(json, false);
}

export function MinionToMasterTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinionToMasterType {
    return json as MinionToMasterType;
}

export function MinionToMasterTypeToJSON(value?: MinionToMasterType | null): any {
    return value as any;
}

export function MinionToMasterTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): MinionToMasterType {
    return value as MinionToMasterType;
}

