/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';

import { type MinimumStockAllWarehouseSame, MinimumStockAllWarehouseSameFromJSONTyped, MinimumStockAllWarehouseSameToJSON, MinimumStockAllWarehouseSameToJSONTyped } from './MinimumStockAllWarehouseSame.js';
import { type MinimumStockAllWarehouseSum, MinimumStockAllWarehouseSumFromJSONTyped, MinimumStockAllWarehouseSumToJSON, MinimumStockAllWarehouseSumToJSONTyped } from './MinimumStockAllWarehouseSum.js';
import { type MinimumStockWarehouseVaried, MinimumStockWarehouseVariedFromJSONTyped, MinimumStockWarehouseVariedToJSON, MinimumStockWarehouseVariedToJSONTyped } from './MinimumStockWarehouseVaried.js';
/**
 * 
 * @export
 * @interface MinimumStockAbstract
 */
export interface MinimumStockAbstract {
    /**
     * Тип неснижаемого остатка
     * @type {string}
     * @memberof MinimumStockAbstract
     */
    readonly type: MinimumStockAbstractTypeEnum;
    /**
     * Признак наследуемости
     * @type {boolean}
     * @memberof MinimumStockAbstract
     */
    inherited?: boolean | null;
}


/**
 * @export
 */
export const MinimumStockAbstractTypeEnum = {
    AllWarehouseSum: 'ALL_WAREHOUSE_SUM',
    AllWarehouseSame: 'ALL_WAREHOUSE_SAME',
    WarehouseVaried: 'WAREHOUSE_VARIED'
} as const;
export type MinimumStockAbstractTypeEnum = typeof MinimumStockAbstractTypeEnum[keyof typeof MinimumStockAbstractTypeEnum];


/**
 * Check if a given object implements the MinimumStockAbstract interface.
 */
export function instanceOfMinimumStockAbstract(value: object): value is MinimumStockAbstract {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MinimumStockAbstractFromJSON(json: any): MinimumStockAbstract {
    return MinimumStockAbstractFromJSONTyped(json, false);
}

export function MinimumStockAbstractFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinimumStockAbstract {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['type'] === 'ALL_WAREHOUSE_SAME') {
            return MinimumStockAllWarehouseSameFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'ALL_WAREHOUSE_SUM') {
            return MinimumStockAllWarehouseSumFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'WAREHOUSE_VARIED') {
            return MinimumStockWarehouseVariedFromJSONTyped(json, ignoreDiscriminator);
        }
    }
    return {
        'type': json['type'],
        'inherited': json['inherited'] == null ? undefined : json['inherited'],
    };
}

export function MinimumStockAbstractToJSON(json: any): MinimumStockAbstract {
    return MinimumStockAbstractToJSONTyped(json, false);
}

export function MinimumStockAbstractToJSONTyped(value?: Omit<MinimumStockAbstract, 'type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (!ignoreDiscriminator) {
        switch (value['type']) {
            case 'ALL_WAREHOUSE_SAME':
                return MinimumStockAllWarehouseSameToJSONTyped(value as MinimumStockAllWarehouseSame, ignoreDiscriminator);
            case 'ALL_WAREHOUSE_SUM':
                return MinimumStockAllWarehouseSumToJSONTyped(value as MinimumStockAllWarehouseSum, ignoreDiscriminator);
            case 'WAREHOUSE_VARIED':
                return MinimumStockWarehouseVariedToJSONTyped(value as MinimumStockWarehouseVaried, ignoreDiscriminator);
            default:
                return value;
        }
    }
    return {
        'inherited': value['inherited'],
    };
}

