/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { NotificationOrder } from './NotificationOrder.js';
import {
    NotificationOrderFromJSON,
    NotificationOrderFromJSONTyped,
    NotificationOrderToJSON,
    NotificationOrderToJSONTyped,
} from './NotificationOrder.js';

import * as NotificationOrderOverduePolymorphicParent from './NotificationAbstract.js';
/**
 * Уведомление о просроченном заказе покупателя
 * @export
 * @interface NotificationOrderOverdue
 */
export interface NotificationOrderOverdueOwn {
    /**
     * Имя контрагента
     * @type {string}
     * @memberof NotificationOrderOverdue
     */
    agentName?: string;
    /**
     * Планируемое время отгрузки
     * @type {string}
     * @memberof NotificationOrderOverdue
     */
    deliveryPlannedMoment?: string;
    /**
     * 
     * @type {NotificationOrder}
     * @memberof NotificationOrderOverdue
     */
    order?: NotificationOrder;
    /**
     * Сумма заказа
     * @type {number}
     * @memberof NotificationOrderOverdue
     */
    sum?: number;
}
export type NotificationOrderOverdue = NotificationOrderOverdueOwn & NotificationOrderOverduePolymorphicParent.NotificationAbstract;


/**
 * Check if a given object implements the NotificationOrderOverdue interface.
 */
export function instanceOfNotificationOrderOverdue(value: object): value is NotificationOrderOverdue {
    return true;
}

export function NotificationOrderOverdueFromJSON(json: any): NotificationOrderOverdue {
    return NotificationOrderOverdueFromJSONTyped(json, false);
}

export function NotificationOrderOverdueFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationOrderOverdue {
    if (json == null) {
        return json;
    }
    return {
        ...NotificationOrderOverduePolymorphicParent.NotificationAbstractFromJSONTyped(json, true),
        'agentName': json['agentName'] == null ? undefined : json['agentName'],
        'deliveryPlannedMoment': json['deliveryPlannedMoment'] == null ? undefined : json['deliveryPlannedMoment'],
        'order': json['order'] == null ? undefined : NotificationOrderFromJSON(json['order']),
        'sum': json['sum'] == null ? undefined : json['sum'],
    };
}

export function NotificationOrderOverdueToJSON(json: any): NotificationOrderOverdue {
    return NotificationOrderOverdueToJSONTyped(json, false);
}

export function NotificationOrderOverdueToJSONTyped(value?: NotificationOrderOverdue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...NotificationOrderOverduePolymorphicParent.NotificationAbstractToJSONTyped(value as any, true),
        'agentName': value['agentName'],
        'deliveryPlannedMoment': value['deliveryPlannedMoment'],
        'order': NotificationOrderToJSON(value['order']),
        'sum': value['sum'],
    };
}

