/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { NotificationNamedEntity } from './NotificationNamedEntity.js';
import {
    NotificationNamedEntityFromJSON,
    NotificationNamedEntityFromJSONTyped,
    NotificationNamedEntityToJSON,
    NotificationNamedEntityToJSONTyped,
} from './NotificationNamedEntity.js';

import * as NotificationGoodCountTooLowPolymorphicParent from './NotificationAbstract.js';
/**
 * Уведомление о снижении остатка товара ниже неснижаемого
 * @export
 * @interface NotificationGoodCountTooLow
 */
export interface NotificationGoodCountTooLowOwn {
    /**
     * Остаток товара
     * @type {number}
     * @memberof NotificationGoodCountTooLow
     */
    actualBalance?: number;
    /**
     * 
     * @type {NotificationNamedEntity}
     * @memberof NotificationGoodCountTooLow
     */
    good?: NotificationNamedEntity;
    /**
     * Неснижаемый остаток товара
     * @type {number}
     * @memberof NotificationGoodCountTooLow
     */
    minimumBalance?: number;
}
export type NotificationGoodCountTooLow = NotificationGoodCountTooLowOwn & NotificationGoodCountTooLowPolymorphicParent.NotificationAbstract;


/**
 * Check if a given object implements the NotificationGoodCountTooLow interface.
 */
export function instanceOfNotificationGoodCountTooLow(value: object): value is NotificationGoodCountTooLow {
    return true;
}

export function NotificationGoodCountTooLowFromJSON(json: any): NotificationGoodCountTooLow {
    return NotificationGoodCountTooLowFromJSONTyped(json, false);
}

export function NotificationGoodCountTooLowFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationGoodCountTooLow {
    if (json == null) {
        return json;
    }
    return {
        ...NotificationGoodCountTooLowPolymorphicParent.NotificationAbstractFromJSONTyped(json, true),
        'actualBalance': json['actualBalance'] == null ? undefined : json['actualBalance'],
        'good': json['good'] == null ? undefined : NotificationNamedEntityFromJSON(json['good']),
        'minimumBalance': json['minimumBalance'] == null ? undefined : json['minimumBalance'],
    };
}

export function NotificationGoodCountTooLowToJSON(json: any): NotificationGoodCountTooLow {
    return NotificationGoodCountTooLowToJSONTyped(json, false);
}

export function NotificationGoodCountTooLowToJSONTyped(value?: NotificationGoodCountTooLow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...NotificationGoodCountTooLowPolymorphicParent.NotificationAbstractToJSONTyped(value as any, true),
        'actualBalance': value['actualBalance'],
        'good': NotificationNamedEntityToJSON(value['good']),
        'minimumBalance': value['minimumBalance'],
    };
}

