/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Накладные расходы на уровне документа
 * @export
 * @interface Overhead
 */
export interface Overhead {
    /**
     * Сумма в копейках
     * @type {number}
     * @memberof Overhead
     */
    sum?: number;
    /**
     * Распределение накладных расходов. Возможные значения описаны в OverheadDistribution
     * @type {string}
     * @memberof Overhead
     */
    distribution?: string;
}


/**
 * Check if a given object implements the Overhead interface.
 */
export function instanceOfOverhead(value: object): value is Overhead {
    return true;
}

export function OverheadFromJSON(json: any): Overhead {
    return OverheadFromJSONTyped(json, false);
}

export function OverheadFromJSONTyped(json: any, ignoreDiscriminator: boolean): Overhead {
    if (json == null) {
        return json;
    }
    return {
        'sum': json['sum'] == null ? undefined : json['sum'],
        'distribution': json['distribution'] == null ? undefined : json['distribution'],
    };
}

export function OverheadToJSON(json: any): Overhead {
    return OverheadToJSONTyped(json, false);
}

export function OverheadToJSONTyped(value?: Overhead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'sum': value['sum'],
        'distribution': value['distribution'],
    };
}

