/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Uom } from './Uom.js';
import {
    UomFromJSON,
    UomFromJSONTyped,
    UomToJSON,
    UomToJSONTyped,
} from './Uom.js';
import type { Barcode } from './Barcode.js';
import {
    BarcodeFromJSON,
    BarcodeFromJSONTyped,
    BarcodeToJSON,
    BarcodeToJSONTyped,
} from './Barcode.js';

/**
 * Упаковка
 * @export
 * @interface Pack
 */
export interface Pack {
    /**
     * 
     * @type {Meta}
     * @memberof Pack
     */
    meta?: Meta;
    /**
     * ID упаковки
     * @type {string}
     * @memberof Pack
     */
    readonly id?: string;
    /**
     * 
     * @type {Uom}
     * @memberof Pack
     */
    uom?: Uom;
    /**
     * Количество товаров в упаковке
     * @type {number}
     * @memberof Pack
     */
    quantity?: number;
    /**
     * Штрихкоды упаковки
     * @type {Array<Barcode>}
     * @memberof Pack
     */
    barcodes?: Array<Barcode> | null;
}


/**
 * Check if a given object implements the Pack interface.
 */
export function instanceOfPack(value: object): value is Pack {
    return true;
}

export function PackFromJSON(json: any): Pack {
    return PackFromJSONTyped(json, false);
}

export function PackFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pack {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'uom': json['uom'] == null ? undefined : UomFromJSON(json['uom']),
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'barcodes': json['barcodes'] == null ? undefined : ((json['barcodes'] as Array<any>).map(BarcodeFromJSON)),
    };
}

export function PackToJSON(json: any): Pack {
    return PackToJSONTyped(json, false);
}

export function PackToJSONTyped(value?: Omit<Pack, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaToJSON(value['meta']),
        'uom': UomToJSON(value['uom']),
        'quantity': value['quantity'],
        'barcodes': value['barcodes'] == null ? undefined : ((value['barcodes'] as Array<any>).map(BarcodeToJSON)),
    };
}

