/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Context } from './Context.js';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context.js';
import type { MetaList } from './MetaList.js';
import {
    MetaListFromJSON,
    MetaListFromJSONTyped,
    MetaListToJSON,
    MetaListToJSONTyped,
} from './MetaList.js';
import type { ProcessingPlanStage } from './ProcessingPlanStage.js';
import {
    ProcessingPlanStageFromJSON,
    ProcessingPlanStageFromJSONTyped,
    ProcessingPlanStageToJSON,
    ProcessingPlanStageToJSONTyped,
} from './ProcessingPlanStage.js';

/**
 * Список этапов Техкарты
 * @export
 * @interface ProcessingPlanStageList
 */
export interface ProcessingPlanStageList {
    /**
     * 
     * @type {Context}
     * @memberof ProcessingPlanStageList
     */
    context?: Context;
    /**
     * 
     * @type {MetaList}
     * @memberof ProcessingPlanStageList
     */
    meta?: MetaList;
    /**
     * Массив этапов Техкарты
     * @type {Array<ProcessingPlanStage>}
     * @memberof ProcessingPlanStageList
     */
    rows?: Array<ProcessingPlanStage> | null;
}


/**
 * Check if a given object implements the ProcessingPlanStageList interface.
 */
export function instanceOfProcessingPlanStageList(value: object): value is ProcessingPlanStageList {
    return true;
}

export function ProcessingPlanStageListFromJSON(json: any): ProcessingPlanStageList {
    return ProcessingPlanStageListFromJSONTyped(json, false);
}

export function ProcessingPlanStageListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessingPlanStageList {
    if (json == null) {
        return json;
    }
    return {
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
        'meta': json['meta'] == null ? undefined : MetaListFromJSON(json['meta']),
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(ProcessingPlanStageFromJSON)),
    };
}

export function ProcessingPlanStageListToJSON(json: any): ProcessingPlanStageList {
    return ProcessingPlanStageListToJSONTyped(json, false);
}

export function ProcessingPlanStageListToJSONTyped(value?: ProcessingPlanStageList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'context': ContextToJSON(value['context']),
        'meta': MetaListToJSON(value['meta']),
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(ProcessingPlanStageToJSON)),
    };
}

