/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Context } from './Context.js';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context.js';
import type { ProcessingProcessPosition } from './ProcessingProcessPosition.js';
import {
    ProcessingProcessPositionFromJSON,
    ProcessingProcessPositionFromJSONTyped,
    ProcessingProcessPositionToJSON,
    ProcessingProcessPositionToJSONTyped,
} from './ProcessingProcessPosition.js';
import type { MetaList } from './MetaList.js';
import {
    MetaListFromJSON,
    MetaListFromJSONTyped,
    MetaListToJSON,
    MetaListToJSONTyped,
} from './MetaList.js';

/**
 * Список позиций Техпроцесса
 * @export
 * @interface ProcessingProcessPositionList
 */
export interface ProcessingProcessPositionList {
    /**
     * 
     * @type {Context}
     * @memberof ProcessingProcessPositionList
     */
    context?: Context;
    /**
     * 
     * @type {MetaList}
     * @memberof ProcessingProcessPositionList
     */
    meta?: MetaList;
    /**
     * Массив позиций Техпроцесса
     * @type {Array<ProcessingProcessPosition>}
     * @memberof ProcessingProcessPositionList
     */
    rows?: Array<ProcessingProcessPosition> | null;
}


/**
 * Check if a given object implements the ProcessingProcessPositionList interface.
 */
export function instanceOfProcessingProcessPositionList(value: object): value is ProcessingProcessPositionList {
    return true;
}

export function ProcessingProcessPositionListFromJSON(json: any): ProcessingProcessPositionList {
    return ProcessingProcessPositionListFromJSONTyped(json, false);
}

export function ProcessingProcessPositionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessingProcessPositionList {
    if (json == null) {
        return json;
    }
    return {
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
        'meta': json['meta'] == null ? undefined : MetaListFromJSON(json['meta']),
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(ProcessingProcessPositionFromJSON)),
    };
}

export function ProcessingProcessPositionListToJSON(json: any): ProcessingProcessPositionList {
    return ProcessingProcessPositionListToJSONTyped(json, false);
}

export function ProcessingProcessPositionListToJSONTyped(value?: ProcessingProcessPositionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'context': ContextToJSON(value['context']),
        'meta': MetaListToJSON(value['meta']),
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(ProcessingProcessPositionToJSON)),
    };
}

