/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Agent } from './Agent.js';
import {
    AgentFromJSON,
    AgentFromJSONTyped,
    AgentToJSON,
    AgentToJSONTyped,
} from './Agent.js';
import type { Group } from './Group.js';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { FileList } from './FileList.js';
import {
    FileListFromJSON,
    FileListFromJSONTyped,
    FileListToJSON,
    FileListToJSONTyped,
} from './FileList.js';
import type { AttributeAbstract } from './AttributeAbstract.js';
import {
    AttributeAbstractFromJSON,
    AttributeAbstractFromJSONTyped,
    AttributeAbstractToJSON,
    AttributeAbstractToJSONTyped,
} from './AttributeAbstract.js';
import type { ProductFolder } from './ProductFolder.js';
import {
    ProductFolderFromJSON,
    ProductFolderFromJSONTyped,
    ProductFolderToJSON,
    ProductFolderToJSONTyped,
} from './ProductFolder.js';
import type { ImageList } from './ImageList.js';
import {
    ImageListFromJSON,
    ImageListFromJSONTyped,
    ImageListToJSON,
    ImageListToJSONTyped,
} from './ImageList.js';
import type { MinimumStockAbstract } from './MinimumStockAbstract.js';
import {
    MinimumStockAbstractFromJSON,
    MinimumStockAbstractFromJSONTyped,
    MinimumStockAbstractToJSON,
    MinimumStockAbstractToJSONTyped,
} from './MinimumStockAbstract.js';
import type { Uom } from './Uom.js';
import {
    UomFromJSON,
    UomFromJSONTyped,
    UomToJSON,
    UomToJSONTyped,
} from './Uom.js';
import type { Employee } from './Employee.js';
import {
    EmployeeFromJSON,
    EmployeeFromJSONTyped,
    EmployeeToJSON,
    EmployeeToJSONTyped,
} from './Employee.js';
import type { Price } from './Price.js';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price.js';
import type { ProductAlcoholic } from './ProductAlcoholic.js';
import {
    ProductAlcoholicFromJSON,
    ProductAlcoholicFromJSONTyped,
    ProductAlcoholicToJSON,
    ProductAlcoholicToJSONTyped,
} from './ProductAlcoholic.js';
import type { Barcode } from './Barcode.js';
import {
    BarcodeFromJSON,
    BarcodeFromJSONTyped,
    BarcodeToJSON,
    BarcodeToJSONTyped,
} from './Barcode.js';
import type { Country } from './Country.js';
import {
    CountryFromJSON,
    CountryFromJSONTyped,
    CountryToJSON,
    CountryToJSONTyped,
} from './Country.js';
import type { SalePrice } from './SalePrice.js';
import {
    SalePriceFromJSON,
    SalePriceFromJSONTyped,
    SalePriceToJSON,
    SalePriceToJSONTyped,
} from './SalePrice.js';
import type { Pack } from './Pack.js';
import {
    PackFromJSON,
    PackFromJSONTyped,
    PackToJSON,
    PackToJSONTyped,
} from './Pack.js';

import * as ProductPolymorphicParent from './ProductMarker.js';
/**
 * 
 * @export
 * @interface Product
 */
export interface ProductOwn {
    /**
     * 
     * @type {Meta}
     * @memberof Product
     */
    meta?: Meta;
    /**
     * ID товара
     * @type {string}
     * @memberof Product
     */
    readonly id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof Product
     */
    readonly accountId?: string;
    /**
     * 
     * @type {ProductAlcoholic}
     * @memberof Product
     */
    alcoholic?: ProductAlcoholic;
    /**
     * Добавлен ли товар в архив
     * @type {boolean}
     * @memberof Product
     */
    archived?: boolean;
    /**
     * Признак товара, как табачной продукции
     * @type {boolean}
     * @memberof Product
     */
    readonly tobacco?: boolean;
    /**
     * Наименование товара
     * @type {string}
     * @memberof Product
     */
    name?: string;
    /**
     * Код товара
     * @type {string}
     * @memberof Product
     */
    code?: string;
    /**
     * Внешний код товара
     * @type {string}
     * @memberof Product
     */
    externalCode?: string;
    /**
     * Наименование группы, в которую входит товар
     * @type {string}
     * @memberof Product
     */
    readonly pathName?: string;
    /**
     * Артикул
     * @type {string}
     * @memberof Product
     */
    article?: string;
    /**
     * Описание Товара
     * @type {string}
     * @memberof Product
     */
    description?: string | null;
    /**
     * НДС %
     * @type {number}
     * @memberof Product
     */
    vat?: number;
    /**
     * Включен ли НДС для товара
     * @type {boolean}
     * @memberof Product
     */
    vatEnabled?: boolean;
    /**
     * Используется ли ставка НДС родительской группы
     * @type {boolean}
     * @memberof Product
     */
    useParentVat?: boolean;
    /**
     * Реальный НДС %
     * @type {number}
     * @memberof Product
     */
    readonly effectiveVat?: number;
    /**
     * Дополнительный признак для определения разграничения реального НДС
     * @type {boolean}
     * @memberof Product
     */
    readonly effectiveVatEnabled?: boolean;
    /**
     * Признак запрета скидок
     * @type {boolean}
     * @memberof Product
     */
    discountProhibited?: boolean;
    /**
     * Количество модификаций у данного товара
     * @type {number}
     * @memberof Product
     */
    readonly variantsCount?: number;
    /**
     * Учет по серийным номерам
     * @type {boolean}
     * @memberof Product
     */
    isSerialTrackable?: boolean;
    /**
     * Общий доступ
     * @type {boolean}
     * @memberof Product
     */
    shared?: boolean;
    /**
     * 
     * @type {Group}
     * @memberof Product
     */
    group?: Group;
    /**
     * Метаданные владельца (Сотрудника)
     * @type {Employee}
     * @memberof Product
     */
    owner?: Employee | null;
    /**
     * Момент последнего обновления сущности
     * @type {string}
     * @memberof Product
     */
    readonly updated?: string;
    /**
     * Вес
     * @type {number}
     * @memberof Product
     */
    weight?: number;
    /**
     * Объем
     * @type {number}
     * @memberof Product
     */
    volume?: number;
    /**
     * 
     * @type {Price}
     * @memberof Product
     */
    buyPrice?: Price;
    /**
     * Цены продажи
     * @type {Array<SalePrice>}
     * @memberof Product
     */
    salePrices?: Array<SalePrice> | null;
    /**
     * Метаданные контрагента или юрлица
     * @type {Agent}
     * @memberof Product
     */
    supplier?: Agent;
    /**
     * Метаданные Страны
     * @type {Country}
     * @memberof Product
     */
    country?: Country | null;
    /**
     * Метаданные единиц измерения
     * @type {Uom}
     * @memberof Product
     */
    uom?: Uom | null;
    /**
     * Метаданные группы Товара
     * @type {ProductFolder}
     * @memberof Product
     */
    productFolder?: ProductFolder | null;
    /**
     * Массив изображений
     * @type {ImageList}
     * @memberof Product
     */
    images?: ImageList | null;
    /**
     * Метаданные массива Файлов
     * @type {FileList}
     * @memberof Product
     */
    files?: FileList;
    /**
     * Штрихкоды Товара
     * @type {Array<Barcode>}
     * @memberof Product
     */
    barcodes?: Array<Barcode> | null;
    /**
     * Упаковки товара
     * @type {Array<Pack>}
     * @memberof Product
     */
    packs?: Array<Pack> | null;
    /**
     * Тип маркируемой продукции. Известные значения описаны в TrackingType
     * @type {string}
     * @memberof Product
     */
    trackingType?: string;
    /**
     * Код ТН ВЭД
     * @type {string}
     * @memberof Product
     */
    tnved?: string;
    /**
     * Признак предмета расчета. Известные значения описаны в PaymentItemType
     * @type {string}
     * @memberof Product
     */
    paymentItemType?: string;
    /**
     * Код системы налогообложения. Известные значения описаны в TaxSystem
     * @type {string}
     * @memberof Product
     */
    taxSystem?: string;
    /**
     * Дополнительные поля
     * @type {Array<AttributeAbstract>}
     * @memberof Product
     */
    attributes?: Array<AttributeAbstract> | null;
    /**
     * Неснижаемый остаток. Не выводится по умолчанию.
     * Для получения передайте параметр `?fields=minimumStock`.
     * 
     * @type {MinimumStockAbstract}
     * @memberof Product
     */
    minimumStock?: MinimumStockAbstract | null;
    /**
     * 
     * @type {Price}
     * @memberof Product
     */
    minPrice?: Price;
    /**
     * Поле, показывающее является ли товар весовым
     * @type {boolean}
     * @memberof Product
     */
    weighed?: boolean;
    /**
     * Поле, показывающее является ли товар разливным
     * @type {boolean}
     * @memberof Product
     */
    onTap?: boolean;
    /**
     * Управление состоянием частичного выбытия маркированного товара
     * @type {boolean}
     * @memberof Product
     */
    partialDisposal?: boolean;
    /**
     * Серийные номера
     * @type {Array<string>}
     * @memberof Product
     */
    things?: Array<string> | null;
    /**
     * ID синхронизации
     * @type {string}
     * @memberof Product
     */
    syncId?: string;
    /**
     * Код вида номенклатурной классификации медицинских средств индивидуальной защиты. Известные значения описаны в PpeType
     * @type {string}
     * @memberof Product
     */
    ppeType?: string;
}
export type Product = ProductOwn & ProductPolymorphicParent.ProductMarker;


/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): value is Product {
    return true;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if (json == null) {
        return json;
    }
    return {
        ...ProductPolymorphicParent.ProductMarkerFromJSONTyped(json, true),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'alcoholic': json['alcoholic'] == null ? undefined : ProductAlcoholicFromJSON(json['alcoholic']),
        'archived': json['archived'] == null ? undefined : json['archived'],
        'tobacco': json['tobacco'] == null ? undefined : json['tobacco'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'externalCode': json['externalCode'] == null ? undefined : json['externalCode'],
        'pathName': json['pathName'] == null ? undefined : json['pathName'],
        'article': json['article'] == null ? undefined : json['article'],
        'description': json['description'] == null ? undefined : json['description'],
        'vat': json['vat'] == null ? undefined : json['vat'],
        'vatEnabled': json['vatEnabled'] == null ? undefined : json['vatEnabled'],
        'useParentVat': json['useParentVat'] == null ? undefined : json['useParentVat'],
        'effectiveVat': json['effectiveVat'] == null ? undefined : json['effectiveVat'],
        'effectiveVatEnabled': json['effectiveVatEnabled'] == null ? undefined : json['effectiveVatEnabled'],
        'discountProhibited': json['discountProhibited'] == null ? undefined : json['discountProhibited'],
        'variantsCount': json['variantsCount'] == null ? undefined : json['variantsCount'],
        'isSerialTrackable': json['isSerialTrackable'] == null ? undefined : json['isSerialTrackable'],
        'shared': json['shared'] == null ? undefined : json['shared'],
        'group': json['group'] == null ? undefined : GroupFromJSON(json['group']),
        'owner': json['owner'] == null ? undefined : EmployeeFromJSON(json['owner']),
        'updated': json['updated'] == null ? undefined : json['updated'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'volume': json['volume'] == null ? undefined : json['volume'],
        'buyPrice': json['buyPrice'] == null ? undefined : PriceFromJSON(json['buyPrice']),
        'salePrices': json['salePrices'] == null ? undefined : ((json['salePrices'] as Array<any>).map(SalePriceFromJSON)),
        'supplier': json['supplier'] == null ? undefined : AgentFromJSON(json['supplier']),
        'country': json['country'] == null ? undefined : CountryFromJSON(json['country']),
        'uom': json['uom'] == null ? undefined : UomFromJSON(json['uom']),
        'productFolder': json['productFolder'] == null ? undefined : ProductFolderFromJSON(json['productFolder']),
        'images': json['images'] == null ? undefined : ImageListFromJSON(json['images']),
        'files': json['files'] == null ? undefined : FileListFromJSON(json['files']),
        'barcodes': json['barcodes'] == null ? undefined : ((json['barcodes'] as Array<any>).map(BarcodeFromJSON)),
        'packs': json['packs'] == null ? undefined : ((json['packs'] as Array<any>).map(PackFromJSON)),
        'trackingType': json['trackingType'] == null ? undefined : json['trackingType'],
        'tnved': json['tnved'] == null ? undefined : json['tnved'],
        'paymentItemType': json['paymentItemType'] == null ? undefined : json['paymentItemType'],
        'taxSystem': json['taxSystem'] == null ? undefined : json['taxSystem'],
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(AttributeAbstractFromJSON)),
        'minimumStock': json['minimumStock'] == null ? undefined : MinimumStockAbstractFromJSON(json['minimumStock']),
        'minPrice': json['minPrice'] == null ? undefined : PriceFromJSON(json['minPrice']),
        'weighed': json['weighed'] == null ? undefined : json['weighed'],
        'onTap': json['onTap'] == null ? undefined : json['onTap'],
        'partialDisposal': json['partialDisposal'] == null ? undefined : json['partialDisposal'],
        'things': json['things'] == null ? undefined : json['things'],
        'syncId': json['syncId'] == null ? undefined : json['syncId'],
        'ppeType': json['ppeType'] == null ? undefined : json['ppeType'],
    };
}

export function ProductToJSON(json: any): Product {
    return ProductToJSONTyped(json, false);
}

export function ProductToJSONTyped(value?: Omit<Product, 'id'|'accountId'|'tobacco'|'pathName'|'effectiveVat'|'effectiveVatEnabled'|'variantsCount'|'updated'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...ProductPolymorphicParent.ProductMarkerToJSONTyped(value as any, true),
        'meta': MetaToJSON(value['meta']),
        'alcoholic': ProductAlcoholicToJSON(value['alcoholic']),
        'archived': value['archived'],
        'name': value['name'],
        'code': value['code'],
        'externalCode': value['externalCode'],
        'article': value['article'],
        'description': value['description'],
        'vat': value['vat'],
        'vatEnabled': value['vatEnabled'],
        'useParentVat': value['useParentVat'],
        'discountProhibited': value['discountProhibited'],
        'isSerialTrackable': value['isSerialTrackable'],
        'shared': value['shared'],
        'group': GroupToJSON(value['group']),
        'owner': EmployeeToJSON(value['owner']),
        'weight': value['weight'],
        'volume': value['volume'],
        'buyPrice': PriceToJSON(value['buyPrice']),
        'salePrices': value['salePrices'] == null ? undefined : ((value['salePrices'] as Array<any>).map(SalePriceToJSON)),
        'supplier': AgentToJSON(value['supplier']),
        'country': CountryToJSON(value['country']),
        'uom': UomToJSON(value['uom']),
        'productFolder': ProductFolderToJSON(value['productFolder']),
        'images': ImageListToJSON(value['images']),
        'files': FileListToJSON(value['files']),
        'barcodes': value['barcodes'] == null ? undefined : ((value['barcodes'] as Array<any>).map(BarcodeToJSON)),
        'packs': value['packs'] == null ? undefined : ((value['packs'] as Array<any>).map(PackToJSON)),
        'trackingType': value['trackingType'],
        'tnved': value['tnved'],
        'paymentItemType': value['paymentItemType'],
        'taxSystem': value['taxSystem'],
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(AttributeAbstractToJSON)),
        'minimumStock': MinimumStockAbstractToJSON(value['minimumStock']),
        'minPrice': PriceToJSON(value['minPrice']),
        'weighed': value['weighed'],
        'onTap': value['onTap'],
        'partialDisposal': value['partialDisposal'],
        'things': value['things'],
        'syncId': value['syncId'],
        'ppeType': value['ppeType'],
    };
}

