/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Account } from './Account.js';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account.js';
import type { Agent } from './Agent.js';
import {
    AgentFromJSON,
    AgentFromJSONTyped,
    AgentToJSON,
    AgentToJSONTyped,
} from './Agent.js';
import type { Group } from './Group.js';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Organization } from './Organization.js';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
    OrganizationToJSONTyped,
} from './Organization.js';
import type { FileList } from './FileList.js';
import {
    FileListFromJSON,
    FileListFromJSONTyped,
    FileListToJSON,
    FileListToJSONTyped,
} from './FileList.js';
import type { AttributeAbstract } from './AttributeAbstract.js';
import {
    AttributeAbstractFromJSON,
    AttributeAbstractFromJSONTyped,
    AttributeAbstractToJSON,
    AttributeAbstractToJSONTyped,
} from './AttributeAbstract.js';
import type { CustomerOrder } from './CustomerOrder.js';
import {
    CustomerOrderFromJSON,
    CustomerOrderFromJSONTyped,
    CustomerOrderToJSON,
    CustomerOrderToJSONTyped,
} from './CustomerOrder.js';
import type { Supply } from './Supply.js';
import {
    SupplyFromJSON,
    SupplyFromJSONTyped,
    SupplyToJSON,
    SupplyToJSONTyped,
} from './Supply.js';
import type { Store } from './Store.js';
import {
    StoreFromJSON,
    StoreFromJSONTyped,
    StoreToJSON,
    StoreToJSONTyped,
} from './Store.js';
import type { InternalOrder } from './InternalOrder.js';
import {
    InternalOrderFromJSON,
    InternalOrderFromJSONTyped,
    InternalOrderToJSON,
    InternalOrderToJSONTyped,
} from './InternalOrder.js';
import type { Project } from './Project.js';
import {
    ProjectFromJSON,
    ProjectFromJSONTyped,
    ProjectToJSON,
    ProjectToJSONTyped,
} from './Project.js';
import type { Employee } from './Employee.js';
import {
    EmployeeFromJSON,
    EmployeeFromJSONTyped,
    EmployeeToJSON,
    EmployeeToJSONTyped,
} from './Employee.js';
import type { InvoiceIn } from './InvoiceIn.js';
import {
    InvoiceInFromJSON,
    InvoiceInFromJSONTyped,
    InvoiceInToJSON,
    InvoiceInToJSONTyped,
} from './InvoiceIn.js';
import type { State } from './State.js';
import {
    StateFromJSON,
    StateFromJSONTyped,
    StateToJSON,
    StateToJSONTyped,
} from './State.js';
import type { PurchaseOrderRate } from './PurchaseOrderRate.js';
import {
    PurchaseOrderRateFromJSON,
    PurchaseOrderRateFromJSONTyped,
    PurchaseOrderRateToJSON,
    PurchaseOrderRateToJSONTyped,
} from './PurchaseOrderRate.js';
import type { ProductionTask } from './ProductionTask.js';
import {
    ProductionTaskFromJSON,
    ProductionTaskFromJSONTyped,
    ProductionTaskToJSON,
    ProductionTaskToJSONTyped,
} from './ProductionTask.js';
import type { PurchaseOrderPositionList } from './PurchaseOrderPositionList.js';
import {
    PurchaseOrderPositionListFromJSON,
    PurchaseOrderPositionListFromJSONTyped,
    PurchaseOrderPositionListToJSON,
    PurchaseOrderPositionListToJSONTyped,
} from './PurchaseOrderPositionList.js';
import type { Contract } from './Contract.js';
import {
    ContractFromJSON,
    ContractFromJSONTyped,
    ContractToJSON,
    ContractToJSONTyped,
} from './Contract.js';
import type { SalesReturnPaymentsInner } from './SalesReturnPaymentsInner.js';
import {
    SalesReturnPaymentsInnerFromJSON,
    SalesReturnPaymentsInnerFromJSONTyped,
    SalesReturnPaymentsInnerToJSON,
    SalesReturnPaymentsInnerToJSONTyped,
} from './SalesReturnPaymentsInner.js';

import * as PurchaseOrderPolymorphicParent from './EntityWithMeta.js';
/**
 * Заказ поставщику
 * @export
 * @interface PurchaseOrder
 */
export interface PurchaseOrderOwn {
    /**
     * 
     * @type {Meta}
     * @memberof PurchaseOrder
     */
    meta?: Meta;
    /**
     * ID Заказа поставщику
     * @type {string}
     * @memberof PurchaseOrder
     */
    readonly id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof PurchaseOrder
     */
    readonly accountId?: string;
    /**
     * Наименование Заказа поставщику
     * @type {string}
     * @memberof PurchaseOrder
     */
    name?: string;
    /**
     * Код Заказа поставщику
     * @type {string}
     * @memberof PurchaseOrder
     */
    code?: string;
    /**
     * Внешний код Заказа поставщику
     * @type {string}
     * @memberof PurchaseOrder
     */
    externalCode?: string;
    /**
     * ID синхронизации
     * @type {string}
     * @memberof PurchaseOrder
     */
    syncId?: string;
    /**
     * Комментарий Заказа поставщику
     * @type {string}
     * @memberof PurchaseOrder
     */
    description?: string | null;
    /**
     * Дата создания
     * @type {string}
     * @memberof PurchaseOrder
     */
    readonly created?: string;
    /**
     * Момент последнего удаления Заказа поставщику
     * @type {string}
     * @memberof PurchaseOrder
     */
    readonly deleted?: string;
    /**
     * Момент последнего обновления Заказа поставщику
     * @type {string}
     * @memberof PurchaseOrder
     */
    readonly updated?: string;
    /**
     * Дата документа
     * @type {string}
     * @memberof PurchaseOrder
     */
    moment?: string;
    /**
     * Планируемая дата отгрузки
     * @type {string}
     * @memberof PurchaseOrder
     */
    deliveryPlannedMoment?: string;
    /**
     * Отметка о проведении
     * @type {boolean}
     * @memberof PurchaseOrder
     */
    applicable?: boolean;
    /**
     * Напечатан ли документ
     * @type {boolean}
     * @memberof PurchaseOrder
     */
    readonly printed?: boolean;
    /**
     * Опубликован ли документ
     * @type {boolean}
     * @memberof PurchaseOrder
     */
    readonly published?: boolean;
    /**
     * Общий доступ
     * @type {boolean}
     * @memberof PurchaseOrder
     */
    shared?: boolean;
    /**
     * Учитывается ли НДС
     * @type {boolean}
     * @memberof PurchaseOrder
     */
    vatEnabled?: boolean;
    /**
     * Включен ли НДС в цену
     * @type {boolean}
     * @memberof PurchaseOrder
     */
    vatIncluded?: boolean;
    /**
     * Сумма НДС
     * @type {number}
     * @memberof PurchaseOrder
     */
    readonly vatSum?: number;
    /**
     * Сумма Заказа поставщику в установленной валюте
     * @type {number}
     * @memberof PurchaseOrder
     */
    readonly sum?: number;
    /**
     * Сумма входящих платежей по Заказу
     * @type {number}
     * @memberof PurchaseOrder
     */
    readonly payedSum?: number;
    /**
     * Сумма принятого
     * @type {number}
     * @memberof PurchaseOrder
     */
    readonly shippedSum?: number;
    /**
     * Сумма счетов поставщику
     * @type {number}
     * @memberof PurchaseOrder
     */
    readonly invoicedSum?: number;
    /**
     * Сумма товаров в пути
     * @type {number}
     * @memberof PurchaseOrder
     */
    readonly waitSum?: number;
    /**
     * 
     * @type {Organization}
     * @memberof PurchaseOrder
     */
    organization?: Organization;
    /**
     * Метаданные счета юрлица
     * @type {Account}
     * @memberof PurchaseOrder
     */
    organizationAccount?: Account | null;
    /**
     * Метаданные контрагента или юрлица
     * @type {Agent}
     * @memberof PurchaseOrder
     */
    agent?: Agent;
    /**
     * Метаданные счета контрагента
     * @type {Account}
     * @memberof PurchaseOrder
     */
    agentAccount?: Account | null;
    /**
     * Метаданные склада
     * @type {Store}
     * @memberof PurchaseOrder
     */
    store?: Store | null;
    /**
     * Метаданные статуса заказа
     * @type {State}
     * @memberof PurchaseOrder
     */
    state?: State | null;
    /**
     * Метаданные договора
     * @type {Contract}
     * @memberof PurchaseOrder
     */
    contract?: Contract | null;
    /**
     * Метаданные проекта
     * @type {Project}
     * @memberof PurchaseOrder
     */
    project?: Project | null;
    /**
     * Владелец (Сотрудник)
     * @type {Employee}
     * @memberof PurchaseOrder
     */
    owner?: Employee | null;
    /**
     * 
     * @type {Group}
     * @memberof PurchaseOrder
     */
    group?: Group;
    /**
     * Коллекция метаданных доп. полей
     * @type {Array<AttributeAbstract>}
     * @memberof PurchaseOrder
     */
    attributes?: Array<AttributeAbstract> | null;
    /**
     * Метаданные массива Файлов
     * @type {FileList}
     * @memberof PurchaseOrder
     */
    files?: FileList | null;
    /**
     * 
     * @type {PurchaseOrderRate}
     * @memberof PurchaseOrder
     */
    rate?: PurchaseOrderRate;
    /**
     * 
     * @type {PurchaseOrderPositionList}
     * @memberof PurchaseOrder
     */
    positions?: PurchaseOrderPositionList;
    /**
     * Внутренний заказ, связанный с заказом поставщику
     * @type {InternalOrder}
     * @memberof PurchaseOrder
     */
    internalOrder?: InternalOrder | null;
    /**
     * Массив ссылок на связанные заказы покупателей
     * @type {Array<CustomerOrder>}
     * @memberof PurchaseOrder
     */
    customerOrders?: Array<CustomerOrder> | null;
    /**
     * Массив ссылок на связанные счета поставщиков
     * @type {Array<InvoiceIn>}
     * @memberof PurchaseOrder
     */
    invoicesIn?: Array<InvoiceIn> | null;
    /**
     * Массив ссылок на связанные приемки
     * @type {Array<Supply>}
     * @memberof PurchaseOrder
     */
    supplies?: Array<Supply> | null;
    /**
     * Массив ссылок на связанные платежи
     * @type {Array<SalesReturnPaymentsInner>}
     * @memberof PurchaseOrder
     */
    payments?: Array<SalesReturnPaymentsInner> | null;
    /**
     * Массив ссылок на связанные производственные задания
     * @type {Array<ProductionTask>}
     * @memberof PurchaseOrder
     */
    productionTasks?: Array<ProductionTask> | null;
}
export type PurchaseOrder = PurchaseOrderOwn & PurchaseOrderPolymorphicParent.EntityWithMeta;


/**
 * Check if a given object implements the PurchaseOrder interface.
 */
export function instanceOfPurchaseOrder(value: object): value is PurchaseOrder {
    return true;
}

export function PurchaseOrderFromJSON(json: any): PurchaseOrder {
    return PurchaseOrderFromJSONTyped(json, false);
}

export function PurchaseOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseOrder {
    if (json == null) {
        return json;
    }
    return {
        ...PurchaseOrderPolymorphicParent.EntityWithMetaFromJSONTyped(json, true),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'externalCode': json['externalCode'] == null ? undefined : json['externalCode'],
        'syncId': json['syncId'] == null ? undefined : json['syncId'],
        'description': json['description'] == null ? undefined : json['description'],
        'created': json['created'] == null ? undefined : json['created'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'updated': json['updated'] == null ? undefined : json['updated'],
        'moment': json['moment'] == null ? undefined : json['moment'],
        'deliveryPlannedMoment': json['deliveryPlannedMoment'] == null ? undefined : json['deliveryPlannedMoment'],
        'applicable': json['applicable'] == null ? undefined : json['applicable'],
        'printed': json['printed'] == null ? undefined : json['printed'],
        'published': json['published'] == null ? undefined : json['published'],
        'shared': json['shared'] == null ? undefined : json['shared'],
        'vatEnabled': json['vatEnabled'] == null ? undefined : json['vatEnabled'],
        'vatIncluded': json['vatIncluded'] == null ? undefined : json['vatIncluded'],
        'vatSum': json['vatSum'] == null ? undefined : json['vatSum'],
        'sum': json['sum'] == null ? undefined : json['sum'],
        'payedSum': json['payedSum'] == null ? undefined : json['payedSum'],
        'shippedSum': json['shippedSum'] == null ? undefined : json['shippedSum'],
        'invoicedSum': json['invoicedSum'] == null ? undefined : json['invoicedSum'],
        'waitSum': json['waitSum'] == null ? undefined : json['waitSum'],
        'organization': json['organization'] == null ? undefined : OrganizationFromJSON(json['organization']),
        'organizationAccount': json['organizationAccount'] == null ? undefined : AccountFromJSON(json['organizationAccount']),
        'agent': json['agent'] == null ? undefined : AgentFromJSON(json['agent']),
        'agentAccount': json['agentAccount'] == null ? undefined : AccountFromJSON(json['agentAccount']),
        'store': json['store'] == null ? undefined : StoreFromJSON(json['store']),
        'state': json['state'] == null ? undefined : StateFromJSON(json['state']),
        'contract': json['contract'] == null ? undefined : ContractFromJSON(json['contract']),
        'project': json['project'] == null ? undefined : ProjectFromJSON(json['project']),
        'owner': json['owner'] == null ? undefined : EmployeeFromJSON(json['owner']),
        'group': json['group'] == null ? undefined : GroupFromJSON(json['group']),
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(AttributeAbstractFromJSON)),
        'files': json['files'] == null ? undefined : FileListFromJSON(json['files']),
        'rate': json['rate'] == null ? undefined : PurchaseOrderRateFromJSON(json['rate']),
        'positions': json['positions'] == null ? undefined : PurchaseOrderPositionListFromJSON(json['positions']),
        'internalOrder': json['internalOrder'] == null ? undefined : InternalOrderFromJSON(json['internalOrder']),
        'customerOrders': json['customerOrders'] == null ? undefined : ((json['customerOrders'] as Array<any>).map(CustomerOrderFromJSON)),
        'invoicesIn': json['invoicesIn'] == null ? undefined : ((json['invoicesIn'] as Array<any>).map(InvoiceInFromJSON)),
        'supplies': json['supplies'] == null ? undefined : ((json['supplies'] as Array<any>).map(SupplyFromJSON)),
        'payments': json['payments'] == null ? undefined : ((json['payments'] as Array<any>).map(SalesReturnPaymentsInnerFromJSON)),
        'productionTasks': json['productionTasks'] == null ? undefined : ((json['productionTasks'] as Array<any>).map(ProductionTaskFromJSON)),
    };
}

export function PurchaseOrderToJSON(json: any): PurchaseOrder {
    return PurchaseOrderToJSONTyped(json, false);
}

export function PurchaseOrderToJSONTyped(value?: Omit<PurchaseOrder, 'id'|'accountId'|'created'|'deleted'|'updated'|'printed'|'published'|'vatSum'|'sum'|'payedSum'|'shippedSum'|'invoicedSum'|'waitSum'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...PurchaseOrderPolymorphicParent.EntityWithMetaToJSONTyped(value as any, true),
        'meta': MetaToJSON(value['meta']),
        'name': value['name'],
        'code': value['code'],
        'externalCode': value['externalCode'],
        'syncId': value['syncId'],
        'description': value['description'],
        'moment': value['moment'],
        'deliveryPlannedMoment': value['deliveryPlannedMoment'],
        'applicable': value['applicable'],
        'shared': value['shared'],
        'vatEnabled': value['vatEnabled'],
        'vatIncluded': value['vatIncluded'],
        'organization': OrganizationToJSON(value['organization']),
        'organizationAccount': AccountToJSON(value['organizationAccount']),
        'agent': AgentToJSON(value['agent']),
        'agentAccount': AccountToJSON(value['agentAccount']),
        'store': StoreToJSON(value['store']),
        'state': StateToJSON(value['state']),
        'contract': ContractToJSON(value['contract']),
        'project': ProjectToJSON(value['project']),
        'owner': EmployeeToJSON(value['owner']),
        'group': GroupToJSON(value['group']),
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(AttributeAbstractToJSON)),
        'files': FileListToJSON(value['files']),
        'rate': PurchaseOrderRateToJSON(value['rate']),
        'positions': PurchaseOrderPositionListToJSON(value['positions']),
        'internalOrder': InternalOrderToJSON(value['internalOrder']),
        'customerOrders': value['customerOrders'] == null ? undefined : ((value['customerOrders'] as Array<any>).map(CustomerOrderToJSON)),
        'invoicesIn': value['invoicesIn'] == null ? undefined : ((value['invoicesIn'] as Array<any>).map(InvoiceInToJSON)),
        'supplies': value['supplies'] == null ? undefined : ((value['supplies'] as Array<any>).map(SupplyToJSON)),
        'payments': value['payments'] == null ? undefined : ((value['payments'] as Array<any>).map(SalesReturnPaymentsInnerToJSON)),
        'productionTasks': value['productionTasks'] == null ? undefined : ((value['productionTasks'] as Array<any>).map(ProductionTaskToJSON)),
    };
}

