/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';

/**
 * Регион
 * @export
 * @interface Region
 */
export interface Region {
    /**
     * 
     * @type {Meta}
     * @memberof Region
     */
    meta?: Meta;
    /**
     * ID Региона
     * @type {string}
     * @memberof Region
     */
    readonly id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof Region
     */
    readonly accountId?: string;
    /**
     * Наименование Региона
     * @type {string}
     * @memberof Region
     */
    name?: string;
    /**
     * Код Региона
     * @type {string}
     * @memberof Region
     */
    code?: string;
    /**
     * Внешний код Региона
     * @type {string}
     * @memberof Region
     */
    externalCode?: string;
    /**
     * Время последнего изменения
     * @type {string}
     * @memberof Region
     */
    readonly updated?: string;
    /**
     * Версия сущности
     * @type {number}
     * @memberof Region
     */
    readonly version?: number;
}


/**
 * Check if a given object implements the Region interface.
 */
export function instanceOfRegion(value: object): value is Region {
    return true;
}

export function RegionFromJSON(json: any): Region {
    return RegionFromJSONTyped(json, false);
}

export function RegionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Region {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'externalCode': json['externalCode'] == null ? undefined : json['externalCode'],
        'updated': json['updated'] == null ? undefined : json['updated'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function RegionToJSON(json: any): Region {
    return RegionToJSONTyped(json, false);
}

export function RegionToJSONTyped(value?: Omit<Region, 'id'|'accountId'|'updated'|'version'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaToJSON(value['meta']),
        'name': value['name'],
        'code': value['code'],
        'externalCode': value['externalCode'],
    };
}

