/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Counterparty } from './Counterparty.js';
import {
    CounterpartyFromJSON,
    CounterpartyFromJSONTyped,
    CounterpartyToJSON,
    CounterpartyToJSONTyped,
} from './Counterparty.js';

/**
 * Строка отчета «Показатели контрагентов»
 * @export
 * @interface ReportCounterparty
 */
export interface ReportCounterparty {
    /**
     * 
     * @type {Meta}
     * @memberof ReportCounterparty
     */
    meta?: Meta;
    /**
     * 
     * @type {Counterparty}
     * @memberof ReportCounterparty
     */
    counterparty?: Counterparty;
    /**
     * Дата первой продажи
     * @type {string}
     * @memberof ReportCounterparty
     */
    firstDemandDate?: string | null;
    /**
     * Дата последней продажи
     * @type {string}
     * @memberof ReportCounterparty
     */
    lastDemandDate?: string | null;
    /**
     * Количество продаж
     * @type {number}
     * @memberof ReportCounterparty
     */
    demandsCount?: number;
    /**
     * Сумма продаж
     * @type {number}
     * @memberof ReportCounterparty
     */
    demandsSum?: number;
    /**
     * Средний чек
     * @type {number}
     * @memberof ReportCounterparty
     */
    averageReceipt?: number;
    /**
     * Количество возвратов
     * @type {number}
     * @memberof ReportCounterparty
     */
    returnsCount?: number;
    /**
     * Сумма возвратов
     * @type {number}
     * @memberof ReportCounterparty
     */
    returnsSum?: number;
    /**
     * Сумма скидок
     * @type {number}
     * @memberof ReportCounterparty
     */
    discountsSum?: number;
    /**
     * Баланс
     * @type {number}
     * @memberof ReportCounterparty
     */
    balance?: number;
    /**
     * Баллы
     * @type {number}
     * @memberof ReportCounterparty
     */
    bonusBalance?: number;
    /**
     * Прибыль
     * @type {number}
     * @memberof ReportCounterparty
     */
    profit?: number;
    /**
     * Дата последнего события
     * @type {string}
     * @memberof ReportCounterparty
     */
    lastEventDate?: string | null;
    /**
     * Текст последнего события
     * @type {string}
     * @memberof ReportCounterparty
     */
    lastEventText?: string | null;
    /**
     * Момент последнего изменения контрагента
     * @type {string}
     * @memberof ReportCounterparty
     */
    updated?: string;
}


/**
 * Check if a given object implements the ReportCounterparty interface.
 */
export function instanceOfReportCounterparty(value: object): value is ReportCounterparty {
    return true;
}

export function ReportCounterpartyFromJSON(json: any): ReportCounterparty {
    return ReportCounterpartyFromJSONTyped(json, false);
}

export function ReportCounterpartyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportCounterparty {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'counterparty': json['counterparty'] == null ? undefined : CounterpartyFromJSON(json['counterparty']),
        'firstDemandDate': json['firstDemandDate'] == null ? undefined : json['firstDemandDate'],
        'lastDemandDate': json['lastDemandDate'] == null ? undefined : json['lastDemandDate'],
        'demandsCount': json['demandsCount'] == null ? undefined : json['demandsCount'],
        'demandsSum': json['demandsSum'] == null ? undefined : json['demandsSum'],
        'averageReceipt': json['averageReceipt'] == null ? undefined : json['averageReceipt'],
        'returnsCount': json['returnsCount'] == null ? undefined : json['returnsCount'],
        'returnsSum': json['returnsSum'] == null ? undefined : json['returnsSum'],
        'discountsSum': json['discountsSum'] == null ? undefined : json['discountsSum'],
        'balance': json['balance'] == null ? undefined : json['balance'],
        'bonusBalance': json['bonusBalance'] == null ? undefined : json['bonusBalance'],
        'profit': json['profit'] == null ? undefined : json['profit'],
        'lastEventDate': json['lastEventDate'] == null ? undefined : json['lastEventDate'],
        'lastEventText': json['lastEventText'] == null ? undefined : json['lastEventText'],
        'updated': json['updated'] == null ? undefined : json['updated'],
    };
}

export function ReportCounterpartyToJSON(json: any): ReportCounterparty {
    return ReportCounterpartyToJSONTyped(json, false);
}

export function ReportCounterpartyToJSONTyped(value?: ReportCounterparty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaToJSON(value['meta']),
        'counterparty': CounterpartyToJSON(value['counterparty']),
        'firstDemandDate': value['firstDemandDate'],
        'lastDemandDate': value['lastDemandDate'],
        'demandsCount': value['demandsCount'],
        'demandsSum': value['demandsSum'],
        'averageReceipt': value['averageReceipt'],
        'returnsCount': value['returnsCount'],
        'returnsSum': value['returnsSum'],
        'discountsSum': value['discountsSum'],
        'balance': value['balance'],
        'bonusBalance': value['bonusBalance'],
        'profit': value['profit'],
        'lastEventDate': value['lastEventDate'],
        'lastEventText': value['lastEventText'],
        'updated': value['updated'],
    };
}

