/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ReportTurnoverAssortment } from './ReportTurnoverAssortment.js';
import {
    ReportTurnoverAssortmentFromJSON,
    ReportTurnoverAssortmentFromJSONTyped,
    ReportTurnoverAssortmentToJSON,
    ReportTurnoverAssortmentToJSONTyped,
} from './ReportTurnoverAssortment.js';
import type { ReportTurnoverIndicators } from './ReportTurnoverIndicators.js';
import {
    ReportTurnoverIndicatorsFromJSON,
    ReportTurnoverIndicatorsFromJSONTyped,
    ReportTurnoverIndicatorsToJSON,
    ReportTurnoverIndicatorsToJSONTyped,
} from './ReportTurnoverIndicators.js';

/**
 * Строка отчета «Обороты по товарам»
 * @export
 * @interface ReportTurnover
 */
export interface ReportTurnover {
    /**
     * 
     * @type {ReportTurnoverAssortment}
     * @memberof ReportTurnover
     */
    assortment?: ReportTurnoverAssortment;
    /**
     * 
     * @type {ReportTurnoverIndicators}
     * @memberof ReportTurnover
     */
    onPeriodStart?: ReportTurnoverIndicators;
    /**
     * 
     * @type {ReportTurnoverIndicators}
     * @memberof ReportTurnover
     */
    onPeriodEnd?: ReportTurnoverIndicators;
    /**
     * 
     * @type {ReportTurnoverIndicators}
     * @memberof ReportTurnover
     */
    income?: ReportTurnoverIndicators;
    /**
     * 
     * @type {ReportTurnoverIndicators}
     * @memberof ReportTurnover
     */
    outcome?: ReportTurnoverIndicators;
}


/**
 * Check if a given object implements the ReportTurnover interface.
 */
export function instanceOfReportTurnover(value: object): value is ReportTurnover {
    return true;
}

export function ReportTurnoverFromJSON(json: any): ReportTurnover {
    return ReportTurnoverFromJSONTyped(json, false);
}

export function ReportTurnoverFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportTurnover {
    if (json == null) {
        return json;
    }
    return {
        'assortment': json['assortment'] == null ? undefined : ReportTurnoverAssortmentFromJSON(json['assortment']),
        'onPeriodStart': json['onPeriodStart'] == null ? undefined : ReportTurnoverIndicatorsFromJSON(json['onPeriodStart']),
        'onPeriodEnd': json['onPeriodEnd'] == null ? undefined : ReportTurnoverIndicatorsFromJSON(json['onPeriodEnd']),
        'income': json['income'] == null ? undefined : ReportTurnoverIndicatorsFromJSON(json['income']),
        'outcome': json['outcome'] == null ? undefined : ReportTurnoverIndicatorsFromJSON(json['outcome']),
    };
}

export function ReportTurnoverToJSON(json: any): ReportTurnover {
    return ReportTurnoverToJSONTyped(json, false);
}

export function ReportTurnoverToJSONTyped(value?: ReportTurnover | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'assortment': ReportTurnoverAssortmentToJSON(value['assortment']),
        'onPeriodStart': ReportTurnoverIndicatorsToJSON(value['onPeriodStart']),
        'onPeriodEnd': ReportTurnoverIndicatorsToJSON(value['onPeriodEnd']),
        'income': ReportTurnoverIndicatorsToJSON(value['income']),
        'outcome': ReportTurnoverIndicatorsToJSON(value['outcome']),
    };
}

