/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Context } from './Context.js';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context.js';
import type { RetailSalesReturn } from './RetailSalesReturn.js';
import {
    RetailSalesReturnFromJSON,
    RetailSalesReturnFromJSONTyped,
    RetailSalesReturnToJSON,
    RetailSalesReturnToJSONTyped,
} from './RetailSalesReturn.js';
import type { MetaList } from './MetaList.js';
import {
    MetaListFromJSON,
    MetaListFromJSONTyped,
    MetaListToJSON,
    MetaListToJSONTyped,
} from './MetaList.js';

/**
 * Список Розничных возвратов
 * @export
 * @interface RetailSalesReturnList
 */
export interface RetailSalesReturnList {
    /**
     * 
     * @type {Context}
     * @memberof RetailSalesReturnList
     */
    context?: Context;
    /**
     * 
     * @type {MetaList}
     * @memberof RetailSalesReturnList
     */
    meta?: MetaList;
    /**
     * Массив Розничных возвратов
     * @type {Array<RetailSalesReturn>}
     * @memberof RetailSalesReturnList
     */
    rows?: Array<RetailSalesReturn>;
}


/**
 * Check if a given object implements the RetailSalesReturnList interface.
 */
export function instanceOfRetailSalesReturnList(value: object): value is RetailSalesReturnList {
    return true;
}

export function RetailSalesReturnListFromJSON(json: any): RetailSalesReturnList {
    return RetailSalesReturnListFromJSONTyped(json, false);
}

export function RetailSalesReturnListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetailSalesReturnList {
    if (json == null) {
        return json;
    }
    return {
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
        'meta': json['meta'] == null ? undefined : MetaListFromJSON(json['meta']),
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(RetailSalesReturnFromJSON)),
    };
}

export function RetailSalesReturnListToJSON(json: any): RetailSalesReturnList {
    return RetailSalesReturnListToJSONTyped(json, false);
}

export function RetailSalesReturnListToJSONTyped(value?: RetailSalesReturnList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'context': ContextToJSON(value['context']),
        'meta': MetaListToJSON(value['meta']),
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(RetailSalesReturnToJSON)),
    };
}

