/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Context } from './Context.js';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context.js';
import type { MetaList } from './MetaList.js';
import {
    MetaListFromJSON,
    MetaListFromJSONTyped,
    MetaListToJSON,
    MetaListToJSONTyped,
} from './MetaList.js';
import type { RetailStore } from './RetailStore.js';
import {
    RetailStoreFromJSON,
    RetailStoreFromJSONTyped,
    RetailStoreToJSON,
    RetailStoreToJSONTyped,
} from './RetailStore.js';

/**
 * Список точек продаж
 * @export
 * @interface RetailStoreList
 */
export interface RetailStoreList {
    /**
     * 
     * @type {Context}
     * @memberof RetailStoreList
     */
    context?: Context;
    /**
     * 
     * @type {MetaList}
     * @memberof RetailStoreList
     */
    meta?: MetaList;
    /**
     * Массив точек продаж
     * @type {Array<RetailStore>}
     * @memberof RetailStoreList
     */
    rows?: Array<RetailStore> | null;
}


/**
 * Check if a given object implements the RetailStoreList interface.
 */
export function instanceOfRetailStoreList(value: object): value is RetailStoreList {
    return true;
}

export function RetailStoreListFromJSON(json: any): RetailStoreList {
    return RetailStoreListFromJSONTyped(json, false);
}

export function RetailStoreListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetailStoreList {
    if (json == null) {
        return json;
    }
    return {
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
        'meta': json['meta'] == null ? undefined : MetaListFromJSON(json['meta']),
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(RetailStoreFromJSON)),
    };
}

export function RetailStoreListToJSON(json: any): RetailStoreList {
    return RetailStoreListToJSONTyped(json, false);
}

export function RetailStoreListToJSONTyped(value?: RetailStoreList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'context': ContextToJSON(value['context']),
        'meta': MetaListToJSON(value['meta']),
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(RetailStoreToJSON)),
    };
}

