/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';

import * as RetailShiftOperationPrepaymentPolymorphicParent from './RetailShiftOperation.js';
/**
 * Предоплата
 * @export
 * @interface RetailShiftOperationPrepayment
 */
export interface RetailShiftOperationPrepaymentOwn {
    /**
     * 
     * @type {Meta}
     * @memberof RetailShiftOperationPrepayment
     */
    meta?: Meta;
    /**
     * ID Предоплаты
     * @type {string}
     * @memberof RetailShiftOperationPrepayment
     */
    readonly id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof RetailShiftOperationPrepayment
     */
    readonly accountId?: string;
    /**
     * Наименование Предоплаты
     * @type {string}
     * @memberof RetailShiftOperationPrepayment
     */
    name?: string;
    /**
     * Код Предоплаты
     * @type {string}
     * @memberof RetailShiftOperationPrepayment
     */
    code?: string;
    /**
     * Внешний код Предоплаты
     * @type {string}
     * @memberof RetailShiftOperationPrepayment
     */
    externalCode?: string;
    /**
     * ID синхронизации
     * @type {string}
     * @memberof RetailShiftOperationPrepayment
     */
    syncId?: string;
    /**
     * Комментарий Предоплаты
     * @type {string}
     * @memberof RetailShiftOperationPrepayment
     */
    description?: string | null;
    /**
     * Дата создания
     * @type {string}
     * @memberof RetailShiftOperationPrepayment
     */
    readonly created?: string;
    /**
     * Момент последнего удаления Предоплаты
     * @type {string}
     * @memberof RetailShiftOperationPrepayment
     */
    readonly deleted?: string;
    /**
     * Момент последнего обновления Предоплаты
     * @type {string}
     * @memberof RetailShiftOperationPrepayment
     */
    readonly updated?: string;
    /**
     * Дата документа
     * @type {string}
     * @memberof RetailShiftOperationPrepayment
     */
    moment?: string;
}
export type RetailShiftOperationPrepayment = RetailShiftOperationPrepaymentOwn & RetailShiftOperationPrepaymentPolymorphicParent.RetailShiftOperation;


/**
 * Check if a given object implements the RetailShiftOperationPrepayment interface.
 */
export function instanceOfRetailShiftOperationPrepayment(value: object): value is RetailShiftOperationPrepayment {
    return true;
}

export function RetailShiftOperationPrepaymentFromJSON(json: any): RetailShiftOperationPrepayment {
    return RetailShiftOperationPrepaymentFromJSONTyped(json, false);
}

export function RetailShiftOperationPrepaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetailShiftOperationPrepayment {
    if (json == null) {
        return json;
    }
    return {
        ...RetailShiftOperationPrepaymentPolymorphicParent.RetailShiftOperationFromJSONTyped(json, true),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'externalCode': json['externalCode'] == null ? undefined : json['externalCode'],
        'syncId': json['syncId'] == null ? undefined : json['syncId'],
        'description': json['description'] == null ? undefined : json['description'],
        'created': json['created'] == null ? undefined : json['created'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'updated': json['updated'] == null ? undefined : json['updated'],
        'moment': json['moment'] == null ? undefined : json['moment'],
    };
}

export function RetailShiftOperationPrepaymentToJSON(json: any): RetailShiftOperationPrepayment {
    return RetailShiftOperationPrepaymentToJSONTyped(json, false);
}

export function RetailShiftOperationPrepaymentToJSONTyped(value?: Omit<RetailShiftOperationPrepayment, 'id'|'accountId'|'created'|'deleted'|'updated'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...RetailShiftOperationPrepaymentPolymorphicParent.RetailShiftOperationToJSONTyped(value as any, true),
        'meta': MetaToJSON(value['meta']),
        'name': value['name'],
        'code': value['code'],
        'externalCode': value['externalCode'],
        'syncId': value['syncId'],
        'description': value['description'],
        'moment': value['moment'],
    };
}

