/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Context } from './Context.js';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context.js';
import type { RetailShift } from './RetailShift.js';
import {
    RetailShiftFromJSON,
    RetailShiftFromJSONTyped,
    RetailShiftToJSON,
    RetailShiftToJSONTyped,
} from './RetailShift.js';
import type { MetaList } from './MetaList.js';
import {
    MetaListFromJSON,
    MetaListFromJSONTyped,
    MetaListToJSON,
    MetaListToJSONTyped,
} from './MetaList.js';

/**
 * Список Розничных смен
 * @export
 * @interface RetailShiftList
 */
export interface RetailShiftList {
    /**
     * 
     * @type {Context}
     * @memberof RetailShiftList
     */
    context?: Context;
    /**
     * 
     * @type {MetaList}
     * @memberof RetailShiftList
     */
    meta?: MetaList;
    /**
     * Массив Розничных смен
     * @type {Array<RetailShift>}
     * @memberof RetailShiftList
     */
    rows?: Array<RetailShift>;
}


/**
 * Check if a given object implements the RetailShiftList interface.
 */
export function instanceOfRetailShiftList(value: object): value is RetailShiftList {
    return true;
}

export function RetailShiftListFromJSON(json: any): RetailShiftList {
    return RetailShiftListFromJSONTyped(json, false);
}

export function RetailShiftListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetailShiftList {
    if (json == null) {
        return json;
    }
    return {
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
        'meta': json['meta'] == null ? undefined : MetaListFromJSON(json['meta']),
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(RetailShiftFromJSON)),
    };
}

export function RetailShiftListToJSON(json: any): RetailShiftList {
    return RetailShiftListToJSONTyped(json, false);
}

export function RetailShiftListToJSONTyped(value?: RetailShiftList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'context': ContextToJSON(value['context']),
        'meta': MetaListToJSON(value['meta']),
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(RetailShiftToJSON)),
    };
}

