/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { RetailStoreEnvironmentChequePrinterFiscalMemory } from './RetailStoreEnvironmentChequePrinterFiscalMemory.js';
import {
    RetailStoreEnvironmentChequePrinterFiscalMemoryFromJSON,
    RetailStoreEnvironmentChequePrinterFiscalMemoryFromJSONTyped,
    RetailStoreEnvironmentChequePrinterFiscalMemoryToJSON,
    RetailStoreEnvironmentChequePrinterFiscalMemoryToJSONTyped,
} from './RetailStoreEnvironmentChequePrinterFiscalMemory.js';
import type { RetailStoreEnvironmentChequePrinterDriver } from './RetailStoreEnvironmentChequePrinterDriver.js';
import {
    RetailStoreEnvironmentChequePrinterDriverFromJSON,
    RetailStoreEnvironmentChequePrinterDriverFromJSONTyped,
    RetailStoreEnvironmentChequePrinterDriverToJSON,
    RetailStoreEnvironmentChequePrinterDriverToJSONTyped,
} from './RetailStoreEnvironmentChequePrinterDriver.js';

/**
 * Информация о чековом принтере
 * @export
 * @interface RetailStoreEnvironmentChequePrinter
 */
export interface RetailStoreEnvironmentChequePrinter {
    /**
     * 
     * @type {RetailStoreEnvironmentChequePrinterDriver}
     * @memberof RetailStoreEnvironmentChequePrinter
     */
    driver?: RetailStoreEnvironmentChequePrinterDriver;
    /**
     * Версия прошивки
     * @type {string}
     * @memberof RetailStoreEnvironmentChequePrinter
     */
    firmwareVersion?: string;
    /**
     * Версия фискальных данных
     * @type {string}
     * @memberof RetailStoreEnvironmentChequePrinter
     */
    fiscalDataVersion?: string;
    /**
     * 
     * @type {RetailStoreEnvironmentChequePrinterFiscalMemory}
     * @memberof RetailStoreEnvironmentChequePrinter
     */
    fiscalMemory?: RetailStoreEnvironmentChequePrinterFiscalMemory;
    /**
     * Наименование чекового принтера
     * @type {string}
     * @memberof RetailStoreEnvironmentChequePrinter
     */
    name?: string;
    /**
     * Серийный номер чекового принтера
     * @type {string}
     * @memberof RetailStoreEnvironmentChequePrinter
     */
    serial?: string;
    /**
     * Производитель чекового принтера
     * @type {string}
     * @memberof RetailStoreEnvironmentChequePrinter
     */
    vendor?: string;
}


/**
 * Check if a given object implements the RetailStoreEnvironmentChequePrinter interface.
 */
export function instanceOfRetailStoreEnvironmentChequePrinter(value: object): value is RetailStoreEnvironmentChequePrinter {
    return true;
}

export function RetailStoreEnvironmentChequePrinterFromJSON(json: any): RetailStoreEnvironmentChequePrinter {
    return RetailStoreEnvironmentChequePrinterFromJSONTyped(json, false);
}

export function RetailStoreEnvironmentChequePrinterFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetailStoreEnvironmentChequePrinter {
    if (json == null) {
        return json;
    }
    return {
        'driver': json['driver'] == null ? undefined : RetailStoreEnvironmentChequePrinterDriverFromJSON(json['driver']),
        'firmwareVersion': json['firmwareVersion'] == null ? undefined : json['firmwareVersion'],
        'fiscalDataVersion': json['fiscalDataVersion'] == null ? undefined : json['fiscalDataVersion'],
        'fiscalMemory': json['fiscalMemory'] == null ? undefined : RetailStoreEnvironmentChequePrinterFiscalMemoryFromJSON(json['fiscalMemory']),
        'name': json['name'] == null ? undefined : json['name'],
        'serial': json['serial'] == null ? undefined : json['serial'],
        'vendor': json['vendor'] == null ? undefined : json['vendor'],
    };
}

export function RetailStoreEnvironmentChequePrinterToJSON(json: any): RetailStoreEnvironmentChequePrinter {
    return RetailStoreEnvironmentChequePrinterToJSONTyped(json, false);
}

export function RetailStoreEnvironmentChequePrinterToJSONTyped(value?: RetailStoreEnvironmentChequePrinter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'driver': RetailStoreEnvironmentChequePrinterDriverToJSON(value['driver']),
        'firmwareVersion': value['firmwareVersion'],
        'fiscalDataVersion': value['fiscalDataVersion'],
        'fiscalMemory': RetailStoreEnvironmentChequePrinterFiscalMemoryToJSON(value['fiscalMemory']),
        'name': value['name'],
        'serial': value['serial'],
        'vendor': value['vendor'],
    };
}

