/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Информация о ПО
 * @export
 * @interface RetailStoreEnvironmentSoftware
 */
export interface RetailStoreEnvironmentSoftware {
    /**
     * Наименование ПО
     * @type {string}
     * @memberof RetailStoreEnvironmentSoftware
     */
    name?: string;
    /**
     * Производитель ПО
     * @type {string}
     * @memberof RetailStoreEnvironmentSoftware
     */
    vendor?: string;
    /**
     * Версия ПО
     * @type {string}
     * @memberof RetailStoreEnvironmentSoftware
     */
    version?: string;
}


/**
 * Check if a given object implements the RetailStoreEnvironmentSoftware interface.
 */
export function instanceOfRetailStoreEnvironmentSoftware(value: object): value is RetailStoreEnvironmentSoftware {
    return true;
}

export function RetailStoreEnvironmentSoftwareFromJSON(json: any): RetailStoreEnvironmentSoftware {
    return RetailStoreEnvironmentSoftwareFromJSONTyped(json, false);
}

export function RetailStoreEnvironmentSoftwareFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetailStoreEnvironmentSoftware {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'] == null ? undefined : json['name'],
        'vendor': json['vendor'] == null ? undefined : json['vendor'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function RetailStoreEnvironmentSoftwareToJSON(json: any): RetailStoreEnvironmentSoftware {
    return RetailStoreEnvironmentSoftwareToJSONTyped(json, false);
}

export function RetailStoreEnvironmentSoftwareToJSONTyped(value?: RetailStoreEnvironmentSoftware | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'vendor': value['vendor'],
        'version': value['version'],
    };
}

