/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Возможные значения пермиссий script
 * @export
 */
export const ScriptPermissionValue = {
    No: 'NO',
    AuthorOrAssignee: 'AUTHOR_OR_ASSIGNEE',
    Assignee: 'ASSIGNEE',
    Author: 'AUTHOR',
    All: 'ALL'
} as const;
export type ScriptPermissionValue = typeof ScriptPermissionValue[keyof typeof ScriptPermissionValue];


export function instanceOfScriptPermissionValue(value: any): boolean {
    for (const key in ScriptPermissionValue) {
        if (Object.prototype.hasOwnProperty.call(ScriptPermissionValue, key)) {
            if (ScriptPermissionValue[key as keyof typeof ScriptPermissionValue] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ScriptPermissionValueFromJSON(json: any): ScriptPermissionValue {
    return ScriptPermissionValueFromJSONTyped(json, false);
}

export function ScriptPermissionValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScriptPermissionValue {
    return json as ScriptPermissionValue;
}

export function ScriptPermissionValueToJSON(value?: ScriptPermissionValue | null): any {
    return value as any;
}

export function ScriptPermissionValueToJSONTyped(value: any, ignoreDiscriminator: boolean): ScriptPermissionValue {
    return value as ScriptPermissionValue;
}

