/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Group } from './Group.js';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Uom } from './Uom.js';
import {
    UomFromJSON,
    UomFromJSONTyped,
    UomToJSON,
    UomToJSONTyped,
} from './Uom.js';
import type { Employee } from './Employee.js';
import {
    EmployeeFromJSON,
    EmployeeFromJSONTyped,
    EmployeeToJSON,
    EmployeeToJSONTyped,
} from './Employee.js';
import type { FileList } from './FileList.js';
import {
    FileListFromJSON,
    FileListFromJSONTyped,
    FileListToJSON,
    FileListToJSONTyped,
} from './FileList.js';
import type { Price } from './Price.js';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price.js';
import type { Barcode } from './Barcode.js';
import {
    BarcodeFromJSON,
    BarcodeFromJSONTyped,
    BarcodeToJSON,
    BarcodeToJSONTyped,
} from './Barcode.js';
import type { AttributeAbstract } from './AttributeAbstract.js';
import {
    AttributeAbstractFromJSON,
    AttributeAbstractFromJSONTyped,
    AttributeAbstractToJSON,
    AttributeAbstractToJSONTyped,
} from './AttributeAbstract.js';
import type { ProductFolder } from './ProductFolder.js';
import {
    ProductFolderFromJSON,
    ProductFolderFromJSONTyped,
    ProductFolderToJSON,
    ProductFolderToJSONTyped,
} from './ProductFolder.js';
import type { SalePrice } from './SalePrice.js';
import {
    SalePriceFromJSON,
    SalePriceFromJSONTyped,
    SalePriceToJSON,
    SalePriceToJSONTyped,
} from './SalePrice.js';

import * as ServicePolymorphicParent from './ProductMarker.js';
/**
 * 
 * @export
 * @interface Service
 */
export interface ServiceOwn {
    /**
     * 
     * @type {Meta}
     * @memberof Service
     */
    meta?: Meta;
    /**
     * ID услуги
     * @type {string}
     * @memberof Service
     */
    readonly id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof Service
     */
    readonly accountId?: string;
    /**
     * Добавлена ли услуга в архив
     * @type {boolean}
     * @memberof Service
     */
    archived?: boolean;
    /**
     * Наименование услуги
     * @type {string}
     * @memberof Service
     */
    name?: string;
    /**
     * Код услуги
     * @type {string}
     * @memberof Service
     */
    code?: string;
    /**
     * Внешний код услуги
     * @type {string}
     * @memberof Service
     */
    externalCode?: string;
    /**
     * Наименование группы, в которую входит услуга
     * @type {string}
     * @memberof Service
     */
    readonly pathName?: string;
    /**
     * Описание услуги
     * @type {string}
     * @memberof Service
     */
    description?: string | null;
    /**
     * НДС %
     * @type {number}
     * @memberof Service
     */
    vat?: number;
    /**
     * Включен ли НДС для услуги
     * @type {boolean}
     * @memberof Service
     */
    vatEnabled?: boolean;
    /**
     * Используется ли ставка НДС родительской группы
     * @type {boolean}
     * @memberof Service
     */
    useParentVat?: boolean;
    /**
     * Реальный НДС %
     * @type {number}
     * @memberof Service
     */
    readonly effectiveVat?: number;
    /**
     * Дополнительный признак для определения разграничения реального НДС
     * @type {boolean}
     * @memberof Service
     */
    readonly effectiveVatEnabled?: boolean;
    /**
     * Признак запрета скидок
     * @type {boolean}
     * @memberof Service
     */
    discountProhibited?: boolean;
    /**
     * Общий доступ
     * @type {boolean}
     * @memberof Service
     */
    shared?: boolean;
    /**
     * 
     * @type {Group}
     * @memberof Service
     */
    group?: Group;
    /**
     * Метаданные владельца (Сотрудника)
     * @type {Employee}
     * @memberof Service
     */
    owner?: Employee | null;
    /**
     * Момент последнего обновления сущности
     * @type {string}
     * @memberof Service
     */
    readonly updated?: string;
    /**
     * 
     * @type {Price}
     * @memberof Service
     */
    buyPrice?: Price;
    /**
     * Цены продажи
     * @type {Array<SalePrice>}
     * @memberof Service
     */
    salePrices?: Array<SalePrice> | null;
    /**
     * Метаданные единиц измерения
     * @type {Uom}
     * @memberof Service
     */
    uom?: Uom | null;
    /**
     * Метаданные группы Услуги
     * @type {ProductFolder}
     * @memberof Service
     */
    productFolder?: ProductFolder | null;
    /**
     * Метаданные массива Файлов
     * @type {FileList}
     * @memberof Service
     */
    files?: FileList | null;
    /**
     * Штрихкоды услуги
     * @type {Array<Barcode>}
     * @memberof Service
     */
    barcodes?: Array<Barcode> | null;
    /**
     * Признак предмета расчета. Известные значения описаны в PaymentItemType
     * @type {string}
     * @memberof Service
     */
    paymentItemType?: string;
    /**
     * Код системы налогообложения. Известные значения описаны в TaxSystem
     * @type {string}
     * @memberof Service
     */
    taxSystem?: string;
    /**
     * Дополнительные поля
     * @type {Array<AttributeAbstract>}
     * @memberof Service
     */
    attributes?: Array<AttributeAbstract> | null;
    /**
     * 
     * @type {Price}
     * @memberof Service
     */
    minPrice?: Price;
    /**
     * ID синхронизации
     * @type {string}
     * @memberof Service
     */
    syncId?: string;
}
export type Service = ServiceOwn & ServicePolymorphicParent.ProductMarker;


/**
 * Check if a given object implements the Service interface.
 */
export function instanceOfService(value: object): value is Service {
    return true;
}

export function ServiceFromJSON(json: any): Service {
    return ServiceFromJSONTyped(json, false);
}

export function ServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Service {
    if (json == null) {
        return json;
    }
    return {
        ...ServicePolymorphicParent.ProductMarkerFromJSONTyped(json, true),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'externalCode': json['externalCode'] == null ? undefined : json['externalCode'],
        'pathName': json['pathName'] == null ? undefined : json['pathName'],
        'description': json['description'] == null ? undefined : json['description'],
        'vat': json['vat'] == null ? undefined : json['vat'],
        'vatEnabled': json['vatEnabled'] == null ? undefined : json['vatEnabled'],
        'useParentVat': json['useParentVat'] == null ? undefined : json['useParentVat'],
        'effectiveVat': json['effectiveVat'] == null ? undefined : json['effectiveVat'],
        'effectiveVatEnabled': json['effectiveVatEnabled'] == null ? undefined : json['effectiveVatEnabled'],
        'discountProhibited': json['discountProhibited'] == null ? undefined : json['discountProhibited'],
        'shared': json['shared'] == null ? undefined : json['shared'],
        'group': json['group'] == null ? undefined : GroupFromJSON(json['group']),
        'owner': json['owner'] == null ? undefined : EmployeeFromJSON(json['owner']),
        'updated': json['updated'] == null ? undefined : json['updated'],
        'buyPrice': json['buyPrice'] == null ? undefined : PriceFromJSON(json['buyPrice']),
        'salePrices': json['salePrices'] == null ? undefined : ((json['salePrices'] as Array<any>).map(SalePriceFromJSON)),
        'uom': json['uom'] == null ? undefined : UomFromJSON(json['uom']),
        'productFolder': json['productFolder'] == null ? undefined : ProductFolderFromJSON(json['productFolder']),
        'files': json['files'] == null ? undefined : FileListFromJSON(json['files']),
        'barcodes': json['barcodes'] == null ? undefined : ((json['barcodes'] as Array<any>).map(BarcodeFromJSON)),
        'paymentItemType': json['paymentItemType'] == null ? undefined : json['paymentItemType'],
        'taxSystem': json['taxSystem'] == null ? undefined : json['taxSystem'],
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(AttributeAbstractFromJSON)),
        'minPrice': json['minPrice'] == null ? undefined : PriceFromJSON(json['minPrice']),
        'syncId': json['syncId'] == null ? undefined : json['syncId'],
    };
}

export function ServiceToJSON(json: any): Service {
    return ServiceToJSONTyped(json, false);
}

export function ServiceToJSONTyped(value?: Omit<Service, 'id'|'accountId'|'pathName'|'effectiveVat'|'effectiveVatEnabled'|'updated'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...ServicePolymorphicParent.ProductMarkerToJSONTyped(value as any, true),
        'meta': MetaToJSON(value['meta']),
        'archived': value['archived'],
        'name': value['name'],
        'code': value['code'],
        'externalCode': value['externalCode'],
        'description': value['description'],
        'vat': value['vat'],
        'vatEnabled': value['vatEnabled'],
        'useParentVat': value['useParentVat'],
        'discountProhibited': value['discountProhibited'],
        'shared': value['shared'],
        'group': GroupToJSON(value['group']),
        'owner': EmployeeToJSON(value['owner']),
        'buyPrice': PriceToJSON(value['buyPrice']),
        'salePrices': value['salePrices'] == null ? undefined : ((value['salePrices'] as Array<any>).map(SalePriceToJSON)),
        'uom': UomToJSON(value['uom']),
        'productFolder': ProductFolderToJSON(value['productFolder']),
        'files': FileListToJSON(value['files']),
        'barcodes': value['barcodes'] == null ? undefined : ((value['barcodes'] as Array<any>).map(BarcodeToJSON)),
        'paymentItemType': value['paymentItemType'],
        'taxSystem': value['taxSystem'],
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(AttributeAbstractToJSON)),
        'minPrice': PriceToJSON(value['minPrice']),
        'syncId': value['syncId'],
    };
}

