/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Известные значения типа статуса
 * @export
 */
export const StateType = {
    Regular: 'Regular',
    Successful: 'Successful',
    Unsuccessful: 'Unsuccessful'
} as const;
export type StateType = typeof StateType[keyof typeof StateType];


export function instanceOfStateType(value: any): boolean {
    for (const key in StateType) {
        if (Object.prototype.hasOwnProperty.call(StateType, key)) {
            if (StateType[key as keyof typeof StateType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StateTypeFromJSON(json: any): StateType {
    return StateTypeFromJSONTyped(json, false);
}

export function StateTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateType {
    return json as StateType;
}

export function StateTypeToJSON(value?: StateType | null): any {
    return value as any;
}

export function StateTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): StateType {
    return value as StateType;
}

