/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';

/**
 * Остаток по позиции в отчете «Остатки по документам»
 * @export
 * @interface StockByOperationPosition
 */
export interface StockByOperationPosition {
    /**
     * 
     * @type {Meta}
     * @memberof StockByOperationPosition
     */
    meta?: Meta;
    /**
     * Наименование позиции
     * @type {string}
     * @memberof StockByOperationPosition
     */
    name?: string;
    /**
     * Остаток
     * @type {number}
     * @memberof StockByOperationPosition
     */
    stock?: number;
    /**
     * Себестоимость в копейках
     * @type {number}
     * @memberof StockByOperationPosition
     */
    cost?: number;
    /**
     * Ожидание. У сущности Комплект значение всегда `0`
     * @type {number}
     * @memberof StockByOperationPosition
     */
    inTransit?: number;
    /**
     * Резерв. У сущности Комплект значение всегда `0`
     * @type {number}
     * @memberof StockByOperationPosition
     */
    reserve?: number;
    /**
     * Доступно. У сущности Комплект значение всегда `0`
     * @type {number}
     * @memberof StockByOperationPosition
     */
    quantity?: number;
}


/**
 * Check if a given object implements the StockByOperationPosition interface.
 */
export function instanceOfStockByOperationPosition(value: object): value is StockByOperationPosition {
    return true;
}

export function StockByOperationPositionFromJSON(json: any): StockByOperationPosition {
    return StockByOperationPositionFromJSONTyped(json, false);
}

export function StockByOperationPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockByOperationPosition {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'name': json['name'] == null ? undefined : json['name'],
        'stock': json['stock'] == null ? undefined : json['stock'],
        'cost': json['cost'] == null ? undefined : json['cost'],
        'inTransit': json['inTransit'] == null ? undefined : json['inTransit'],
        'reserve': json['reserve'] == null ? undefined : json['reserve'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function StockByOperationPositionToJSON(json: any): StockByOperationPosition {
    return StockByOperationPositionToJSONTyped(json, false);
}

export function StockByOperationPositionToJSONTyped(value?: StockByOperationPosition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaToJSON(value['meta']),
        'name': value['name'],
        'stock': value['stock'],
        'cost': value['cost'],
        'inTransit': value['inTransit'],
        'reserve': value['reserve'],
        'quantity': value['quantity'],
    };
}

