/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { AttributeMetaInfoList } from './AttributeMetaInfoList.js';
import {
    AttributeMetaInfoListFromJSON,
    AttributeMetaInfoListFromJSONTyped,
    AttributeMetaInfoListToJSON,
    AttributeMetaInfoListToJSONTyped,
} from './AttributeMetaInfoList.js';

/**
 * Метаданные складов
 * @export
 * @interface StoreMetadata
 */
export interface StoreMetadata {
    /**
     * 
     * @type {Meta}
     * @memberof StoreMetadata
     */
    meta?: Meta;
    /**
     * 
     * @type {AttributeMetaInfoList}
     * @memberof StoreMetadata
     */
    attributes?: AttributeMetaInfoList;
    /**
     * Создавать новые склады с меткой "Общий"
     * @type {boolean}
     * @memberof StoreMetadata
     */
    createShared?: boolean;
}


/**
 * Check if a given object implements the StoreMetadata interface.
 */
export function instanceOfStoreMetadata(value: object): value is StoreMetadata {
    return true;
}

export function StoreMetadataFromJSON(json: any): StoreMetadata {
    return StoreMetadataFromJSONTyped(json, false);
}

export function StoreMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMetadata {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'attributes': json['attributes'] == null ? undefined : AttributeMetaInfoListFromJSON(json['attributes']),
        'createShared': json['createShared'] == null ? undefined : json['createShared'],
    };
}

export function StoreMetadataToJSON(json: any): StoreMetadata {
    return StoreMetadataToJSONTyped(json, false);
}

export function StoreMetadataToJSONTyped(value?: StoreMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaToJSON(value['meta']),
        'attributes': AttributeMetaInfoListToJSON(value['attributes']),
        'createShared': value['createShared'],
    };
}

