/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Employee } from './Employee.js';
import {
    EmployeeFromJSON,
    EmployeeFromJSONTyped,
    EmployeeToJSON,
    EmployeeToJSONTyped,
} from './Employee.js';

/**
 * Файл комментария к Задаче
 * @export
 * @interface TaskNoteFile
 */
export interface TaskNoteFile {
    /**
     * 
     * @type {Meta}
     * @memberof TaskNoteFile
     */
    meta?: Meta;
    /**
     * ID файла
     * @type {string}
     * @memberof TaskNoteFile
     */
    readonly id?: string;
    /**
     * Название файла
     * @type {string}
     * @memberof TaskNoteFile
     */
    title?: string;
    /**
     * Имя файла
     * @type {string}
     * @memberof TaskNoteFile
     */
    filename?: string;
    /**
     * Файл, закодированный в Base64
     * @type {string}
     * @memberof TaskNoteFile
     */
    content?: string;
    /**
     * Размер файла в байтах
     * @type {number}
     * @memberof TaskNoteFile
     */
    readonly size?: number;
    /**
     * Время создания объекта
     * @type {string}
     * @memberof TaskNoteFile
     */
    readonly created?: string;
    /**
     * 
     * @type {Employee}
     * @memberof TaskNoteFile
     */
    createdBy?: Employee;
    /**
     * 
     * @type {Meta}
     * @memberof TaskNoteFile
     */
    tiny?: Meta;
    /**
     * 
     * @type {Meta}
     * @memberof TaskNoteFile
     */
    miniature?: Meta;
}


/**
 * Check if a given object implements the TaskNoteFile interface.
 */
export function instanceOfTaskNoteFile(value: object): value is TaskNoteFile {
    return true;
}

export function TaskNoteFileFromJSON(json: any): TaskNoteFile {
    return TaskNoteFileFromJSONTyped(json, false);
}

export function TaskNoteFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskNoteFile {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'content': json['content'] == null ? undefined : json['content'],
        'size': json['size'] == null ? undefined : json['size'],
        'created': json['created'] == null ? undefined : json['created'],
        'createdBy': json['createdBy'] == null ? undefined : EmployeeFromJSON(json['createdBy']),
        'tiny': json['tiny'] == null ? undefined : MetaFromJSON(json['tiny']),
        'miniature': json['miniature'] == null ? undefined : MetaFromJSON(json['miniature']),
    };
}

export function TaskNoteFileToJSON(json: any): TaskNoteFile {
    return TaskNoteFileToJSONTyped(json, false);
}

export function TaskNoteFileToJSONTyped(value?: Omit<TaskNoteFile, 'id'|'size'|'created'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaToJSON(value['meta']),
        'title': value['title'],
        'filename': value['filename'],
        'content': value['content'],
        'createdBy': EmployeeToJSON(value['createdBy']),
        'tiny': MetaToJSON(value['tiny']),
        'miniature': MetaToJSON(value['miniature']),
    };
}

