/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Employee } from './Employee.js';
import {
    EmployeeFromJSON,
    EmployeeFromJSONTyped,
    EmployeeToJSON,
    EmployeeToJSONTyped,
} from './Employee.js';
import type { FileList } from './FileList.js';
import {
    FileListFromJSON,
    FileListFromJSONTyped,
    FileListToJSON,
    FileListToJSONTyped,
} from './FileList.js';
import type { Application } from './Application.js';
import {
    ApplicationFromJSON,
    ApplicationFromJSONTyped,
    ApplicationToJSON,
    ApplicationToJSONTyped,
} from './Application.js';

import * as TaskNotePolymorphicParent from './EntityWithMeta.js';
/**
 * Комментарий к Задаче
 * @export
 * @interface TaskNote
 */
export interface TaskNoteOwn {
    /**
     * 
     * @type {Meta}
     * @memberof TaskNote
     */
    meta?: Meta;
    /**
     * ID комментария к Задаче
     * @type {string}
     * @memberof TaskNote
     */
    readonly id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof TaskNote
     */
    readonly accountId?: string;
    /**
     * 
     * @type {Employee}
     * @memberof TaskNote
     */
    author?: Employee;
    /**
     * 
     * @type {Application}
     * @memberof TaskNote
     */
    authorApplication?: Application;
    /**
     * Момент создания комментария
     * @type {string}
     * @memberof TaskNote
     */
    readonly moment?: string;
    /**
     * Текст комментария
     * @type {string}
     * @memberof TaskNote
     */
    text?: string;
    /**
     * Метаданные массива Файлов
     * @type {FileList}
     * @memberof TaskNote
     */
    files?: FileList | null;
}
export type TaskNote = TaskNoteOwn & TaskNotePolymorphicParent.EntityWithMeta;


/**
 * Check if a given object implements the TaskNote interface.
 */
export function instanceOfTaskNote(value: object): value is TaskNote {
    return true;
}

export function TaskNoteFromJSON(json: any): TaskNote {
    return TaskNoteFromJSONTyped(json, false);
}

export function TaskNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskNote {
    if (json == null) {
        return json;
    }
    return {
        ...TaskNotePolymorphicParent.EntityWithMetaFromJSONTyped(json, true),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'author': json['author'] == null ? undefined : EmployeeFromJSON(json['author']),
        'authorApplication': json['authorApplication'] == null ? undefined : ApplicationFromJSON(json['authorApplication']),
        'moment': json['moment'] == null ? undefined : json['moment'],
        'text': json['text'] == null ? undefined : json['text'],
        'files': json['files'] == null ? undefined : FileListFromJSON(json['files']),
    };
}

export function TaskNoteToJSON(json: any): TaskNote {
    return TaskNoteToJSONTyped(json, false);
}

export function TaskNoteToJSONTyped(value?: Omit<TaskNote, 'id'|'accountId'|'moment'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...TaskNotePolymorphicParent.EntityWithMetaToJSONTyped(value as any, true),
        'meta': MetaToJSON(value['meta']),
        'author': EmployeeToJSON(value['author']),
        'authorApplication': ApplicationToJSON(value['authorApplication']),
        'text': value['text'],
        'files': FileListToJSON(value['files']),
    };
}

