/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Известные значения типа маркируемой продукции
 * @export
 */
export const TrackingType = {
    BeerAlcohol: 'BEER_ALCOHOL',
    Bicycle: 'BICYCLE',
    Electronics: 'ELECTRONICS',
    FoodSupplement: 'FOOD_SUPPLEMENT',
    LpClothes: 'LP_CLOTHES',
    LpLinens: 'LP_LINENS',
    MedicalDevices: 'MEDICAL_DEVICES',
    Milk: 'MILK',
    Nabeer: 'NABEER',
    Ncp: 'NCP',
    NotTracked: 'NOT_TRACKED',
    Otp: 'OTP',
    Perfumery: 'PERFUMERY',
    PetFood: 'PET_FOOD',
    Sanitizer: 'SANITIZER',
    Seafood: 'SEAFOOD',
    Shoes: 'SHOES',
    SoftDrinks: 'SOFT_DRINKS',
    Tires: 'TIRES',
    Tobacco: 'TOBACCO',
    VegetableOil: 'VEGETABLE_OIL',
    Vetpharma: 'VETPHARMA',
    Water: 'WATER'
} as const;
export type TrackingType = typeof TrackingType[keyof typeof TrackingType];


export function instanceOfTrackingType(value: any): boolean {
    for (const key in TrackingType) {
        if (Object.prototype.hasOwnProperty.call(TrackingType, key)) {
            if (TrackingType[key as keyof typeof TrackingType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TrackingTypeFromJSON(json: any): TrackingType {
    return TrackingTypeFromJSONTyped(json, false);
}

export function TrackingTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackingType {
    return json as TrackingType;
}

export function TrackingTypeToJSON(value?: TrackingType | null): any {
    return value as any;
}

export function TrackingTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): TrackingType {
    return value as TrackingType;
}

