/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { VariantCharacteristic } from './VariantCharacteristic.js';
import {
    VariantCharacteristicFromJSON,
    VariantCharacteristicFromJSONTyped,
    VariantCharacteristicToJSON,
    VariantCharacteristicToJSONTyped,
} from './VariantCharacteristic.js';

/**
 * Метаданные модификации
 * @export
 * @interface VariantMetadata
 */
export interface VariantMetadata {
    /**
     * 
     * @type {Meta}
     * @memberof VariantMetadata
     */
    meta?: Meta;
    /**
     * Характеристики Модификации
     * @type {Array<VariantCharacteristic>}
     * @memberof VariantMetadata
     */
    characteristics?: Array<VariantCharacteristic>;
}


/**
 * Check if a given object implements the VariantMetadata interface.
 */
export function instanceOfVariantMetadata(value: object): value is VariantMetadata {
    return true;
}

export function VariantMetadataFromJSON(json: any): VariantMetadata {
    return VariantMetadataFromJSONTyped(json, false);
}

export function VariantMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): VariantMetadata {
    if (json == null) {
        return json;
    }
    return {
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'characteristics': json['characteristics'] == null ? undefined : ((json['characteristics'] as Array<any>).map(VariantCharacteristicFromJSON)),
    };
}

export function VariantMetadataToJSON(json: any): VariantMetadata {
    return VariantMetadataToJSONTyped(json, false);
}

export function VariantMetadataToJSONTyped(value?: VariantMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        'meta': MetaToJSON(value['meta']),
        'characteristics': value['characteristics'] == null ? undefined : ((value['characteristics'] as Array<any>).map(VariantCharacteristicToJSON)),
    };
}

