/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Тип отчёта остатков для вебхука на изменение остатков. Известные значения поля reportType
 * @export
 */
export const WebhookStockReportType = {
    All: 'all',
    Bystore: 'bystore'
} as const;
export type WebhookStockReportType = typeof WebhookStockReportType[keyof typeof WebhookStockReportType];


export function instanceOfWebhookStockReportType(value: any): boolean {
    for (const key in WebhookStockReportType) {
        if (Object.prototype.hasOwnProperty.call(WebhookStockReportType, key)) {
            if (WebhookStockReportType[key as keyof typeof WebhookStockReportType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WebhookStockReportTypeFromJSON(json: any): WebhookStockReportType {
    return WebhookStockReportTypeFromJSONTyped(json, false);
}

export function WebhookStockReportTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookStockReportType {
    return json as WebhookStockReportType;
}

export function WebhookStockReportTypeToJSON(value?: WebhookStockReportType | null): any {
    return value as any;
}

export function WebhookStockReportTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): WebhookStockReportType {
    return value as WebhookStockReportType;
}

