/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Действие, которое отслеживается вебхуком или действие в уведомлении
 * @export
 */
export const WebhookAction = {
    Create: 'CREATE',
    Update: 'UPDATE',
    Delete: 'DELETE',
    Processed: 'PROCESSED'
} as const;
export type WebhookAction = typeof WebhookAction[keyof typeof WebhookAction];


export function instanceOfWebhookAction(value: any): boolean {
    for (const key in WebhookAction) {
        if (Object.prototype.hasOwnProperty.call(WebhookAction, key)) {
            if (WebhookAction[key as keyof typeof WebhookAction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WebhookActionFromJSON(json: any): WebhookAction {
    return WebhookActionFromJSONTyped(json, false);
}

export function WebhookActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookAction {
    return json as WebhookAction;
}

export function WebhookActionToJSON(value?: WebhookAction | null): any {
    return value as any;
}

export function WebhookActionToJSONTyped(value: any, ignoreDiscriminator: boolean): WebhookAction {
    return value as WebhookAction;
}

