/* tslint:disable */
/* eslint-disable */
/**
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Application } from './Application.js';
import {
    ApplicationFromJSON,
    ApplicationFromJSONTyped,
    ApplicationToJSON,
    ApplicationToJSONTyped,
} from './Application.js';

import * as WebhookPolymorphicParent from './EntityWithMeta.js';
/**
 * Вебхук
 * @export
 * @interface Webhook
 */
export interface WebhookOwn {
    /**
     * 
     * @type {Meta}
     * @memberof Webhook
     */
    meta?: Meta;
    /**
     * ID вебхука
     * @type {string}
     * @memberof Webhook
     */
    readonly id?: string;
    /**
     * ID учетной записи
     * @type {string}
     * @memberof Webhook
     */
    readonly accountId?: string;
    /**
     * Тип сущности, к которой привязан вебхук. Известные ограничения см. в документации (нельзя webhook, discount, notes)
     * @type {string}
     * @memberof Webhook
     */
    entityType?: string;
    /**
     * URL, по которому отправляется уведомление
     * @type {string}
     * @memberof Webhook
     */
    url?: string;
    /**
     * HTTP метод запроса к URL подписчика. Известные значения описаны в WebhookMethod
     * @type {string}
     * @memberof Webhook
     */
    method?: string;
    /**
     * Вебхук включен или отключен
     * @type {boolean}
     * @memberof Webhook
     */
    enabled?: boolean;
    /**
     * Отслеживаемое действие. Известные значения описаны в WebhookAction. Значение PROCESSED допустимо только для асинхронных задач
     * @type {string}
     * @memberof Webhook
     */
    action?: string;
    /**
     * Режим для действия UPDATE. Известные значения описаны в WebhookDiffType
     * @type {string}
     * @memberof Webhook
     */
    diffType?: string | null;
    /**
     * 
     * @type {Application}
     * @memberof Webhook
     */
    authorApplication?: Application;
}
export type Webhook = WebhookOwn & WebhookPolymorphicParent.EntityWithMeta;


/**
 * Check if a given object implements the Webhook interface.
 */
export function instanceOfWebhook(value: object): value is Webhook {
    return true;
}

export function WebhookFromJSON(json: any): Webhook {
    return WebhookFromJSONTyped(json, false);
}

export function WebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Webhook {
    if (json == null) {
        return json;
    }
    return {
        ...WebhookPolymorphicParent.EntityWithMetaFromJSONTyped(json, true),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'entityType': json['entityType'] == null ? undefined : json['entityType'],
        'url': json['url'] == null ? undefined : json['url'],
        'method': json['method'] == null ? undefined : json['method'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'action': json['action'] == null ? undefined : json['action'],
        'diffType': json['diffType'] == null ? undefined : json['diffType'],
        'authorApplication': json['authorApplication'] == null ? undefined : ApplicationFromJSON(json['authorApplication']),
    };
}

export function WebhookToJSON(json: any): Webhook {
    return WebhookToJSONTyped(json, false);
}

export function WebhookToJSONTyped(value?: Omit<Webhook, 'id'|'accountId'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return {
        ...WebhookPolymorphicParent.EntityWithMetaToJSONTyped(value as any, true),
        'meta': MetaToJSON(value['meta']),
        'entityType': value['entityType'],
        'url': value['url'],
        'method': value['method'],
        'enabled': value['enabled'],
        'action': value['action'],
        'diffType': value['diffType'],
        'authorApplication': ApplicationToJSON(value['authorApplication']),
    };
}

